### ISSUE TITLE
When uploading: error doing PATCH request to data gateway

### ISSUE THREAD

**Issue by yuri-becker** [owncloud/ocis#10156]
## Describe the bug
File uploads via the web ui fail and the server has a high CPU usage without any user activity.

## Steps to reproduce
Try to upload a file via the web ui.

## Expected behavior
The upload succeedes and the file is available.

## Actual behavior
Upload fails with `Unknown Error`. For other users, the upload seemes to have succeded, but the file is grayed out and not available.
The log the contains entries like this:
```json
{"level":"error","service":"ocdav","name":"com.owncloud.web.ocdav","traceid":"8ff9c83be64eddf7f24fc1f19a3c2769","request-id":"6dde09b8-4611-4743-a38e-bd8605657e00","path":"/public/POcnTlUcNrxpUXb/<redacted>","error":"Patch \"https://cloud.catboy.house/data/<redacted>\": context canceled","time":"2024-09-25T06:49:43Z","message":"error doing PATCH request to data gateway"}
```

Also, this log keeps popping up
```json
{"level":"error","service":"postprocessing","uploadID":"da362552-3dfb-4952-a535-89226a610a0f","error":"Failed to delete data: nats: timeout","time":"2024-09-25T07:27:18Z","message":"cannot delete upload"}
```

## Setup
The server is managed via Ansible.
The container setup is this:
<details>
<p>

```yaml
- name: 🚀 Starts container
  community.docker.docker_container:
    name: "{{ owncloud_container_name }}"
    image: owncloud/ocis
    state: started
    restart_policy: unless-stopped
    ports:
      - "{{ docker_gateway }}:{{ owncloud_service_port }}:9200"
    entrypoint:
      - /bin/sh
    command: ["-c", "ocis init || true; ocis server"]
    env:
      OCIS_INSECURE: "false"
      OCIS_URL: "https://{{ owncloud_domain }}"
      PROXY_HTTP_ADDR: "0.0.0.0:9200"
      PROXY_TLS: "false"
      OCIS_LOG_LEVEL: "warn"
      OCIS_ADD_RUN_SERVICES: "notifications"
      NOTIFICATIONS_SMTP_HOST: "{{ smtp_server }}"
      NOTIFICATIONS_SMTP_PORT: "{{ smtp_port }}"
      NOTIFICATIONS_SMTP_SENDER: "{{ owncloud_smtp_sender }}"
      NOTIFICATIONS_SMTP_USERNAME: "{{ owncloud_smtp_user }}"
      NOTIFICATIONS_SMTP_PASSWORD: "{{ owncloud_smtp_password }}"
      NOTIFICATIONS_SMTP_INSECURE: "false"
    user: "{{ owncloud_uid }}:{{ app_gid }}"
    volumes:
      - "{{ owncloud_volume_config }}:/etc/ocis"
      - "{{ owncloud_volume_data }}:/var/lib/ocis"

```
</p>
</details>

The reverse proxy (caddy) has this setup for owncloud:
<details>
<p>

```caddy
cloud.catboy.house {
    reverse_proxy 172.17.0.1:28946 {
        request_buffers 256k
        response_buffers 256k
    }
}
```

</p> 
</details>

The complete setup is here: [https://github.com/yuri-becker/catboy-house/tree/main/roles/owncloud](https://github.com/yuri-becker/catboy-house/tree/main/roles/owncloud)

## Additional context
I assume this is some kind of permission issue. Is OCIS having issues with changing the user?
Uploading via the client seems to work, or seemed to have worked.
