### ISSUE TITLE
User can't upload to public space (core access token is invalid)

### ISSUE THREAD

**Issue by yuri-becker** [owncloud/ocis#10220]
## Describe the bug
A single user can't upload to a shared, public (password-protected) space. There is no user feedback that the upload fails, the progress popup does not open.
The issue only persists in a specific space.

## Steps to reproduce
1. Go to space via link.
2. Try to upload a file.

## Setup

The container is managed via Ansible:

<details>
<p>

```yml
- name: 🚀 Starts container
  community.docker.docker_container:
    name: owncloud
    image: owncloud/ocis
    state: started
    restart_policy: unless-stopped
    ports:
      - " 172.17.0.1:28946:9200"
    entrypoint:
      - /bin/sh
    command: ["-c", "ocis init || true; ocis server"]
    env:
      OCIS_INSECURE: "false"
      OCIS_URL: "https://cloud.catboy.house"
      PROXY_HTTP_ADDR: "0.0.0.0:9200"
      PROXY_TLS: "false"
      OCIS_LOG_LEVEL: "warn"
      OCIS_ADD_RUN_SERVICES: "notifications"
      NOTIFICATIONS_SMTP_HOST: "{{ smtp_server }}"
      NOTIFICATIONS_SMTP_PORT: "{{ smtp_port }}"
      NOTIFICATIONS_SMTP_SENDER: "{{ owncloud_smtp_sender }}"
      NOTIFICATIONS_SMTP_USERNAME: "{{ owncloud_smtp_user }}"
      NOTIFICATIONS_SMTP_PASSWORD: "{{ owncloud_smtp_password }}"
      NOTIFICATIONS_SMTP_INSECURE: "false"
    user: "{{ owncloud_uid }}:{{ app_gid }}"
    volumes:
      - "{{ owncloud_volume_config }}:/etc/ocis"
      - "{{ owncloud_volume_data }}:/var/lib/ocis"
```

</p>
</details>

This is the caddy configuration for the site:

<details>
<p>

```
cloud.catboy.house {
    reverse_proxy 172.17.0.1:28946
    log {
        output file /var/log/caddy/cloud.catboy.house-access.log
    }
}⏎
```
</p>
</details>

The complete setup is here: https://github.com/yuri-becker/catboy-house/tree/main/roles/owncloud

## Additional context
The issue apparently exists using both MS Edge and DuckDuckGo's browser.
I can't reproduce the issue on my end, using the same file.
The file is a PDF of 225KB.
OCIS Version is 6.5.0
Web Client Version is 10.3.0.

The access and OCIS logs are attached (access log was filtered to requests from Edge, ocis log is right after a restart trying to upload the file).

[access.log](https://github.com/user-attachments/files/17228369/access.log)
[owncloud.log](https://github.com/user-attachments/files/17228370/owncloud.log)
