### ISSUE TITLE
Bind addresses are used as ip addresses to connect to server

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#10381]
## Describe the bug

The healthchecks use the http server bind address for connection to the server, eg:

https://github.com/owncloud/ocis/blob/f54979f0ad4d5c4b7b37d0270a23cc6d01739e96/services/proxy/pkg/server/debug/server.go#L20-L22

This fails if the http server bind address uses a bind-all-interfaces logic, like `0.0.0.0`.

## Steps to reproduce
1. Deploy eg. the development deployment example in Kubernetes
2. look at the pods 

## Expected behavior

Healthchecks succeed -> no pod restarts

## Actual behavior

Healthchecks fail -> pod restarts

## Setup

oCIS 6.6.0 in Kubernetes, eg. https://github.com/owncloud/ocis-charts/pull/778

**Comment by wkloucek** [comment]
I tried to workaround this by replacing the wildcard bind 0.0.0.0 by an actual interface ip, eg:

```
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            - name: GATEWAY_GRPC_ADDR
              value: $(POD_IP):9142
            - name: GATEWAY_DEBUG_ADDR
              value: $(POD_IP):9143
```

But this fails on the gateway, because it tries to talk to itself via 127.0.0.1 where it no longer listens if it only listens on the non-localhost interface ip instead of all interfaces including localhost. During a quick search, I didn't found a config option to tell the gateway where it could contact itself...
