### ISSUE TITLE
gateway tries to contact itself on 127.0.0.1, can't be changed?

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#10404]
I tried to workaround this by replacing the wildcard bind 0.0.0.0 by an actual interface ip, eg:

```
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            - name: GATEWAY_GRPC_ADDR
              value: $(POD_IP):9142
            - name: GATEWAY_DEBUG_ADDR
              value: $(POD_IP):9143
```

But this fails on the gateway, because it tries to talk to itself via 127.0.0.1. During a quick search, I didn't find a config option to tell the gateway where it could contact itself...

_Originally posted by @wkloucek in https://github.com/owncloud/ocis/issues/10381#issuecomment-2429155766_
