### ISSUE TITLE
[QA] Flaky changing quota steps - fails with 500 error

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#10603]
Builds:
- https://drone.owncloud.com/owncloud/ocis/41199/38/6
- https://drone.owncloud.com/owncloud/ocis/41198/22/5
- https://drone.owncloud.com/owncloud/ocis/41180/54/5
- https://drone.owncloud.com/owncloud/ocis/41185/38/6

```feature
    And user "Admin" has changed the quota of the personal space of "Alice Hansen" space to "1"                                          # SpacesContext::userHasChangedTheQuotaOfTheSpaceTo()
      Expected response status code should be 200
      Failed asserting that 500 matches expected 200.
```
```bash
==> REQUEST
PATCH /graph/v1.0/drives/28087b3e-b3a7-44a4-850f-082544e6f8b1$ca3ed4f6-c7ae-4ada-a482-95c459958ac3
X-Request-ID: coreApiShareOperationsToShares2/uploadToShare.feature:238-231
==> REQ BODY
{"quota":{"total":1}}

<== RESPONSE
500 Internal Server Error
X-Xss-Protection: 1; mode=block
<== RES BODY
{"error":{"code":"generalException","innererror":{"date":"2024-11-19T05:15:58Z","request-id":"coreApiShareOperationsToShares2/uploadToShare.feature:238-231"},"message":"grpc error"}}
```

Scenarios:
```
apiSpacesShares/shareOperations.feature:340
coreApiShareOperationsToShares2/uploadToShare.feature:218
coreApiShareOperationsToShares2/uploadToShare.feature:249
```

**Comment by saw-jan** [comment]
^
CC @ScharfViktor @micbar @kobergj

**Comment by micbar** [comment]
We should investigate why we get an `500` error in the DEV team.

**Comment by rhafer** [comment]
This is in the logs of the latest failed run:

```
"level":"error","service":"storage-users","pkg":"rgrpc","traceid":"c92e9c1513f71fd3755bfe9419e7db15","error":"open /root/.ocis/storage/users/spaces/b4/68c2d3-0bc1-4b41-bfe7-c85db387057d/nodes/b4/68/c2/d3/-0bc1-4b41-bfe7-c85db387057d.mlock: no such file or 
directory","req":{"storage_space":{"id":{"opaque_id":"96b0a8ee-ab8d-49e8-87dd-e1c3331c77f7$b468c2d3-0bc1-4b41-bfe7-c85db387057d"},"root":{"storage_id":"96b0a8ee-ab8d-49e8-87dd-e1c3331c77f7","opaque_id":"b468c2d3-0bc1-4b41-bfe7-c85db387057d","space_id":"b468
c2d3-0bc1-4b41-bfe7-c85db387057d"},"quota":{"quota_max_bytes":1}}},"time":"2024-11-27T09:23:36Z","message":"failed to update storage space"}
{"level":"error","service":"storage-users","pkg":"rgrpc","traceid":"c92e9c1513f71fd3755bfe9419e7db15","user-agent":"grpc-go/1.68.0","from":"tcp://127.0.0.1:34124","uri":"/cs3.storage.provider.v1beta1.SpacesAPI/UpdateStorageSpace","start":"27/Nov/2024:09:23:
36 +0000","end":"27/Nov/2024:09:23:36 +0000","time_ns":3131418,"code":"Unknown","time":"2024-11-27T09:23:36Z","message":"open /root/.ocis/storage/users/spaces/b4/68c2d3-0bc1-4b41-bfe7-c85db387057d/nodes/b4/68/c2/d3/-0bc1-4b41-bfe7-c85db387057d.mlock: no suc
h file or directory"}
```

The lock file disappeared?

**Comment by rhafer** [comment]
I created a stripped down ci config for reproducing this issue (https://github.com/owncloud/ocis/pull/10678). Of about 10 runs in that configuration only a single one (https://drone.owncloud.com/owncloud/ocis/41458) failed. After increasing the loglevel to debug, I could not reproduce this at all anymore :sob: 

Running stuff locally I wasn't able to reproduce this either.

**Comment by rhafer** [comment]
I wasn't able to get any useful log out of drone (see https://github.com/owncloud/ocis/pull/10678) up to now. And the issue is also not reproducible outside the CI.

I am unassigning myself for now. Since there are higher prio issues to work on :man_shrugging:

**Comment by amrita-shrestha** [comment]
# [Nightly-7-0] Nightly failure on changing quota tests 
## Describe
Build - https://drone.owncloud.com/owncloud/ocis/42165/59/6
https://drone.owncloud.com/owncloud/ocis/42164
Starting from 2024-12-24, getquota tests have been failing during nightly runs. The following scenarios are affected:
```
  Scenario Outline: retrieving folder quota when no quota is set                                      # /drone/src/tests/acceptance/features/coreApiWebdavProperties/getQuota.feature:12
    Given using <dav-path-version> DAV path                                                           # FeatureContext::usingOldOrNewOrSpacesDavPath()
    When user "Admin" changes the quota of the "Alice Hansen" space to "0"                            # SpacesContext::updateSpaceQuota()
    Then the HTTP status code should be "200"                                                         # FeatureContext::thenTheHTTPStatusCodeShouldBe()
    And as user "Alice" folder "/" should contain a property "d:quota-available-bytes" with value "0" # WebDavPropertiesContext::asUserFolderShouldContainAPropertyWithValueOrWithValue()

    Examples:
      | dav-path-version |
      | old              |
        Failed step: Then the HTTP status code should be "200"
        HTTP status code 500 is not the expected value 200
        Failed asserting that 500 matches expected '200'.
      | new              |
        Failed step: Then the HTTP status code should be "200"
        HTTP status code 500 is not the expected value 200
        Failed asserting that 500 matches expected '200'.
      | spaces           |

  @smokeTest
  Scenario Outline: retrieving folder quota when quota is set                                             # /drone/src/tests/acceptance/features/coreApiWebdavProperties/getQuota.feature:24
    Given using <dav-path-version> DAV path                                                               # FeatureContext::usingOldOrNewOrSpacesDavPath()
    When user "Admin" changes the quota of the "Alice Hansen" space to "10000"                            # SpacesContext::updateSpaceQuota()
    Then the HTTP status code should be "200"                                                             # FeatureContext::thenTheHTTPStatusCodeShouldBe()
    And as user "Alice" folder "/" should contain a property "d:quota-available-bytes" with value "10000" # WebDavPropertiesContext::asUserFolderShouldContainAPropertyWithValueOrWithValue()

    Examples:
      | dav-path-version |
      | old              |
        Failed step: Then the HTTP status code should be "200"
        HTTP status code 500 is not the expected value 200
        Failed asserting that 500 matches expected '200'.
      | new              |
      | spaces           |
```

Logs

```
## Scenario Outline: retrieving folder quota when no quota is set (coreApiWebdavProperties/getQuota.feature:19)
		_______________________________________________________________________

		==> REQUEST
		PATCH /graph/v1.0/drives/d086f596-306d-4b6b-9a15-614f8da06e5b$f0e38ca9-efbd-41da-aea7-52494bbbaae7
		X-Request-ID: coreApiWebdavProperties/getQuota.feature:19-14
		==> REQ BODY
		{"quota":{"total":0}}

		<== RESPONSE
		500 Internal Server Error
		X-Xss-Protection: 1; mode=block
		<== RES BODY
		{"error":{"code":"generalException","innererror":{"date":"2024-12-24T03:48:12Z","request-id":"coreApiWebdavProperties/getQuota.feature:19-14"},"message":"grpc error"}}

	### Then the HTTP status code should be "200"
```

## Setup
Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```console
OCIS_XXX=7.0.0
```
</p>
</details>

**Comment by PrajwolAmatya** [comment]
Couldn't reproduce the flakiness locally. It only occurs in CI and also doesn't generate any useful logs in CI.
Currently, I'm unassigning myself form this issue.

**Comment by PrajwolAmatya** [comment]
List of recent build fail:
- https://drone.owncloud.com/owncloud/ocis/43448/51/5

**Comment by saw-jan** [comment]
**Interesting find**: The server sends 500 because there are two user drives with the same name (`alice`).

```yaml
{
  "value": [
    {
      "driveAlias": "personal/alice",
      "id": "fe49f560-62f3-41fd-8364-fbcfee25e7af$3af10eab-f43d-42f3-92f0-d6b2d30262c5",
      "lastModifiedDateTime": "2025-02-14T06:40:04.180433623Z",
      "name": "Alice Hansen",
      "owner": {
        "user": {
          "displayName": "",
          "id": "3af10eab-f43d-42f3-92f0-d6b2d30262c5"
        }
      }
    },
    {
      "driveAlias": "personal/alice",
      "id": "fe49f560-62f3-41fd-8364-fbcfee25e7af$c3326e64-7aa8-4d59-88ed-0da631963402",
      "lastModifiedDateTime": "2025-02-14T06:39:05.440059135Z",
      "name": "Alice Hansen",
      "owner": {
        "user": {
          "displayName": "",
          "id": "c3326e64-7aa8-4d59-88ed-0da631963402"
        }
      }
    },
    {
      "driveAlias": "personal/admin",
      "id": "fe49f560-62f3-41fd-8364-fbcfee25e7af$447d3d5b-0919-4496-834a-53427cd8890a",
      "lastModifiedDateTime": "2025-02-14T06:33:46.891064395Z",
      "name": "Admin",
      "owner": {
        "user": {
          "displayName": "",
          "id": "447d3d5b-0919-4496-834a-53427cd8890a"
        }
      }
    }
  ]
}

```

**Comment by saw-jan** [comment]
This is fixable from the test code. We are using the wrong spaceId in the quota update request.
But I don't know if this (showing broken/supposed to be deleted space in the drives list) needs fix from the server side

**Comment by saw-jan** [comment]
>But I don't know if this (showing broken/supposed to be deleted space in the drives list) needs fix from the server side

During the test execution, sometimes the deleted user space is also shown in the `/drives` list and the supposed to be deleted space doesn't have `.mlock` file in the `storage/users/spaces/...` path.
If this is a fixable issue in the server

CC @2403905

**Comment by kobergj** [comment]
@saw-jan do we know why the deletion of the user fails in the first place? I think the only chance we have is to avoid that original issue. I'm not sure how we can recover from a failed user deletion automatically.

**Comment by saw-jan** [comment]
> [@saw-jan](https://github.com/saw-jan) do we know why the deletion of the user fails in the first place? I think the only chance we have is to avoid that original issue. I'm not sure how we can recover from a failed user deletion automatically.

From the logs, I can say that the user deletion was successful - at least the request sent successful response

**Comment by saw-jan** [comment]
```yaml
{
  "value": [
    {
      "driveAlias": "personal/alice",
      "id": "fe49f560-62f3-41fd-8364-fbcfee25e7af$c3326e64-7aa8-4d59-88ed-0da631963402",
      "lastModifiedDateTime": "2025-02-14T06:39:05.440059135Z",
      "name": "Alice Hansen",
      "root": {
        "deleted": {
          "state": "trashed" 👈
        },
        "eTag": "\"ee10f95ca197e98906aad303ac00d5b9\"",
        "id": "fe49f560-62f3-41fd-8364-fbcfee25e7af$c3326e64-7aa8-4d59-88ed-0da631963402",
        "webDavUrl": "https://ocis-server:9200/dav/spaces/fe49f560-62f3-41fd-8364-fbcfee25e7af$c3326e64-7aa8-4d59-88ed-0da631963402"
      },
    },
    {
      "driveAlias": "personal/alice",
      "id": "fe49f560-62f3-41fd-8364-fbcfee25e7af$3af10eab-f43d-42f3-92f0-d6b2d30262c5",
      "lastModifiedDateTime": "2025-02-14T06:40:04.180433623Z",
      "name": "Alice Hansen",
      "root": {
        "eTag": "\"75106885b3161a9c779c714f97d60bc4\"",
        "id": "fe49f560-62f3-41fd-8364-fbcfee25e7af$3af10eab-f43d-42f3-92f0-d6b2d30262c5",
        "webDavUrl": "https://ocis-server:9200/dav/spaces/fe49f560-62f3-41fd-8364-fbcfee25e7af$3af10eab-f43d-42f3-92f0-d6b2d30262c5"
      },
    }
...
  ]
}
```

The old (deleted) account has this property:
```yaml
"deleted": {
  "state": "trashed" 👈
},
```
