### ISSUE TITLE
Shares not persisting across reboot

### ISSUE THREAD

**Issue by mitexleo** [owncloud/ocis#10634]
## Describe the bug
Every time the OwnCloud Infinite Scale server restarts, the shares are gone. The logs indicate a `PermissionDenied` error related to an invalid core access token.

## Steps to reproduce
1. Set up OwnCloud Infinite Scale using the provided Docker Compose file.
2. Create shares within the OwnCloud Infinite Scale instance.
3. Restart the server.
4. Observe that the shares are no longer available.

## Expected behavior
Shares should persist across server restarts.

## Actual behavior
Shares disappear after the server is restarted, and the logs show a `PermissionDenied` error related to an invalid core access token.

## Setup
The server was started using the following Docker Compose configuration:

```yaml
services:
  ocis:
    image: owncloud/ocis:5
    user: 1280:1280
    ports:
      - 9500:9200
    entrypoint:
      - /bin/sh
    command: ["-c", "ocis init || true; ocis server"]
    environment:
      OCIS_URL: https://cloud.example.com
      OCIS_LOG_LEVEL: error
      PROXY_TLS: false
      OCIS_INSECURE: false
      PROXY_ENABLE_BASIC_AUTH: false
      IDM_ADMIN_PASSWORD: "your_admin_password"
      SETTINGS_GRPC_ADDR: 0.0.0.0:9191
      GATEWAY_GRPC_ADDR: 0.0.0.0:9142
      NOTIFICATIONS_SMTP_HOST: "mail.example.com"
      NOTIFICATIONS_SMTP_PORT: "465"
      NOTIFICATIONS_SMTP_SENDER: "contact@example.com"
      NOTIFICATIONS_SMTP_USERNAME: "contact@example.com"
      NOTIFICATIONS_SMTP_PASSWORD: "your_smtp_password"
      NOTIFICATIONS_SMTP_AUTHENTICATION: "LOGIN"
      NOTIFICATIONS_SMTP_INSECURE: "false"
      STORAGE_USERS_DATA_GATEWAY_URL: http://ocis:9200/data
      THUMBNAILS_FILESYSTEMSTORAGE_ROOT: /var/lib/ocis-thumbnails
      STORAGE_USERS_DRIVER: s3ng
      STORAGE_SYSTEM_DRIVER: ocis
      STORAGE_USERS_S3NG_ENDPOINT: "https://s3.eu-central-003.backblazeb2.com"
      STORAGE_USERS_S3NG_REGION: "eu-central-003"
      STORAGE_USERS_S3NG_ACCESS_KEY: "your_access_key"
      STORAGE_USERS_S3NG_SECRET_KEY: "your_secret_key"
      STORAGE_USERS_S3NG_BUCKET: "your_bucket"
    volumes:
      - /root/owncloud/ocis-config:/etc/ocis
      - /root/owncloud/ocis-data:/var/lib/ocis
      - /root/owncloud/thumbnails:/var/lib/ocis-thumbnails
    logging:
      driver: "local"
    restart: always```

Additional Context:

```
_ns=197181 code=PermissionDenied

2024-11-23T20:30:01Z ERR gateway: error calling ListReceivedShares: rpc error: code = PermissionDenied desc = auth: core access token is invalid | service=gateway pkg=rgrpc traceid=3f85afb6f6b3767c165491add3c2ef7d user-agent=grpc-go/1.62.0 from=tcp://172.25.0.2:60430 uri=/cs3.gateway.v1beta1.GatewayAPI/ListReceivedOCMShares start=23/Nov/2024:20:30:01 +0000 end=23/Nov/2024:20:30:01 +0000 time_ns=5411477 code=PermissionDenied

2024-11-23T20:30:01Z ERR failed to list storage spaces | service=ocm pkg=rgrpc traceid=3f85afb6f6b3767c165491add3c2ef7d error=rpc error: code = PermissionDenied desc = gateway: error calling ListReceivedShares: rpc error: code = PermissionDenied desc = auth: core access token is invalid status={"code":15,"message":"error listing spaces","trace":"3f85afb6f6b3767c165491add3c2ef7d"} filters=[{"type":5,"Term":{"Path":"/public/tGKpjCHzqYzkPJy/DCIM/Camera"}},{"type":4,"Term":{"SpaceType":"+mountpoint"}}]

2024-11-23T20:30:01Z ERR rpc error: code = PermissionDenied desc = auth: core access token is invalid | service=sharing pkg=rgrpc traceid=84ed38e71b958cf06d8d180c144065da user-agent=grpc-go/1.62.0

```

**Comment by 2403905** [comment]
@mitexleo What reversive proxy are you using?
I tested locally the `ocis_s3` deployment example and Docker Compose configuration below, both work well.
```yaml
services:
  ocis:
    image: owncloud/ocis:5
    ports:
      - 9200:9200
    entrypoint:
      - /bin/sh
    command: ["-c", "ocis init || true; ocis server"]
    environment:
      OCIS_URL: https://localhost:9200
      PROXY_HTTP_ADDR: 0.0.0.0:9200
      OCIS_LOG_LEVEL: debug
      # PROXY_TLS: false
      OCIS_INSECURE: true
      PROXY_ENABLE_BASIC_AUTH: true
      IDM_ADMIN_PASSWORD: "your_admin_password"
      # SETTINGS_GRPC_ADDR: 0.0.0.0:9191
      # GATEWAY_GRPC_ADDR: 0.0.0.0:9142
      NOTIFICATIONS_SMTP_HOST: "mail.example.com"
      NOTIFICATIONS_SMTP_PORT: "465"
      NOTIFICATIONS_SMTP_SENDER: "contact@example.com"
      NOTIFICATIONS_SMTP_USERNAME: "contact@example.com"
      NOTIFICATIONS_SMTP_PASSWORD: "your_smtp_password"
      NOTIFICATIONS_SMTP_AUTHENTICATION: "LOGIN"
      NOTIFICATIONS_SMTP_INSECURE: "false"
      # STORAGE_USERS_DATA_GATEWAY_URL: http://ocis:9200/data
      THUMBNAILS_FILESYSTEMSTORAGE_ROOT: /var/lib/ocis-thumbnails
      STORAGE_USERS_DRIVER: s3ng
      STORAGE_SYSTEM_DRIVER: ocis
            # s3ng specific settings
      STORAGE_USERS_S3NG_ENDPOINT: ${S3NG_ENDPOINT:-http://minio:9000}
      STORAGE_USERS_S3NG_REGION: ${S3NG_REGION:-default}
      STORAGE_USERS_S3NG_ACCESS_KEY: ${S3NG_ACCESS_KEY:-ocis}
      STORAGE_USERS_S3NG_SECRET_KEY: ${S3NG_SECRET_KEY:-ocis-secret-key}
      STORAGE_USERS_S3NG_BUCKET: ${S3NG_BUCKET:-your_bucket}
      # STORAGE_USERS_S3NG_ENDPOINT: "https://s3.eu-central-003.backblazeb2.com"
      # STORAGE_USERS_S3NG_REGION: "eu-central-003"
      # STORAGE_USERS_S3NG_ACCESS_KEY: "your_access_key"
      # STORAGE_USERS_S3NG_SECRET_KEY: "your_secret_key"
      # STORAGE_USERS_S3NG_BUCKET: "your_bucket"
    volumes:
      - ./ocis-config:/etc/ocis
      - ./ocis-data:/var/lib/ocis
      - ./thumbnails:/var/lib/ocis-thumbnails
    logging:
      driver: "local"
    restart: always

  minio:
    image: minio/minio:latest
    entrypoint:
      - /bin/sh
    command:
      [
        "-c",
        "mkdir -p /data/${S3NG_BUCKET:-your_bucket} && minio server --console-address ':9001' /data",
      ]
    volumes:
      - minio-data-1:/data
    environment:
      MINIO_ACCESS_KEY: ${S3NG_ACCESS_KEY:-ocis}
      MINIO_SECRET_KEY: ${S3NG_SECRET_KEY:-ocis-secret-key}
    logging:
      driver: ${LOG_DRIVER:-local}
    restart: always

volumes:
  minio-data-1:
```
