### ISSUE TITLE
oCIS on Raspberry: Blank Login Page

### ISSUE THREAD

**Issue by dragotin** [owncloud/ocis#1085]
On a fresh install of Raspberry Pi OS Lite I installed oCIS RC7 and started the single binary like this:
```
OCIS_LOG_LEVEL=debug  ./ocis-1.0.0-rc7-linux-arm server
```
It starts fine (no visible errors in log), but when I try to connect to the url `https://ip-of-the-raspi:9200` a blank page is returning with the following source:

```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
	<meta name="theme-color" content="#375f7E"/>
	<meta http-equiv="x-ua-compatible" content="IE=11">
	<link rel="manifest" href="manifest.json">
	<script src="node_modules/requirejs/require.js"></script>
	<noscript>
		<style>
			#enable-js-banner {
				display: flex;
				flex-direction: row;
				justify-content: center;
				padding: 0.5rem;
				background-color: #467391;
			}

			#banner-content{
				color: white;
			}
		</style>
	</noscript>
<link href="css/core.css" rel="stylesheet"></head>
<body>
	<main id="owncloud"></main>
	<noscript>
		<div id="enable-js-banner">
			<span id="banner-content"><h3>Please enable JavaScript</h3></span>
		</div>
	</noscript>
<script type="text/javascript" src="core/core.bundle.js"></script></body>
</html>
```
The browser gives the following output in the debug konsole:

![ksnip_20201213-124341](https://user-images.githubusercontent.com/1070214/102011388-fbb55400-3d43-11eb-98fa-b11f56f31c51.png)

**Comment by butonic** [comment]
did you get it working?

**Comment by refs** [comment]
Closing, as he got it working

**Comment by mpolinowski** [comment]
Hi @refs ,

do you know what the solution was? I am seeing the same error running the latest Docker image from today:

```bash
docker pull owncloud/ocis
docker run --rm -ti -p 9200:9200 owncloud/ocis
```

I opened up port 9200/tcp but started seeing an error message for port 53154 and other in this high range (192.168.2.112 is the computer I am accessing from):

```bash
2021-01-20 06:26:19.118266 I | http: TLS handshake error from 192.168.2.112:53154: remote error: tls: unknown certificate
...
2021-01-20 06:43:36.094455 I | http: TLS handshake error from 192.168.2.112:53733: remote error: tls: unknown certificate
...
2021-01-20 06:45:50.100597 I | http: TLS handshake error from 192.168.2.112:53923: remote error: tls: unknown certificate
```

Do I have to open any of those ports?


I end up with a white login screen and a couple of network errors:


```html
curl https://localhost:9200 --insecure

<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="UTF-8">
        <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
        <meta name="theme-color" content="#375f7E"/>
        <meta http-equiv="x-ua-compatible" content="IE=11">
        <link rel="manifest" href="manifest.json">
        <script src="node_modules/requirejs/require.js"></script>
        <noscript>
                <style>
                        #enable-js-banner {
                                display: flex;
                                flex-direction: row;
                                justify-content: center;
                                padding: 0.5rem;
                                background-color: #467391;
                        }

                        #banner-content{
                                color: white;
                        }
                </style>
        </noscript>
<link href="css/core.css" rel="stylesheet"></head>
<body>
        <main id="owncloud"></main>
        <noscript>
                <div id="enable-js-banner">
                        <span id="banner-content"><h3>Please enable JavaScript</h3></span>
                </div>
        </noscript>
<script type="text/javascript" src="core/core.bundle.js"></script></body>
</html>
```

![chrome](https://user-images.githubusercontent.com/18694428/105140885-4db37b80-5b33-11eb-8b9d-a3475f38e213.png)


It is interesting `/.well-known/openid-configuration` gets me an ERR_CONNECTION_REFUSED. But `/accounts.js` and `/settings.js` can be reached:


```bash
{"level":"info","service":"proxy","from":"192.168.2.112:53641","method":"GET","path":"/settings.js","time":"2021-01-20T06:42:48.10877392Z","message":"access-log"}
{"level":"info","service":"proxy","from":"192.168.2.112:53643","method":"GET","path":"/accounts.js","time":"2021-01-20T06:42:48.143669302Z","message":"access-log"}
```

**Comment by lastb0isct** [comment]
I'm also getting this error when running the docker image on a non-localhost docker host.  Connecting to the https://dockerhostip:9200 redirects to the full https://dockerhostip:9200/#/login but nothing is displayed and get the unknown certificate error

**Comment by kennyparsons** [comment]
> I'm also getting this error when running the docker image on a non-localhost docker host. Connecting to the https://dockerhostip:9200 redirects to the full https://dockerhostip:9200/#/login but nothing is displayed and get the unknown certificate error

Same here. Any documented fix?

**Comment by yg382** [comment]
Same here as well with the same issue in Kubernetes/OpenShift. Any solution so far?

**Comment by refs** [comment]
Follow in #1354

**Comment by refs** [comment]
@yg382 @kennyparsons @lastb0isct This is my setup with a remote docker host:

- docker host running on `136.244.93.194`
- ssh and `docker run --env-file="env" --rm -ti -p 9200:9200 owncloud/ocis`

The contents of `env` are

```
PROXY_HTTP_ADDR=0.0.0.0:9200
OCIS_URL=https://136.244.93.194:9200
KONNECTD_TLS=0
OCIS_LOG_PRETTY=true
```

The critical line is `OCIS_URL`. When present, it configures the identity provider on that URL. You can see the contents we generate for the idp here with `docker exec -ti container_name less config/identifier-registration.yaml`

```yaml
---

# OpenID Connect client registry.
clients:
  - id: web
    name: ownCloud web app
    trusted: yes
    insecure: yes
    redirect_uris:
      - https://136.244.93.194:9200/
      - https://136.244.93.194:9200/oidc-callback.html
      - https://136.244.93.194:9200/oidc-silent-redirect.html
    origins:
      - https://136.244.93.194:9200

  - id: ocis-explorer.js
    name: oCIS Graph Explorer
    trusted: yes
    insecure: yes

  - id: xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69
    secret: UBntmLjC2yYCeHwsyj73Uwo9TAaecAetRwMw0xYcvNL9yRdLSUi0hUAHfvCHFeFh
    name: ownCloud desktop app
    application_type: native
    insecure: true

  - id: e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD
    secret: dInFYGV33xKzhbRmpqQltYNdfLdJIfJ9L5ISoKhNoT9qZftpdWSP71VrpGR9pmoD
    name: ownCloud Android app
    application_type: native
    redirect_uris:
      - oc://android.owncloud.com

  - id: mxd5OQDk6es5LzOzRvidJNfXLUZS2oN3oUFeXPP8LpPrhx3UroJFduGEYIBOxkY1
    secret: KFeFWWEZO9TkisIQzR3fo7hfiMXlOpaqP8CFuTbSHzV1TUuGECglPxpiVKJfOXIx
    name: ownCloud iOS app
    application_type: native
    redirect_uris:
      - oc://ios.owncloud.com
      - oc.ios://ios.owncloud.com
[...]
```

and inspecting the arrays `redirect_uris` and `origins`. In my case I'm accessing the host using its IP, but had I have a domain name, then I would change the `OCIS_URL` value to that name. Could you give that a try?

**Comment by yg382** [comment]
I tried with OCIS_URL and it worked out but unfortunately, access is denied when trying to login using different demo accounts. 

![image](https://user-images.githubusercontent.com/44134731/106476614-ae8e6c80-64c0-11eb-8e03-b7287806a539.png)

**Comment by kulmann** [comment]
> I tried with OCIS_URL and it can see the login page but unfortunately, access is denied when trying to login using different demo accounts.
> 
> ![image](https://user-images.githubusercontent.com/44134731/106476614-ae8e6c80-64c0-11eb-8e03-b7287806a539.png)

@yg382 Do you have a valid SSL certificate for your domain? If you don't have one (which would be fine) then we'll need to take care of setting some env vars for your instance (anything `INSECURE` related needs to be `true`).

**Comment by refs** [comment]
It could as well be that a service failed to start, hard to say without the server logs :/

**Comment by yg382** [comment]
I have disabled the tls so far using PROXY_TLS=false and I don't see any remote error: tls: unknown certificate. I still can see the same context deadline exceeded issue during the login.

logs:

2021-02-01 17:19:00  file=v2@v2.9.1/service.go:200 level=info Starting [service] com.owncloud.api.accounts
2021-02-01 17:19:00  file=grpc/grpc.go:864 level=info Server [grpc] Listening on [::]:9180
2021-02-01T17:19:00Z INF successfully added permission to bundle bundle=d7beeea8-8ff4-406b-8fb6-ab2dd81e6b11 service=accounts setting=e03070e9-4362-4cc6-a872-1c7cb2eb2b8e
2021-02-01 17:19:00  file=grpc/grpc.go:697 level=info Registry [mdns] Registering node: com.owncloud.api.accounts-a4b8c286-2a8e-4b7c-b078-08e7b4e294f9
2021-02-01T17:19:39Z INF access-log from=10.128.4.1:33118 method=GET path=/signin/v1/identifier/_/authorize service=proxy
2021-02-01T17:19:41Z INF access-log from=10.128.4.1:33144 method=GET path=/settings.js service=proxy
2021-02-01T17:19:41Z INF access-log from=10.128.4.1:33144 method=GET path=/accounts.js service=proxy
2021-02-01T17:19:41Z INF access-log from=10.128.4.1:33118 method=GET path=/.well-known/openid-configuration service=proxy
2021-02-01T17:19:41Z INF access-log from=10.128.4.1:33118 method=GET path=/signin/v1/identifier/_/authorize service=proxy
2021-02-01T17:19:41Z INF access-log from=10.128.4.1:33118 method=GET path=/signin/v1/identifier service=proxy
2021-02-01T17:19:42Z INF access-log from=10.128.4.1:33118 method=GET path=/signin/v1/static/css/main.ff4176e2.chunk.css service=proxy
2021-02-01T17:19:42Z INF access-log from=10.128.4.1:33178 method=GET path=/signin/v1/static/js/runtime-main.6429ebf0.js service=proxy
2021-02-01T17:19:42Z INF access-log from=10.128.4.1:33118 method=GET path=/signin/v1/static/js/main.319f99c0.chunk.js service=proxy
2021-02-01T17:19:42Z INF access-log from=10.128.4.1:33178 method=GET path=/signin/v1/static/media/background.d469fc8c.jpg service=proxy
2021-02-01T17:19:42Z INF access-log from=10.128.4.1:33118 method=GET path=/signin/v1/static/js/9.a3e68dee.chunk.js service=proxy
2021-02-01T17:19:42Z INF access-log from=10.128.4.1:33178 method=GET path=/signin/v1/static/js/identifier-app.dc3ded3f.chunk.js service=proxy
2021-02-01T17:19:42Z INF access-log from=10.128.4.1:33118 method=GET path=/signin/v1/static/js/8.15de8a91.chunk.js service=proxy
2021-02-01T17:19:42Z INF access-log from=10.128.4.1:33178 method=GET path=/signin/v1/static/js/identifier-main.87e8e905.chunk.js service=proxy
2021-02-01T17:19:42Z INF access-log from=10.128.4.1:33178 method=GET path=/signin/v1/static/js/10.eee7136a.chunk.js service=proxy
2021-02-01T17:19:42Z INF access-log from=10.128.4.1:33118 method=GET path=/signin/v1/static/js/0.ce7dce23.chunk.js service=proxy
2021-02-01T17:19:42Z INF access-log from=10.128.4.1:33192 method=GET path=/signin/v1/static/js/containers-login.35b164c4.chunk.js service=proxy
2021-02-01T17:19:42Z INF access-log from=10.128.4.1:33118 method=GET path=/signin/v1/static/logo.svg service=proxy
2021-02-01T17:19:42Z INF access-log from=10.128.4.1:33192 method=POST path=/signin/v1/identifier/_/hello service=proxy
2021-02-01T17:19:42Z INF access-log from=10.128.4.1:33118 method=GET path=/signin/v1/static/favicon.ico service=proxy
2021-02-01T17:19:51Z ERR could not initialize oidcAuth provider error="Get \"https://ocis.int.consol.ae/.well-known/openid-configuration\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" service=proxy
2021-02-01T17:19:51Z INF access-log from=10.128.4.1:33118 method=POST path=/signin/v1/identifier/_/logon service=proxy
2021-02-01T17:19:52Z INF access-log from=10.128.4.1:33118 method=GET path=/signin/v1/identifier/_/authorize service=proxy
2021-02-01T17:19:54Z INF access-log from=10.128.4.1:33178 method=GET path=/settings.js service=proxy
2021-02-01T17:19:54Z INF access-log from=10.128.4.1:33178 method=GET path=/accounts.js service=proxy
2021-02-01T17:19:54Z INF access-log from=10.128.4.1:33118 method=GET path=/.well-known/openid-configuration service=proxy
2021-02-01T17:19:54Z INF access-log from=10.128.4.1:33118 method=POST path=/konnect/v1/token service=proxy
2021-02-01T17:19:54Z INF access-log from=10.128.4.1:33118 method=GET path=/konnect/v1/userinfo service=proxy
2021-02-01T17:20:04Z ERR could not initialize oidcAuth provider error="Get \"https://ocis.int.consol.ae/.well-known/openid-configuration\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" service=proxy
2021-02-01T17:20:14Z ERR could not initialize oidcAuth provider error="Get \"https://ocis.int.consol.ae/.well-known/openid-configuration\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" service=proxy

**Comment by mpolinowski** [comment]
Ok - I tried this as well.

1. Created the environment file `.env`:

```
PROXY_HTTP_ADDR=0.0.0.0:9200
OCIS_URL=https://192.168.2.111:9200
OCIS_LOG_PRETTY=true
PROXY_TLS=false
```

2. Started the docker container with the env variables:

```
docker run --env-file=".env" --rm -ti -p 9200:9200 owncloud/ocis
```

see [start-up log](https://gist.github.com/mpolinowski/98f6d18bf84b5dd83594eb8779166539)

3. Checked if the variables were used by the container:

```
docker exec -ti container_name less config/identifier-registration.yaml
```

```
# OpenID Connect client registry.
clients:
  - id: web
    name: ownCloud web app
    trusted: yes
    insecure: yes
    redirect_uris:
      - https://192.168.2.111:9200/
      - https://192.168.2.111:9200/oidc-callback.html
      - https://192.168.2.111:9200/oidc-silent-redirect.html
    origins:
      - https://192.168.2.111:9200

  - id: ocis-explorer.js
    name: oCIS Graph Explorer
    trusted: yes
    insecure: yes

  - id: xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69
    secret: UBntmLjC2yYCeHwsyj73Uwo9TAaecAetRwMw0xYcvNL9yRdLSUi0hUAHfvCHFeFh
    name: ownCloud desktop app
    application_type: native
    insecure: true

  - id: e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD
    secret: dInFYGV33xKzhbRmpqQltYNdfLdJIfJ9L5ISoKhNoT9qZftpdWSP71VrpGR9pmoD
    name: ownCloud Android app
    application_type: native
    redirect_uris:
      - oc://android.owncloud.com

  - id: mxd5OQDk6es5LzOzRvidJNfXLUZS2oN3oUFeXPP8LpPrhx3UroJFduGEYIBOxkY1
    secret: KFeFWWEZO9TkisIQzR3fo7hfiMXlOpaqP8CFuTbSHzV1TUuGECglPxpiVKJfOXIx
    name: ownCloud iOS app
    application_type: native
    redirect_uris:
      - oc://ios.owncloud.com
      - oc.ios://ios.owncloud.com
```

4. Deactivated the firewall to make sure everything is open:

```
ufw disable
```


And I am still getting SSL_PROTOCOL_ERRORs and 404s:


![ocis](https://user-images.githubusercontent.com/18694428/106561493-be12c180-6563-11eb-825c-7b0d5d47a69c.png)
