### ISSUE TITLE
Delete user containing `+` in username returns 404 but user gets deleted

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#11027]
## Steps to reproduce
1. Create a new user containing +: `user+plus`
2. Try to delete the created user - `404` ❗ 
```bash
curl -XDELETE "https://localhost:9200/graph/v1.0/users/user+plus' -u admin:admin -vk
```
```yaml
< HTTP/1.1 404 Not Found

{
  "error": {
    "code": "itemNotFound",
    "innererror": {"date":"2025-02-18T11:58:19Z","request-id":"..."},
    "message": ""
  }
}
```
3. List user - user gets deleted ❗ 
```bash
curl 'https://localhost:9200/graph/v1.0/users' -uadmin:admin -vk | jq
```

## Expected behavior
204

## Actual behavior
404 Not Found
but user gets deleted
