### ISSUE TITLE
OnlyOffice JWT Secret

### ISSUE THREAD

**Issue by zerodarkzone** [owncloud/ocis#11325]
Hi,

I'm using the ocis_full deployment example to desploy oCIS with OnlyOffice integration and it is working right now. However I have a question.

From the compose files, it looks like even if the JWT secret is enabled in OnlyOffice oCIS is connecting to it without providing the secret value. How does this work? is OnlyOffice actually left open and any client can connect to it? it looks like a security concern if I want to expose my ocis instance to the internet.

Both on Owncloud server 10 and Nextcloud you must provide the JWT Secret to connect to onlyoffice but here it looks like it is not needed.

**Comment by jvillafanez** [comment]
> oCIS is connecting to it without providing the secret value.

This is wrong. It's the other way around. OnlyOffice is connecting to oCIS.

oCIS generates a token, which happens to be a JWT token. Then it tells OnlyOffice to open a specific oCIS url (pointing to oCIS) with the generated token as access token. Basically, oCIS tells OnlyOffice to "open this document with this token"


> is OnlyOffice actually left open and any client can connect to it? it looks like a security concern if I want to expose my ocis instance to the internet.

I haven't tested security options, but there are a couple of things you can try:
* In order to ensure that only oCIS can access to OnlyOffice, you can setup ip filters in OnlyOffice (https://helpcenter.onlyoffice.com/docs/installation/docs-configure-ipfilter.aspx). I haven't tested this, but I assume it works as they say.
* In order to verify oCIS documents are only accessible from a trusted source (OnlyOffice in this case), oCIS uses proof key verification. This is enabled by default, although you can disable it if there are problems.

Using both should prevent unwanted access to each piece.

-----

https://api.onlyoffice.com/docs/docs-api/using-wopi/api-vs-wopi/ might also help to understand. oCIS is using WOPI integration

**Comment by zerodarkzone** [comment]
Hi,

I understand now. The secret only works when using the API but when using the wopi server it is left completely open to any request.

![Image](https://github.com/user-attachments/assets/d75f30ca-b039-4398-b399-d5d73b0471c9)

Even if it is not a security concern it would allow anyone to use the onlyoffice server if it is exposed to the internet. I'll try to test the ip filter configuration which I think can also be used with a domain. It would be nice if you added this configuration to the _local.json_ file inside the _full_ocis_ example deployment.

> * In order to verify oCIS documents are only accessible from a trusted source (OnlyOffice in this case), oCIS uses proof key verification. This is enabled by default, although you can disable it if there are problems.
> 

From what I understand this is done with this option right? `COLLABORATION_APP_PROOF_DISABLE`

It is disabled by default on the example deployment. Maybe you could leave it enabled with some kind of note?

```
 collaboration-oo:
    image: ${OCIS_DOCKER_IMAGE:-owncloud/ocis}:${OCIS_DOCKER_TAG:-latest}
    networks:
      ocis-net:
    depends_on:
      ocis:
        condition: service_started
      onlyoffice:
        condition: service_healthy
    entrypoint:
      - /bin/sh
    command: [ "-c", "ocis collaboration server" ]
    environment:
      COLLABORATION_GRPC_ADDR: 0.0.0.0:9301
      COLLABORATION_HTTP_ADDR: 0.0.0.0:9300
      MICRO_REGISTRY: "nats-js-kv"
      MICRO_REGISTRY_ADDRESS: "ocis:9233"
      COLLABORATION_WOPI_SRC: https://${WOPISERVER_ONLYOFFICE_DOMAIN:-wopiserver-oo.owncloud.test}
      COLLABORATION_APP_NAME: "OnlyOffice"
      COLLABORATION_APP_PRODUCT: "OnlyOffice"
      COLLABORATION_APP_ADDR: https://${ONLYOFFICE_DOMAIN:-onlyoffice.owncloud.test}
      COLLABORATION_APP_ICON: https://${ONLYOFFICE_DOMAIN:-onlyoffice.owncloud.test}/web-apps/apps/documenteditor/main/resources/img/favicon.ico
      COLLABORATION_APP_INSECURE: "${INSECURE:-true}"
      COLLABORATION_CS3API_DATAGATEWAY_INSECURE: "${INSECURE:-true}"
      COLLABORATION_LOG_LEVEL: ${LOG_LEVEL:-info}
      COLLABORATION_APP_PROOF_DISABLE: "true"
      OCIS_URL: https://${OCIS_DOMAIN:-ocis.owncloud.test}
    volumes:
      # configure the .env file to use own paths instead of docker internal volumes
      - ${OCIS_CONFIG_DIR:-ocis-config}:/etc/ocis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collaboration-oo.entrypoints=https"
      - "traefik.http.routers.collaboration-oo.rule=Host(`${WOPISERVER_ONLYOFFICE_DOMAIN:-wopiserver-oo.owncloud.test}`)"
      - "traefik.http.routers.collaboration-oo.tls.certresolver=http"
      - "traefik.http.routers.collaboration-oo.service=collaboration-oo"
      - "traefik.http.services.collaboration-oo.loadbalancer.server.port=9300"
    logging:
      driver: ${LOG_DRIVER:-local}
    restart: always
```

Thank you
