### ISSUE TITLE
Cannot read picture on web browser / Thumbnails missing

### ISSUE THREAD

**Issue by Fred-06** [owncloud/ocis#11355]
Hi,

I set about configuring oCIS via Docker Compose with Pangolin as the reverse proxy and Pocket-ID as the OIDC provider.

Web access works fine and I can upload my files. However, I can't read images and the thumbnails aren't displayed.

Here is my Docker Compose : 
```

services:
  ocis:
    image: owncloud/ocis:latest
    user: 1000:1000
    container_name: owncloud-ocis
    hostname: owncloud-ocis
    restart: unless-stopped
    entrypoint:
      - /bin/sh
    # run ocis init to initialize a configuration file with random secrets
    # it will fail on subsequent runs, because the config file already exists
    # therefore we ignore the error and then start the ocis server
    command: ["-c", "ocis init || true; ocis server"]
    environment:

      #- OCIS_LOG_FILE=/var/log/ocis/ocis.log

      #OIDC
      - OCIS_URL=https://ocis.domain.com # adjust to your FQDN domain; https required
      - OCIS_OIDC_ISSUER=https://pid.domain.com 
      - OCIS_OIDC_CLIENT_ID=ocis.domain.com 
      - OCIS_EXCLUDE_RUN_SERVICES=idp
      - OCIS_INSECURE=true # required if you use a reverse proxy with SSL support in front
      - OCIS_ADMIN_USER_ID=admin
      - OCIS_LOG_LEVEL=debug
      - OCIS_LOG_COLOR=true
      - OCIS_LOG_PRETTY=true
      - OCIS_JWT_SECRET=*********************************
      - OCIS_BASE_DATA_PATH=/var/lib/ocis/thumbnails
      - WEB_OIDC_CLIENT_ID=6*************************
      - WEB_OIDC_SCOPE=openid profile email groups
      - WEB_OIDC_METADATA_URL=https://pid.domain.com /.well-known/openid-configuration
      - WEB_OIDC_AUTHORITY=https://pid.domain.com 
      - PROXY_TLS=true # disable if you use a reverse proxy with SSL support in front
      - PROXY_AUTOPROVISION_ACCOUNTS=true
      - PROXY_ROLE_ASSIGNMENT_DRIVER=oidc
      - PROXY_OIDC_ISSUER=https://pid.domain.com 
      - PROXY_OIDC_REWRITE_WELLKNOWN=true
      - PROXY_USER_OIDC_CLAIM=email
      - PROXY_USER_CS3_CLAIM=mail
      - PROXY_CSP_CONFIG_FILE_LOCATION=/etc/ocis/csp.yaml
      - PROXY_OIDC_ACCESS_TOKEN_VERIFY_METHOD=jwt
      #- PROXY_OIDC_SKIP_USER_INFO=false
      - PROXY_AUTOPROVISION_CLAIM_EMAIL=email
      #- PROXY_ENABLE_BASIC_AUTH=false
      - DEMO_USERS=false
      - NATS_HOST=127.0.0.1
      - NATS_PORT=9233
      - NATS_ENABLE_TLS=false
      - THUMBNAILS_FILESYSTEMSTORAGE_ROOT=/var/lib/ocis/thumbnails
    volumes:
      - /srv/dev-disk-by-uuid-c5367cf6-9435-4031-8ea1-c0fe415b9ccd/DOCKER-DATA/portainer/ocis-home/ocis-config:/etc/ocis
      - /srv/dev-disk-by-uuid-c5367cf6-9435-4031-8ea1-c0fe415b9ccd/DOCKER-DATA/portainer/ocis-home/ocis-data:/var/lib/ocis
      - /srv/dev-disk-by-uuid-c5367cf6-9435-4031-8ea1-c0fe415b9ccd/DOCKER-DATA/portainer/ocis-home/ocis-thumbnails:/var/lib/ocis/thumbnails

    ports:
      - 9200:9200
```
According to the documentation, I created the thumbnails.yaml file in ./config where ocis.yaml is also located, but I'm not sure how to interpret it correctly.

I can see this error log : 
`
owncloud-ocis  | 2025-05-23T13:17:07Z DBG could not get thumbnail error="{\"id\":\"com.owncloud.api.thumbnails\",\"code\":500,\"detail\":\"could not get image\",\"status\":\"Internal Server Error\"}" line=github.com/owncloud/ocis/v2/services/webdav/pkg/service/v0/service.go:273 request-id= service=webdav`

Thanks for your help!
