### ISSUE TITLE
Remove Feedback button does not work

### ISSUE THREAD

**Issue by conserve-cgn** [owncloud/ocis#11417]
It was possible in the past to disable the feedback button in the ocis.yaml with "disableFeedbackLink: true".
But on the actual version 7.1.3 this setting does not work and show the feedback button again.

How it is possible to disable the feedback button?

Kind regards

**Comment by LukasHirt** [comment]
I just tested this with the `v7.1.3` tag and it worked for me. How does your config file look like? This is what worked for me:

```yaml
web:
  web:
    config:
      options:
        disableFeedbackLink: true
```

**Comment by conserve-cgn** [comment]
I had tried with:
```
web:  
  config:
    options:
      disableFeedbackLink: true
```


I just tried your config with v7.1.3, and it works on my site too now. Many thanks.
```
web:
  web:
    config:
      options:
        disableFeedbackLink: true
```
