### ISSUE TITLE
Blank page after fresh install on raspberry pi

### ISSUE THREAD

**Issue by Rilnaista** [owncloud/ocis#1354]
I had just made a clean install on a clean raspberry pi (2021-01-11-raspios-buster-armhf-lite) full updated / upgraded via 

`curl https://download.owncloud.com/ocis/ocis/1.0.0/ocis-1.0.0-linux-arm --output ocis`

After that I started the service via

`-/ocis server`

I stopped the service via STRG+C and edited the generated config/identifier-registration.yaml like descibed at [https://owncloud.github.io/ocis/deployment/basic-remote-setup/](https://owncloud.github.io/ocis/deployment/basic-remote-setup/) to access this owncloud from my PC.

```yaml
clients:
  - id: web
  name: ownCloud web app
  trusted: yes
  insecure: yes
  redirect_uris:
    - https://localhost:9200/
    - https://localhost:9200/oidc-callback.html
    - https://localhost:9200/oidc-silent-redirect.html
    - http://localhost:9100/
    - http://localhost:9100/oidc-callback.html
    - http://localhost:9100/oidc-silent-redirect.html
    - https://owncloud:9200/
    - https://owncloud:9200/oidc-callback.html
    - https://owncloud:9200/oidc-silent-redirect.html
  origins:
    - https://localhost:9200
    - http://localhost:9100
    - https://owncloud:9200
```

After editing the yml file I started the server with the following command:

`PROXY_HTTP_ADDR=0.0.0.0:9200 \
OCIS_URL=https://owncloud:9200 \
PROXY_TRANSPORT_TLS_KEY=./certs/your-host.key \
PROXY_TRANSPORT_TLS_CERT=./certs/your-host.crt \
KONNECTD_TLS=0 \
./ocis server`

I cleared the cache in my browser and typed in the hostname and got a blank screen. I took a look in the console and saw that owncloud tried to load an js-Library from localhost.

`2core.bundle.js:18 UserManager.getUser: user not found in storage
core.bundle.js:18 JsonService.getJson: network error
t.error @ core.bundle.js:18
localhost:9200/.well-known/openid-configuration:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
core.bundle.js:18 Uncaught (in promise) Error: Network Error
    at XMLHttpRequest.s.onerror (core.bundle.js:18)`

I followed all described steps to access own cloud via remote. It didn't work as expected / described. Don't know it there is an bug in the documentation or software.

Hope I provided all needed information to reproduce this error.
