### ISSUE TITLE
please provide us with a working and complete YML file (to deploy OCIS+owncloud 10)

### ISSUE THREAD

**Issue by jboesh** [owncloud/ocis#1396]
## Is your feature request related to a problem? Please describe.
I would like to try out the new OCIS but I find the example that is given not very clear and also not complete (looks like it). I'm talking about this example:
https://github.com/owncloud/ocis/tree/master/deployments/examples/ocis_traefik

isn't this just the backend image? it would be nice if the frontend (owncloud 10) is also added in the example. Also a redis image (if possible) and for instance Onlyoffice and a database image. So that it is complete and quickly usable for those who want to deploy it.
I would otherwise spend a lot of time looking up those parts (redis, onlyoffice, database ...) to add in the file to deploy... 

## Describe the solution you'd like
A complete example (YML file), in which OCIS (as backend?), Owncloud 10 (as frontend?) with a database image, redis and onlyoffice is embedded. this allows people like me to use owncloud easily and quickly.

I also use docker swarm, it would be like to include an example for this kind of deployment too.

## Describe alternatives you've considered
I already have some knowledge of docker (compose) and swarm, but I am NOT getting the existing example working.

## Additional context
I'm willing to test a few things, if you have any suggestions please let me know

**Comment by wkloucek** [comment]
Thank you for your interest in oCIS!

The oCIS with Traefik example starts the oCIS backend and also serves the web frontend, wich you can then use in your browser.
A database or redis is not needed for oCIS.  So this example is indeed complete. Onlyoffice is not yet available for the use with oCIS.

Did you also have a look at the associated documentation at https://owncloud.github.io/ocis/deployment/ocis_traefik/, especially the part about the `.env file? Do you have any explicit error messages or what stops you to get it working?

If you want to deploy it with swarm, give this a try: https://docs.docker.com/engine/swarm/stack-deploy/.

**Comment by jboesh** [comment]
thanks for your reply and clarification, Ived tried the traefik example from this location:
https://github.com/owncloud/ocis/blob/master/deployments/examples/ocis_traefik/docker-compose.yml

the application is running in docker, but nothing happens in traefik. I cant get to the frontpage...
Also nothing happens when I try to add this lines:
    ports:
      - 9200:9200

this is my config, do you see any suggestions?

```
version: "3.7"
services:
  ocis:
    image: owncloud/ocis:latest
    networks:
      - internal
      - traefik_public
    environment:
      - OCIS_URL=https://ocis.mydomain.com
      - OCIS_LOG_LEVEL=warn
      - PROXY_OIDC_INSECURE=true
      - OCIS_DOMAIN=https://ocis.mydomain.com
    ports:
      - 9200:9200
    volumes:
      - /share/docker/swarm/appdata/ocis:/var/tmp/ocis
    deploy:
      labels:
        - "traefik.enable=true"
        # Entry point for http
        - "traefik.http.routers.ocis.entrypoints=http"
        - "traefik.http.routers.ocis.rule=Host(`ocis.mydomain.com`)"
        - "traefik.http.routers.ocis.service=ocis"
        - "traefik.http.services.ocis.loadbalancer.server.scheme=https"
        # Entry Point for https
        - "traefik.http.routers.ocis-secure.middlewares=secure-headers@file"
        - "traefik.http.routers.ocis-secure.entrypoints=https"
        - "traefik.http.routers.ocis-secure.rule=Host(`ocis.mydomain.com`)"
        - "traefik.http.routers.ocis-secure.service=ocis"
        - "traefik.http.services.ocis-secure.loadbalancer.server.port=9200"

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.87.0/24
```

**Comment by wkloucek** [comment]
If you want to try it with the port exposed you can leave out all the Traefik related stuff and end up with a pretty small docker-compose definition. Please also note the `OCIS_URL` which I have set up to use your IP. This will allow you to open https://192.168.1.145:9200 in your browser.
```
---
version: "3.7"

services: 
 ocis:
    image: owncloud/ocis:latest
    ports:
      - 9200:9200
    environment:
      OCIS_URL: https://192.168.1.145:9200
      OCIS_LOG_LEVEL: "error"
      PROXY_OIDC_INSECURE: "true"
    volumes:
      - ocis-data:/var/tmp/ocis

volumes:
  ocis-data:
```

Regarding your Traefik configuration:
- I don't know your full Traefik configuration but if you have insecureSkipVerify (https://github.com/owncloud/ocis/blob/1c83fa033aeded9a8a3d9046aecf7a63b4229195/deployments/examples/ocis_traefik/docker-compose.yml#L21) not activated, you need to disable SSL termination on oCIS by setting `PROXY_TLS=false`. Then you also have to set `traefik.http.services.ocis.loadbalancer.server.scheme=https` to `traefik.http.services.ocis.loadbalancer.server.scheme=http`.
- Since Traefik has a trusted SSL certificate in your case you can set `PROXY_OIDC_INSECURE=false`
- Please also check the Traefik log and Traefik dashboard for errors
