### ISSUE TITLE
Can login with invalid password while logging in with openidconnect in oc10

### ISSUE THREAD

**Issue by dpakach** [owncloud/ocis#1428]
### Steps to reproduce
1. Setup openidconnect setup in oc10 using this guid
https://owncloud.github.io/ocis/bridge/
2. create a user in oc10
3. Go to login page from ocis-phoenix and authenticate
4. Try to login to openidconnect page with correct userid and invalid password

### Expected Result
1. The user is not logged in and a error message is shown

### Actual Result
1. The user is logged in successfully and redirected to the files page.

### Configuration used
```
#!/bin/bash
GLAUTH_BACKEND_SERVERS=http://localhost/core GLAUTH_BACKEND_BASEDN="dc=example,dc=com" GLAUTH_BACKEND_DATASTORE=owncloud ../ocis-glauth/bin/ocis-glauth --log-level debug server &

PHOENIX_ASSET_PATH="$HOME/www/dist" ../ocis-phoenix/bin/ocis-phoenix server --web-config-server "http://172.17.0.1/core/" --oidc-authority "https://172.17.0.1:9130" --oidc-metadata-url "https://172.17.0.1:91
30/.well-known/openid-configuration" --oidc-client-id phoenix &

export LDAP_URI="ldap://localhost:9125"
export LDAP_BINDDN="cn=admin,ou=users,dc=example,dc=com"
export LDAP_BINDPW="admin"
export LDAP_BASEDN="dc=example,dc=com"
export LDAP_SCOPE="sub"
export LDAP_LOGIN_ATTRIBUTE=uid
export LDAP_EMAIL_ATTRIBUTE=mail
export LDAP_NAME_ATTRIBUTE=givenName
export LDAP_UUID_ATTRIBUTE=uid
export LDAP_UUID_ATTRIBUTE_TYPE=text
export LDAP_FILTER="(objectClass=posixaccount)"
export KONNECTD_TLS=true
export KONNECTD_ISS="https://172.17.0.1:9130"
../ocis-konnectd/bin/ocis-konnectd --log-level debug server --identifier-registration-conf testidpr.yml --signing-kid gen1-2020-02-27
```

testidpr.yml
```
---

# OpenID Connect client registry.
clients:
  - id: phoenix
    name: OCIS
    application_type: web
    insecure: yes
    redirect_uris:
      - http://172.17.0.1:9100/oidc-callback.html
      - http://172.17.0.1:9100/
      - https://172.17.0.1:9200/oidc-callback.html
      - https://172.17.0.1:9200/
      - http://localhost:9100/oidc-callback.html
      - http://localhost:9100/
      - https://localhost:9200/oidc-callback.html
      - https://localhost:9200/
    origins:
      - http://172.17.0.1:9100
      - https://172.17.0.1:9200
      - http://localhost:9100
      - https://localhost:9200

authorities:

```

config/config.php
```
 'memcache.local' => '\\OC\\Memcache\\APCu',
  'openid-connect' => 
  array (
    'provider-url' => 'https://172.17.0.1:9130',
    'client-id' => 'phoenix',
    'loginButtonName' => 'OpenId Connect @ Konnectd',
  ),
  'debug' => true,
  'cors.allowed-domains' => 
  array (
    0 => 'https://172.17.0.1:9100',
    1 => 'http://172.17.0.1:9100',
    2 => 'http://localhost:9100',
  ),

```
