### ISSUE TITLE
Does not work with Ingress Controllers

### ISSUE THREAD

**Issue by mabushey** [owncloud/ocis#1639]
I'm currently using Traefik 1.7 (Soon to be replaced with Istio w/CertManager) for ingress. I have this for my docker-compose:
```
   owncloud:                                                                                                                                                                                                        
     image: owncloud/ocis                                                                                                                                                                                           
     container_name: owncloud                                                                                                                                                                                       
     restart: unless-stopped                                                                                                                                                                                        
     environment:                                                                                                                                                                                                   
       - PROXY_OIDC_INSECURE=true                                                                                                                                                                                   
     labels:                                                                                                                                                                                                        
       - traefik.enable=true                                                                                                                                                                                        
       - traefik.frontend.rule=Host:owncloud.example.com                                                                                                                                                                  
       - traefik.docker.network=web                                                                                                                                                                                 
     networks:                                                                                                                                                                                                      
       - web
```
When I go to "https://owncloud.example.com" I get `Client sent an HTTP request to an HTTPS server.`. Traefik most likely does not set the `X-Forwarded-Proto` correctly, but I should be able to tell Owncloud to just serve up http. I do NOT see this in the docs anywhere other than the PROXY_OIDC_INSECURE flag which hints at auth more than protocol.
