### ISSUE TITLE
Upgrading from v1.3 to v.14 wiped out all accounts

### ISSUE THREAD

**Issue by ubersteiny** [owncloud/ocis#1885]
## Describe the bug

Using docker-compose I pulled v1.4 to upgrade my v1.3. However when trying to login after the upgrade I received a HTTP 500 error. So I ran an ocis accounts list and it just prints out an empty table with no accounts listed.
```
+----+-------------+------+----------------+
| Id | DisplayName | Mail | AccountEnabled |
+----+-------------+------+----------------+
+----+-------------+------+----------------+
```

Here's a snippet from the logs if that helps.

`{"level":"error","service":"storage","pkg":"rhttp","traceid":"f664cac4acd09320968cb104c1d755cc","host":"127.0.0.1","method":"GET","uri":"/data/groups/167cbee2-0518-455a-bfb2-031fe0621e5d","url":"/data/groups/167cbee2-0518-455a-bfb2-031fe0621e5d","proto":"HTTP/1.1","status":500,"size":0,"start":"01/Apr/2021:13:27:04 +0000","end":"01/Apr/2021:13:27:04 +0000","time_ns":111021,"time":"2021-04-01T13:27:04Z","message":"http"}
{"level":"error","service":"storage","pkg":"rhttp","traceid":"58816e7582ab79c7c6d56b9170a90e7d","svc":"datatx","handler":"download","error":"could not read child node: xattr.get /var/tmp/ocis/storage/users/nodes/516df4de-185b-464b-aa25-dd1933269bbe user.ocis.blobid: no data available","action":"stat","time":"2021-04-01T13:27:04Z","message":"unexpected error"}
{"level":"error","service":"storage","pkg":"rhttp","traceid":"58816e7582ab79c7c6d56b9170a90e7d","host":"127.0.0.1","method":"GET","uri":"/data/groups/262982c1-2362-4afa-bfdf-8cbfef64a06e","url":"/data/groups/262982c1-2362-4afa-bfdf-8cbfef64a06e","proto":"HTTP/1.1","status":500,"size":0,"start":"01/Apr/2021:13:27:04 +0000","end":"01/Apr/2021:13:27:04 +0000","time_ns":153520,"time":"2021-04-01T13:27:04Z","message":"http"}
##################################################
{"level":"error","service":"storage","pkg":"rgrpc","traceid":"78d03ebfc342a251e842376f8a3bba25","error":"could not read child node: xattr.get /var/tmp/ocis/storage/users/nodes/b5868481-1cfd-4553-991f-7efa5bf086d7 user.ocis.blobid: no data available","time":"2021-04-01T13:27:13Z","caller":"/go/pkg/mod/github.com/cs3org/reva@v1.6.1-0.20210326165326-e8a00d9b2368/internal/grpc/services/storageprovider/storageprovider.go:668","message":"error listing container: path:\"/meta/accounts\" "}`

## Steps to reproduce

1. Upgrade from v1.3 to v1.4
2. Run 'ocis accounts list' on the server
3. Observe no accounts are listed anymore

## Expected behavior
Expected that the default admin, idp, and reva accounts be listed in the accounts list and that login is possible with the admin account.

## Actual behavior
No accounts are listed so logging in is not possible

## Setup
Started the server via docker-compose, using caddy as reverse proxy.
Env vars:
```
environment:
      OCIS_URL: https://ocis.example.ca
      OCIS_LOG_LEVEL: "error" # make oCIS less verbose
      PROXY_TLS: "false"
      PROXY_OIDC_INSECURE: "false"
      # change default secrets
      IDP_LDAP_BIND_PASSWORD: ${IDP_LDAP_BIND_PASSWORD}
      STORAGE_LDAP_BIND_PASSWORD: ${STORAGE_LDAP_BIND_PASSWORD}
      OCIS_JWT_SECRET: ${OCIS_JWT_SECRET}
```
<details>
<p>

```console
OCIS_VERSION=v1.4.0
BRANCH=v1.4.0
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>
