### ISSUE TITLE
allow serving ocis-web theme from a dedicated assets folder

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#2523]
In order to serve a custom theme it would be nice to be able to configure ocis to serve only the theme assets with the static middleware.

cc @kulmann @labkode

**Comment by wkloucek** [comment]
should be done together with https://github.com/owncloud/ocis/issues/1899

**Comment by dschmidt** [comment]
I needed this and came up with this workaround:

`docker-compose.yaml`:
```yaml
services:
  ocis:
    [...]
    environment:
      WEB_UI_THEME_PATH: /themes/owncloud/custom.theme.json
    volumes:
      - ./dev/docker/ocis.proxy.config.yaml:/etc/ocis/proxy.yaml 

  theme-server:
    image: joseluisq/static-web-server:2
    networks:
      ocis-net:
    environment:
      SERVER_ROOT: "/assets"
      SERVER_CORS_ALLOW_ORIGINS: "*"
      SERVER_CORS_ALLOW_HEADERS: "origin, content-type, x-request-id"
    ports:
      - 3890:80
    volumes:
      - ./dev/docker/themes:/assets/themes/owncloud
```

` ./dev/docker/ocis.proxy.config.yaml`:
```yaml
additional_policies:
  - name: ocis
    routes:
      - endpoint: /themes/owncloud/custom.theme.json
        backend: http://theme-server
        unprotected: true
```

This is just a workaround and overly complex for a simple task (especially given that `config.json` can just be mounted into the container). I would really like to see a simpler solution to this.
