### ISSUE TITLE
Account provisioning fails with external OIDC provider if id_token does not contain preferred_username claim.

### ISSUE THREAD

**Issue by coucoulala** [owncloud/ocis#2644]
## Describe the bug

Account provisioning fails when setting `PROXY_AUTOPROVISION_ACCOUNTS` to `true`, `PROXY_USER_OIDC_CLAIM` to `email` and the external OIDC provider does not support `preferred_username`.

## Steps to reproduce

1. Follow login flow with external OIDC provider which does not support `preferred_username`.
2. `id_token` and `/userinfo` endpoint of external OIDC are valid.
2. Account creation fails.

## Expected behavior
According to the [OIDC specifications](https://openid.net/specs/openid-connect-basic-1_0.html#StandardClaims) the `preferred_username` claim in an OIDC JWT is the following:
>Shorthand name by which the End-User wishes to be referred to at the RP, such as janedoe or j.doe. This value MAY be any valid JSON string including special characters such as @, /, or whitespace. The RP MUST NOT rely upon this value being unique, as discussed in Section 2.5.3.  

As far as I understand it, `preferred_username` is not strictly necessary. In case it is used for a human-readable username, perhaps a fallback to the `email` claim could be used.

## Actual behavior
Account creation fails.

## Setup
I've set up the server using the following docker-compose.yml
```
---
version: "3.7"

services:
  ocis:
    image: "owncloud/ocis:1.13"
    container_name: "ocis"
    entrypoint:
     - /bin/sh
     - /entrypoint-override.sh
    ports:
     - "9200:9200"
    environment:
      # PROXY
      PROXY_AUTOPROVISION_ACCOUNTS: "true"
      PROXY_OIDC_ISSUER: https://auth.example.org
      PROXY_OIDC_INSECURE: "false"
      PROXY_TLS: "false"
      PROXY_USER_OIDC_CLAIM: "email"
      # WEB
      WEB_OIDC_METADATA_URL: https://auth.example.org
      WEB_OIDC_AUTHORITY: https://auth.example.org
      WEB_OIDC_CLIENT_ID: ocis
      WEB_OIDC_SCOPE: "openid profile email"
      # Storage
      STORAGE_OIDC_ISSUER: https://auth.example.org
      STORAGE_LDAP_IDP: https://auth.example.org
      # CIS
      OCIS_URL: https://ocis.example.org
      OCIS_LOG_LEVEL: info
      # Secrets
      #IDP_LDAP_BIND_PASSWORD: [redacted]
      STORAGE_LDAP_BIND_PASSWORD: [redacted]
      OCIS_JWT_SECRET: [redacted]
      OCIS_TRANSFER_SECRET: [redacted]
    restart: always
    user: 1000:1000
    volumes:
      - ./config/ocis/entrypoint-override.sh:/entrypoint-override.sh
      - ./ocis-data:/var/tmp/ocis
```

<details>
Logs:
```
{"level":"warn","service":"storage","pkg":"rhttp","host":"127.0.0.1","method":"GET","uri":"/data/index.cs3/unique.github.com.owncloud.ocis.accounts.pkg.proto.v0.Account.Mail/mail@example.org","url":"/data/index.cs3/unique.github.com.owncloud.ocis.accounts.pkg.proto.v0.Account.Mail/mail@example.org","proto":"HTTP/1.1","status":404,"size":0,"start":"19/Oct/2021:11:49:24 +0000","end":"19/Oct/2021:11:49:24 +0000","time_ns":629028,"time":"2021-10-19T11:49:24Z","message":"http"} {"level":"error","service":"proxy","query":"mail eq 'mail@example.org'","time":"2021-10-19T11:49:24Z","message":"account not found"}{"level":"warn","service":"proxy","time":"2021-10-19T11:49:24Z","message":"Missing preferred_username claim"} {"level":"error","service":"proxy","error":"{\"id\":\"com.owncloud.api.accounts\",\"code\":400,\"detail\":\"preferred_name '' must be at least the local part of an email\",\"status\":\"Bad Request\"}","time":"2021-10-19T11:49:24Z","message":"Could not get user by claim"}
```

```console
OCIS_VERSION=vX.X.X
BRANCH=vX.X.X
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</details>
