### ISSUE TITLE
s3ng driver not working

### ISSUE THREAD

**Issue by NexZhu** [owncloud/ocis#2645]
## Describe the bug

Could not get `s3ng` driver to work. Error: "S3 configuration incomplete"

## Steps to reproduce

Deploy OCIS on Kubernetes using the official Helm chart with the following env vars:
```yaml
spec:
  containers:
  - env:
    - name: STORAGE_HOME_DRIVER
      value: s3ng
    - name: STORAGE_METADATA_DRIVER
      value: ocis
    - name: STORAGE_USERS_DRIVER
      value: s3ng
    - name: STORAGE_USERS_DRIVER_S3NG_ACCESS_KEY
      value: RANDOM_PLACEHOLDER
    - name: STORAGE_USERS_DRIVER_S3NG_BUCKET
      value: random-owncloud
    - name: STORAGE_USERS_DRIVER_S3NG_ENDPOINT
      value: http://random-owncloud.oss-cn-zhangjiakou.aliyuncs.com
    - name: STORAGE_USERS_DRIVER_S3NG_REGION
      value: oss-cn-zhangjiakou
    - name: STORAGE_USERS_DRIVER_S3NG_SECRET_KEY
      value: RANDOM_PLACEHOLDER
```

## Expected behavior

OCIS starts successfully.

## Actual behavior

Pod failed to start with the following error logs:
```json
{"level":"error","service":"storage","error":"unable to register services: rgrpc: grpc service storageprovider could not be started,: S3 configuration incomplete","time":"2021-10-20T02:11:18Z","message":"error starting the grpc server"}
```

Which comes from:
https://github.com/cs3org/reva/blob/a8c61401b662d8e09175416c0556da8ef3ba8ed6/pkg/storage/fs/s3ng/s3ng.go
