### ISSUE TITLE
S3 Storage Metadata backend not working (Login not possible)

### ISSUE THREAD

**Issue by iFrozenPhoenix** [owncloud/ocis#2668]
## Describe the bug

Currently I'm facing an 500 error when I'm trying to login to the UI while using S3 storage backend for users and metadata storage.

## Steps to reproduce

1. Deploy OCIS latest image with the env variables mentioned below.

## Expected behavior
Login is possible.
Further, if some kind of initial population of the metadata storage folder is required, e.g. during server startup, it is expected that these files are also created with the S3 metadata backend.

## Actual behavior
The server starts but shows errors during startup, e.g.:
```
{"level":"warn","service":"storage","pkg":"rhttp","host":"127.0.0.1","method":"GET","uri":"/data/index.cs3/non_unique.github.com.owncloud.ocis.accounts.pkg.proto.v0.Group.DisplayName/Philosophy%20haters/167cbee2-0518-455a-bfb2-031fe0621e5d","url":"/data/index.cs3/non_unique.github.com.owncloud.ocis.accounts.pkg.proto.v0.Group.DisplayName/Philosophy%20haters/167cbee2-0518-455a-bfb2-031fe0621e5d","proto":"HTTP/1.1","status":404,"size":0,"start":"24/Oct/2021:14:05:08 +0000","end":"24/Oct/2021:14:05:08 +0000","time_ns":87753,"time":"2021-10-24T14:05:08Z","message":"http"}
```
When trying to login with user admin and password admin I see the following errors in the logs:
```
{"level":"error","service":"glauth","error":"{\"id\":\"com.owncloud.api.accounts\",\"code\":401,\"detail\":\"account not found or invalid credentials\",\"status\":\"Unauthorized\"}","handler":"ocis","username":"idp","binddn":"cn=idp,ou=sysusers,dc=ocis,dc=test","src":{"IP":"127.0.0.1","Port":41562,"Zone":""},"time":"2021-10-24T14:08:25Z","message":"Login failed"}
{"level":"error","service":"idp","error":"ldap identifier backend logon connect error: LDAP Result Code 49 \"Invalid Credentials\": ","time":"2021-10-24T14:08:25Z","message":"identifier failed to logon with backend"}
```

## Setup

```
- name: OCIS_URL
  value: https://{{ (index .Values.ingress.hosts 0).host }}
- name: STORAGE_USERS_DRIVER_S3NG_BUCKET
  value: {{ .Values.config.storageBackend.s3.bucket }}
- name: STORAGE_USERS_DRIVER_S3NG_REGION
  value: {{ .Values.config.storageBackend.s3.region }}
- name: STORAGE_USERS_DRIVER_S3NG_ENDPOINT
  value: {{ .Values.config.storageBackend.s3.url }}
- name: STORAGE_USERS_DRIVER_S3NG_ACCESS_KEY
  valueFrom:
    secretKeyRef:
      key: accessKey
      name: {{ default (include "owncloud.fullname" .) .Values.config.storageBackend.s3.secretKeyRef }}
- name: STORAGE_USERS_DRIVER_S3NG_SECRET_KEY
  valueFrom:
    secretKeyRef:
      key: secretKey
      name: {{ default (include "owncloud.fullname" .) .Values.config.storageBackend.s3.secretKeyRef }}
- name: STORAGE_USERS_DRIVER
  value: s3ng
- name: STORAGE_METADATA_DRIVER
  value: s3ng
- name: STORAGE_METADATA_DRIVER_S3NG_BUCKET
  value: {{ .Values.config.storageBackend.s3.metadataBucket }}
- name: STORAGE_METADATA_DRIVER_S3NG_REGION
  value: {{ .Values.config.storageBackend.s3.region }}
- name: STORAGE_METADATA_DRIVER_S3NG_ENDPOINT
  value: {{ .Values.config.storageBackend.s3.url }}
- name: STORAGE_METADATA_DRIVER_S3NG_ACCESS_KEY
  valueFrom:
    secretKeyRef:
      key: accessKey
      name: {{ default (include "owncloud.fullname" .) .Values.config.storageBackend.s3.secretKeyRef }}
- name: STORAGE_METADATA_DRIVER_S3NG_SECRET_KEY
  valueFrom:
    secretKeyRef:
      key: secretKey
      name: {{ default (include "owncloud.fullname" .) .Values.config.storageBackend.s3.secretKeyRef }}
```

```console
OCIS_VERSION=v1.13.0
ocis --version output: e146b03a
BRANCH=vX.X.X
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

## Additional context
If I'm just using the S3 users storage backend the issue does not occur.
While inspecting the metadata storage in the container with just using S3 users storage, the blob folder is populated with some UUID named files. With the S3 metadata storage backend, the folder is empty.

I've also tried to workaround the missing population with starting ocis first just with S3 users storage backend and copying the metadata into a tmp dir outside of the container and tried with starting ocis with S3 metadata storage backend.
But during the copy process I've realized that there are many symlinks originating from the metadata blob dir.
