### ISSUE TITLE
ocis questions data directory, auth and office integration

### ISSUE THREAD

**Issue by jboesh** [owncloud/ocis#2853]
Hi

Owncloud is running on ocis.mydomain.com with the docker compose snippit below.

- Is it possible to have a data directory that I can mount as a volume? 
the config volume is used for application files but I've got some documents on the host too that I want to use in Owncloud (without uploading it first).

- another question, is it possible to disable the authentication? I've got my own authentication so i dont need another one in Ocis.
- and the last question: Is it possible to add OnlyOffice yet?

```
version: "3.7"
services:
  ocis:
    image: owncloud/ocis:latest
    environment:
      - OCIS_URL=https://ocis.mydomain.com
      - OCIS_LOG_LEVEL=error
      - PROXY_OIDC_INSECURE=false
      - PROXY_TLS=false
    ports:
      - 9200:9200
    volumes:
      - /share/docker/appdata/ocis/config:/var/tmp/ocis
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ocis-rtr.entrypoints=https"
        - "traefik.http.routers.ocis-rtr.rule=Host(`ocis.mydomain.com`)"
        - "traefik.http.routers.ocis-rtr.middlewares=secure-headers@file"
        - "traefik.http.routers.ocis-rtr.service=ocis-svc"
        - "traefik.http.services.ocis-svc.loadbalancer.server.port=9200"

```
