### ISSUE TITLE
`ocis dumpconfig`

### ISSUE THREAD

**Issue by dragonchaser** [owncloud/ocis#3646]
It would be nice to have a ocis command the would outomatically dump the used runtime config to the terminal as a yaml tree.
Fields containing confidential values should be automatically redacted (those could be marked using a custom tag at the variables definition in the code).

example:

```bash
$> ocis dumpconfig
```
Result:
```yaml
token_manager:
  jwt_secret: <redacted>
machine_auth_api_key: <redacted>
transfer_secret: <redacted>
graph:
  spaces:
    insecure: true
  identity:
    ldap:
      bind_password: <redacted>
idp:
  ldap:
    bind_password: <redacted>
idm:
  service_user_passwords:
    admin_password: <redacted>
    idm_password: <redacted>
    reva_password: <redacted>
    idp_password: <redacted>
proxy:
  insecure_backends: true
frontend:
  archiver:
    insecure: true
  app_provider:
    insecure: true
auth_basic:
  auth_providers:
    ldap:
      bind_password: <redacted>
auth_bearer:
  auth_providers:
    oidc:
      insecure: true
user:
  drivers:
    ldap:
      bind_password: <redacted>
group:
  drivers:
    ldap:
      bind_password: <redacted>
storage_metadata:
  data_provider_insecure: true
storage_users:
  data_provider_insecure: true
ocdav:
  insecure: true
thumbnails:
  thumbnail:
    webdav_allow_insecure: true
    cs3_allow_insecure: true
```
