### ISSUE TITLE
upload to ocis-eos fails

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#396]
Installed according to the instructions at https://owncloud.github.io/ocis/eos on a hetzner cloud machine.

three additional variables are needed:
```
$ cat .env
OCIS_DOMAIN=$IPADDR
REVA_FRONTEND_URL=https://$IPADDR:9200
REVA_DATAGATEWAY_URL=https://$IPADDR:9200/data
```
These need to be added to a .env file next the docker-compose.yml in a git checkout of https://github.com/owncloud/ocis master branch (or v1.0.0-beta8 -- same behaviour).
These three variables must also be added to `config/eos-docker.env`

To make the IDP login work, we also need to allow additional `redirect_uris` and `origins` entries in `config/identifier-registration.yaml`
As this file is not part of the ocis git tree, but auto-generated upon first start, we patch the file after starting ocis briefly.

```
docker-compose up -d ocis
... wait ...
docker-compose stop ocis
vi config/identifier-registration.yaml 
  clients:
  - id: phoenix
    name: ownCloud web app
    application_type: web
    insecure: yes
    trusted: yes
    redirect_uris:
      - https://95.217.189.160:9200/oidc-callback.html
      - http://localhost:9100/oidc-callback.html
      - http://localhost:9100/
      - https://localhost:9200/
      - https://localhost:9200/oidc-callback.html
    origins:
      - https://95.217.189.160:9200
      - http://95.217.189.160:9100
      - http://localhost:9100
      - https://localhost:9200

```
