### ISSUE TITLE
Again the problem with keycloak&collabora

### ISSUE THREAD

**Issue by rtest12** [owncloud/ocis#3979]
I ran 4 containers, wopi, ocis, collabora and appdriver-collabora.
And my own keycloak instance. 
I'm not using traefik, I have nginx as a reverse proxy
Then i click on the file button "open in collabora", i get a blank page with 500 error in console. 
My docker's logs
```
{"level":"error","service":"gateway","pkg":"rgrpc","traceid":"00000000000000000000000000000000","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36","from":"tcp://127.0.0.1:45622","uri":"/cs3.gateway.v1beta1.GatewayAPI/OpenInApp","start":"16/Jun/2022:13:47:14 +0000","end":"16/Jun/2022:13:47:14 +0000","time_ns":6579265,"code":"Unknown","time":"2022-06-16T13:47:14Z","message":"unary"}
{"level":"error","service":"frontend","pkg":"rhttp","traceid":"00000000000000000000000000000000","error":"rpc error: code = Unknown desc = gateway: error calling OpenInApp: rpc error: code = PermissionDenied desc = auth: core access token is invalid","time":"2022-06-16T13:47:14Z","message":"Error contacting the requested application, please use a different one or try again later"}
{"level":"error","service":"frontend","pkg":"rhttp","traceid":"00000000000000000000000000000000","host":"127.0.0.1","method":"POST","uri":"/app/open?file_id=1284d238-aa92-42ce-bdc4-0b0000009157$f3277494-cbef-4c00-8ff0-fccc2f3dca48!44432905-a206-4e85-8df1-8d98d4dcf141&app_name=Collabora","url":"/app/open?file_id=1284d238-aa92-42ce-bdc4-0b0000009157$f3277494-cbef-4c00-8ff0-fccc2f3dca48!44432905-a206-4e85-8df1-8d98d4dcf141&app_name=Collabora","proto":"HTTP/1.1","status":500,"size":134,"start":"16/Jun/2022:13:47:14 +0000","end":"16/Jun/2022:13:47:14 +0000","time_ns":15799297,"time":"2022-06-16T13:47:14Z","message":"http"}
```

```
{"level":"error","service":"app-provider","error":"unable to register services: rgrpc: grpc service appprovider could not be started,: Get \"[https://colla.ex.com/hosting/discovery\](https://colla.ex.com/hosting/discovery/)": context deadline exceeded","time":"2022-06-16T13:46:53.904600869Z","message":"error starting the grpc server"}
{"level":"error","service":"app-provider","pkg":"rgrpc","traceid":"00000000000000000000000000000000","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36","from":"tcp://172.29.0.3:57478","uri":"/[cs3.app](http://cs3.app/).provider.v1beta1.ProviderAPI/OpenInApp","start":"16/Jun/2022:13:47:14 +0000","end":"16/Jun/2022:13:47:14 +0000","time_ns":260607,"code":"PermissionDenied","time":"2022-06-16T13:47:14.72522977Z","message":"unary"}
```

My yml
```
---
version: "3.7"


services:
  ocis:
    image: owncloud/ocis:${OCIS_DOCKER_TAG:-latest}
    networks:
      ocis-net:
    entrypoint:
      - /bin/sh
    # run ocis init to initialize a configuration file with random secrets
    # it will fail on subsequent runs, because the config file already exists
    # therefore we ignore the error and then start the ocis server
    command: ["-c", "ocis init || true; ocis server"]
    environment:
      GATEWAY_GRPC_ADDR: 0.0.0.0:9142 # make the REVA gateway accessible to the app drivers
      PROXY_OIDC_ISSUER: https://id.ex.com/auth/realms/example
      WEB_OIDC_AUTHORITY: https://id.ex.com/auth/realms/example
      WEB_OIDC_SCOPE: "openid profile email"
      WEB_OIDC_METADATA_URL: https://id.ex.com/auth/realms/example/.well-known/openid-configuration
      STORAGE_OIDC_ISSUER: https://id.ex.com/auth/realms/example
      STORAGE_LDAP_IDP: https://id.ex.com/auth/realms/example
      ACCOUNTS_DEMO_USERS_AND_GROUPS: "false"

      PROXY_ENABLE_BASIC_AUTH: "${PROXY_ENABLE_BASIC_AUTH:-false}"
      # admin user password
      IDM_ADMIN_PASSWORD: "${ADMIN_PASSWORD:-admin}" # this overrides the admin password from the configuration file
      # demo users
      IDM_CREATE_DEMO_USERS: "${DEMO_USERS:-false}"

      # Keycloak IDP specific configuration
      PROXY_AUTOPROVISION_ACCOUNTS: "true"
      OCIS_OIDC_ISSUER: https://${KEYCLOAK_DOMAIN:-keycloak.owncloud.test}/auth/realms/${KEYCLOAK_REALM:-oCIS}
      WEB_OIDC_CLIENT_ID: ${OCIS_OIDC_CLIENT_ID:-web}
      # general config
      OCIS_URL: https://docs.ex.com/
      OCIS_LOG_LEVEL: ${OCIS_LOG_LEVEL:-error} # make oCIS less verbose
      OCIS_LOG_COLOR: "${OCIS_LOG_COLOR:-false}"
      PROXY_TLS: "false" # do not use SSL between Traefik and oCIS
      # demo users
      IDM_CREATE_DEMO_USERS: "${DEMO_USERS:-false}"
      # change default secrets
      IDP_LDAP_BIND_PASSWORD: ${IDP_LDAP_BIND_PASSWORD:-idp}
      STORAGE_LDAP_BIND_PASSWORD: ${STORAGE_LDAP_BIND_PASSWORD:-reva}
      OCIS_JWT_SECRET: ${OCIS_JWT_SECRET:-Pive-Fumkiu4}
      STORAGE_TRANSFER_SECRET: ${STORAGE_TRANSFER_SECRET:-replace-me-with-a-transfer-secret}
      OCIS_MACHINE_AUTH_API_KEY: ${OCIS_MACHINE_AUTH_API_KEY:-change-me-please}
      # INSECURE: needed if oCIS / Traefik is using self generated certificates
      OCIS_INSECURE: "${INSECURE:-false}"
    ports:
      - "9200:9200"
    volumes:
     - ./config/ocis/app-registry.yaml:/etc/ocis/app-registry.yaml
     - ocis-config:/etc/ocis
     - ocis-data:/var/lib/ocis
    logging:
      driver: "local"
    restart: always


  wopiserver:
    image: cs3org/wopiserver:${WOPISERVER_DOCKER_TAG:-latest}
    networks:
      ocis-net:
    entrypoint:
      - /bin/bash
      - /[entrypoint-override.sh](http://entrypoint-override.sh/)
    environment:
      WOPISERVER_INSECURE: "${INSECURE:-false}"
      WOPISECRET: ${WOPI_JWT_SECRET:-LoremIpsum567}
      IOPSECRET: ${WOPI_IOP_SECRET:-LoremIpsum123}
      WOPISERVER_DOMAIN: ${WOPISERVER_DOMAIN:-wopiserver.owncloud.test}
      COLLABORA_DOMAIN: ${COLLABORA_DOMAIN:-collabora.owncloud.test}
    volumes:
      - ./config/wopiserver/[entrypoint-override.sh](http://entrypoint-override.sh/):/[entrypoint-override.sh](http://entrypoint-override.sh/)
      - ./config/wopiserver/wopiserver.conf.dist:/etc/wopi/wopiserver.conf.dist
      - wopi-data:/var/wopi_local_storage
      - wopi-logs:/var/log/wopi
    ports:
      - 8880:8880
    logging:
      driver: "local"
    restart: always

  ocis-appdriver-collabora:
    image: owncloud/ocis:${OCIS_DOCKER_TAG:-latest}
    networks:
      ocis-net:
    command: app-provider server
    environment:
      REVA_GATEWAY: ${REVA_GATEWAY:-ocis:9142}
      APP_PROVIDER_GRPC_ADDR: 0.0.0.0:9164
      APP_PROVIDER_EXTERNAL_ADDR: ocis-appdriver-collabora:9164
      APP_PROVIDER_DRIVER: wopi
      APP_PROVIDER_WOPI_APP_NAME: Collabora
      APP_PROVIDER_WOPI_APP_ICON_URI: https://${COLLABORA_DOMAIN:-collabora.owncloud.test}/favicon.ico
      APP_PROVIDER_WOPI_APP_URL: https://${COLLABORA_DOMAIN:-collabora.owncloud.test}
      APP_PROVIDER_WOPI_INSECURE: "${INSECURE:-false}"
      APP_PROVIDER_WOPI_WOPI_SERVER_IOP_SECRET: ${WOPI_IOP_SECRET:-LoremIpsum123}
      APP_PROVIDER_WOPI_WOPI_SERVER_EXTERNAL_URL: https://${WOPISERVER_DOMAIN:-wopiserver.owncloud.test}
    volumes:
      - ocis-config:/etc/ocis
    logging:
      driver: "local"
    restart: always

  collabora:
    image: collabora/code:6.4.11.3
    networks:
      ocis-net:
    environment:
      domain: ${OCIS_DOMAIN:-ocis.owncloud.test}
      DONT_GEN_SSL_CERT: "YES"
      extra_params: --o:ssl.enable=false --o:ssl.termination=true --o:welcome.enable=false --o:net.frame_ancestors=${OCIS_DOMAIN:-ocis.owncloud.test}
      username: ${COLLABORA_ADMIN_USER}
      password: ${COLLABORA_ADMIN_PASSWORD}
    cap_add:
      - MKNOD

    ports:
      - "9980:9980"
    logging:
      driver: "local"
    restart: always



volumes:
  certs:
  ocis-data:
  wopi-data:
  wopi-logs:
  ocis-config:
networks:
  ocis-net:
```

and .env
```
### oCIS settings ###
# oCIS version. Defaults to "latest"
INSECURE=true
OCIS_DOCKER_TAG=latest
# Domain of oCIS, where you can find the frontend. Defaults to "ocis.owncloud.test"
OCIS_DOMAIN=docs.ex.com
# IDP LDAP bind password. Must be changed in order to have a secure oCIS. Defaults to "idp".
IDP_LDAP_BIND_PASSWORD=1234
# Storage LDAP bind password. Must be changed in order to have a secure oCIS. Defaults to "reva".
STORAGE_LDAP_BIND_PASSWORD=2345
# JWT secret which is used for the storage provider. Must be changed in order to have a secure oCIS. Defaults to "Pive-Fumkiu4"
OCIS_JWT_SECRET=3456
# JWT secret which is used for uploads to create transfer tokens. Must be changed in order to have a secure oCIS. Defaults to "replace-me-with-a-transfer-s>
STORAGE_TRANSFER_SECRET=4567
# Machine auth api key secret. Must be changed in order to have a secure oCIS. Defaults to "change-me-please"
OCIS_MACHINE_AUTH_API_KEY=5678
DEMO_USERS=false

### Wopi server settings ###
# cs3org wopi server version. Defaults to "latest"
WOPISERVER_DOCKER_TAG=
# cs3org wopi server domain. Defaults to "wopiserver.owncloud.test"
WOPISERVER_DOMAIN=wopi.ex.com
# JWT secret which is used for the documents to be request by the Wopi client from the cs3org Wopi server. Must be change in order to have a secure Wopi se>
WOPI_JWT_SECRET=7890
# JWT secret which is used for the documents to be request by the Wopi client from the cs3org Wopi server. Must be change in order to have a secure Wopi se>
WOPI_IOP_SECRET=6789


### Collabora settings ###
# Domain of Collabora, where you can find the frontend. Defaults to "collabora.owncloud.test"
COLLABORA_DOMAIN=office.ex.com
# Admin user for Collabora. Defaults to blank, provide one to enable access
COLLABORA_ADMIN_USER=myuser
# Admin password for Collabora. Defaults to blank, provide one to enable access
COLLABORA_ADMIN_PASSWORD=4321
### For keycloak
OCIS_OIDC_CLIENT_ID=ocis
# IDP LDAP bind password. Must be changed in order to have a secure oCIS. Defaults to "idp".
# Domain of Keycloak, where you can find the management and authentication frontend. Defaults to "keycloak.owncloud.test"
KEYCLOAK_DOMAIN=id.ex.com
# Realm which to be used with oCIS. Defaults to "oCIS"
KEYCLOAK_REALM=example

```
