### ISSUE TITLE
publicUpload parameter in share updates

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ocis#4111]
## Describe the bug

Sending `publicUpload` parameter in `PUT` request to update a share (only upload permission) returns an invalid permission value, reflected in Android mobile client.

## Steps to reproduce

Steps to reproduce the behaviour:

1. Create a public link, for example in that way:

```
curl -k -X POST -u <username>:<pwd> https://<url>/ocs/v2.php/apps/files_sharing/api/v1/shares -d 'path=/Documents&shareType=3&name=myLink&permissions=1'
```

A link over `Documents` with basic permission 1 (Download/View) created.

2. Update the link, by changing permissions to 4 (Upload only) including `publicUpload` (available as https://doc.owncloud.com/server/next/developer_manual/core/apis/ocs-share-api.html#update-share)

```
curl -k -X PUT -u <username>:<pwd> https://<url>/ocs/v2.php/apps/files_sharing/api/v1/shares/<share_id> -d 'path=/Documents/&shareType=3&name=MyLink&permissions=4&publicUpload=true'
```

## Actual behavior

Link updated with permissions 15, not 4. Check with

```
curl -k -u <username>:<pwd> https://<url>/ocs/v2.php/apps/files_sharing/api/v1/shares 
```

that returns

`<permissions>15</permissions>`

## Expected behavior

In the final GET after updating permissions:

`<permissions>4</permissions>`

## Setup

```
Version: 2.0.0-beta.4+27b71bf52
Compiled: 2022-07-06 00:00:00 +0000 UTC
```

created via docker compose file:

``` 
version: "3.7"

services:
  ocis:
    image: owncloud/ocis:latest
    ports:
      - 9200:9200
      - 9215:9215
    environment:
      OCIS_INSECURE: "true"
      OCIS_URL: "https://myServerIP:9200"
      IDM_CREATE_DEMO_USERS: "true"
      IDM_ADMIN_PASSWORD: "admin"
    restart: "no"
    entrypoint:
      - /bin/sh
    # run ocis init to initialize a configuration file with random secrets
    # it will fail on subsequent runs, because the config file already exists
    # therefore we ignore the error and then start the ocis server
    command: ["-c", "ocis init || true; ocis server"]
``` 

## Additional context

`publicUpload` has been used in clients and still supported in oC10 with correct results. Documentation related (not sure if outdated, i hope it does not):

https://doc.owncloud.com/server/next/developer_manual/core/apis/ocs-share-api.html#update-share

By removing the `publicUpload` parameter from the `PUT` request, everything works fine and sets permissions 4 as expected. But, parameter in request payload is correct and should be handled.
