### ISSUE TITLE
User not selectable after entering credentials in browser

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ocis#4704]
Please, feel free to move this issue if it is not the correct place.

I was able to reproduce by using desktop and iOS clients, 

Server: `oCIS 2.0.0 beta8` , deployed via docker

Steps for desktop:

1. Enter URL -> redirected to browser (using incognito mode to avoid existing sessions)
2. Enter credentials in browser

Then:

![Screenshot 2022-09-28 at 13 31 56](https://user-images.githubusercontent.com/14894746/192768934-7c9bc60f-2469-4747-9bbd-2a07f4e64ddb.png)

two options: `alice` and `user another account` . Neither of them is clickable. By cancelling the view and open again, both are clickable.

Same steps, issue also reproducible in iOS.

Same steps, reproducible against `ocis.owncloud.works` (now with `2.0.0-beta.8+e4c28def8"`)

## Expected behavior

This view only makes sense for editing an existing account, or with multiaccount. With a first single account, choosing the user itself is expendable. In case it is, two not clickable options is not good either

## Setup

my `docker_compose.yml` file:

```
version: "3.7"

services:
  ocis:
    image: owncloud/ocis:2.0.0-beta.8
    ports:
      - 9200:9200
      - 9215:9215
    environment:
      OCIS_INSECURE: "true"
      OCIS_URL: "https://xx.xx.xx.xx:9200"
      IDM_CREATE_DEMO_USERS: "true"
      IDM_ADMIN_PASSWORD: "admin"
      PROXY_ENABLE_BASIC_AUTH: "true"
    restart: "no"
    entrypoint:
      - /bin/sh
```
