### ISSUE TITLE
Auto-assigning the default 'User' role fails

### ISSUE THREAD

**Issue by markv9401** [owncloud/ocis#4787]
## Describe the bug

Auto-assigning the default 'User' role fails.
Also see the discussion about it: https://talk.owncloud.com/channel/infinitescale/thread/CXgxnAobTDrk5kmqx?jump=pphqPBZQmnn459wJT

## Steps to reproduce

1. Run the server with an LDAP backend, for example:
2. Try logging in with any user that's not specified as the admin in the aforementioned config (thus missing role assignments)

## Expected behavior
Login working normally, default User role being auto-assigned

## Actual behavior
Login failing in an endless loop, role not being assigned

## Setup
Example:

```services:
  ocis:
    image: owncloud/ocis:latest
    restart: always
    entrypoint: "/bin/sh"
    command: ["-c", "ocis init || true; ocis server"]
    volumes:
      - ./ocis/config:/ocis/config
      - ./ocis/data:/var/lib/ocis
    ports:
      - 9920:9200
    environment:
      OCIS_URL: "https://ocis.rowra.org"
      OCIS_LOG_LEVEL: "debug"
      OCIS_LOG_COLOR: "true"
      OCIS_LOG_PRETTY: "true"
      PROXY_TLS: "false"
      OCIS_INSECURE: "false"

      LDAP_URI: ldaps://ldap.rowra.org
      IDP_LDAP_URI: ldaps://ldap.rowra.org
      LDAP_INSECURE: "true"
      LDAP_BIND_DN: "uid=admin,ou=people,dc=rowra,dc=org"
      LDAP_BIND_PASSWORD: "***************"
      GRAPH_LDAP_SERVER_WRITE_ENABLED: "false"
      LDAP_LOGIN_ATTRIBUTES: "uid"
      OCIS_ADMIN_USER_ID: "06ac7f86-e859-335e-8aa3-ab6724d9994f"
      #IDP_LDAP_LOGIN_ATTRIBUTE: "uid"

      LDAP_GROUP_BASE_DN: "ou=groups,dc=rowra,dc=org"
      LDAP_GROUP_OBJECTCLASS: "groupOfUniqueNames"
      LDAP_GROUP_FILTER: ""
      LDAP_GROUP_SCHEMA_ID: "cn"

      LDAP_USER_BASE_DN: "ou=people,dc=rowra,dc=org"
      LDAP_USER_OBJECTCLASS: "person"
      LDAP_USER_FILTER: ""
      LDAP_USER_SCHEMA_ID: "entryUUID" #"uid" #"uuid"

      OCIS_RUN_SERVICES: app-registry,app-provider,audit,auth-basic,auth-machine,frontend,gateway,graph,groups,idp,nats,notifications,ocdav,ocs,proxy,search,settings,sharing,storage-system,storage-publiclink,storage-shares,storage-users,store,thumbnails,users,web,webdav
networks:
  default:
    driver: bridge
    name: poc_ocis
```

## Additional context
Attached `info` and `debug` level logs
[ocis_role_debug.txt](https://github.com/owncloud/ocis/files/9762791/ocis_role_debug.txt)
[ocis_role_info.txt](https://github.com/owncloud/ocis/files/9762793/ocis_role_info.txt)

https://talk.owncloud.com/channel/infinitescale/thread/CXgxnAobTDrk5kmqx?jump=pphqPBZQmnn459wJT

**Comment by rhafer** [comment]
Thanks. for the report. Looking at the debug logs,  I think you found a bug introduced by a recent change in our setttings service (likely this one: https://github.com/owncloud/ocis/pull/4615/commits/87eaf72020a71f9714ec2c1b396023f32a5d8523). :sob: 

@micbar I think this deserves some priority as it is breaking external LDAP server setups.

**Comment by martadinata666** [comment]
placing myself here, as i got same issue.

**Comment by martadinata666** [comment]
Still fail if LDAP_USER_FILTER from some group existed.
So here is the condition, this is the working but im using UID instead UUID.
```
version: "3.8"
services:
  app:
   image: owncloud/ocis:latest
   entrypoint:
      - /bin/sh
   command: ["-c", "ocis init || true; ocis server"]
   volumes:
     - ocis-config:/etc/ocis
     - ocis-data:/var/lib/ocis
   ports:
     - 9200:9200
   environment:
     OCIS_INSECURE: "true"
     OCIS_LOG_LEVEL: "debug"

     LDAP_URI: ldap://192.168.0.2:3890
     LDAP_INSECURE: true
     LDAP_BIND_DN: "uid=readonly,ou=people,dc=example,dc=com"
     LDAP_BIND_PASSWORD: "ldapreadonly"
     LDAP_LOGIN_ATTRIBUTES: "uid"
     OCIS_ADMIN_USER_ID: "some-uid"

     GRAPH_LDAP_SERVER_WRITE_ENABLED: "false"

     LDAP_GROUP_FILTER: "(cn=ocis,ou=groups,dc=example,dc=com)"
     LDAP_GROUP_BASE_DN: "ou=groups,dc=example,dc=com"
     LDAP_GROUP_OBJECTCLASS: "groupOfUniqueNames"
     LDAP_GROUP_SCHEMA_ID: "cn"

     LDAP_USER_FILTER: "(memberOf=cn=ocis,ou=groups,dc=example,dc=com)"
     LDAP_USER_BASE_DN: "ou=people,dc=example,dc=com"
     LDAP_USER_OBJECTCLASS: "person"
     LDAP_USER_SCHEMA_ID: "uid"

     OCIS_RUN_SERVICES: app-registry,app-provider,audit,auth-basic,auth-machine,frontend,gateway,graph,groups,idp,nats,notifications,ocdav,ocs,proxy,search,settings,sharing,storage-system,storage-publiclink,storage-shares,storage-users,store,thumbnails,users,web,webdav

     IDP_LDAP_URI: ldap://192.168.0.2:3890
     IDP_LDAP_LOGIN_ATTRIBUTE: "uid"
     IDP_LDAP_UUID_ATTRIBUTE: "uid"

volumes:
  ocis-config:
  ocis-data:

```

But when changing uid to uuid, i got access denied, another weird issue is when LDAP filter is empty or just checking uid like `(|(uid=user1)(uid=user2))` it will login fine.
```
version: "3.8"
services:
  app:
   image: owncloud/ocis:latest
   entrypoint:
      - /bin/sh
   command: ["-c", "ocis init || true; ocis server"]
   volumes:
     - ocis-config:/etc/ocis
     - ocis-data:/var/lib/ocis
   ports:
     - 9200:9200
   environment:
     OCIS_INSECURE: "true"
     OCIS_LOG_LEVEL: "debug"

     LDAP_URI: ldap://192.168.0.2:3890
     LDAP_INSECURE: true
     LDAP_BIND_DN: "uid=readonly,ou=people,dc=example,dc=com"
     LDAP_BIND_PASSWORD: "ldapreadonly"
     LDAP_LOGIN_ATTRIBUTES: "uid"
     OCIS_ADMIN_USER_ID: "some-lonng-uuid-number"

     GRAPH_LDAP_SERVER_WRITE_ENABLED: "false"

     LDAP_GROUP_FILTER: "(cn=ocis,ou=groups,dc=example,dc=com)"
#     LDAP_GROUP_FILTER: ""
     LDAP_GROUP_BASE_DN: "ou=groups,dc=example,dc=com"
     LDAP_GROUP_OBJECTCLASS: "groupOfUniqueNames"
     LDAP_GROUP_SCHEMA_ID: "cn"

     LDAP_USER_FILTER: "(memberOf=cn=ocis,ou=groups,dc=example,dc=com)"
#     LDAP_USER_FILTER: ""
     LDAP_USER_BASE_DN: "ou=people,dc=example,dc=com"
     LDAP_USER_OBJECTCLASS: "person"
     LDAP_USER_SCHEMA_ID: "uuid"

     OCIS_RUN_SERVICES: app-registry,app-provider,audit,auth-basic,auth-machine,frontend,gateway,graph,groups,idp,nats,notifications,ocdav,ocs,proxy,search,settings,sharing,storage-system,storage-publiclink,storage-shares,storage-users,store,thumbnails,users,web,webdav

     IDP_LDAP_URI: ldap://192.168.0.2:3890
     IDP_LDAP_LOGIN_ATTRIBUTE: "uid"
     IDP_LDAP_UUID_ATTRIBUTE: "uuid"

volumes:
  ocis-config:
  ocis-data:
```
