### ISSUE TITLE
OIDC login with Authelia failed with "token contains an invalid number of segments"

### ISSUE THREAD

**Issue by NexZhu** [owncloud/ocis#4895]
## Describe the bug

I deployed the latest version `owncloud/ocis:2.0.0-beta.8` with the official Helm chart and configured it to authenticate users with an OIDC provider [Authelia](https://github.com/authelia/authelia) instance, here's what happens:

1. Open owncloud URL, redirected to Authelia.
2. Login and click`Accept` in the OAuth2 consent page.
3. Redirected to `https://owncloud.example.com/oidc-callback.html?code=a0j4L6_ZuH2QbH5mPFJJbCVLH-OO9jIJg5mscuxPSiw.oqHE9PYJP1SnVboJth46PyRES17YKo9FT2WyONQhSTg&scope=openid+profile+email&state=9d6a21e638474d40bdaab11ebfb27088`
4. Browser sent XHR request to `https://owncloud.example.com/ocs/v1.php/cloud/user` with header: `authorization: Bearer p9UAAo2wIMfb8RLlN_f7dW9u5mpxUl76IfUH3jAMEos.4b8WcEj1mLZOen34w719wsjoJa5tpq_ArXvub4M6NrY`, resulted in `401` status code.
5. The `proxy` pod printed the following error log:
```
2022-10-25T09:16:57Z DBG director found method=GET path=/ocs/v1.php/cloud/user policy=ocis prefix=/ocs/ routeType=prefix service=proxy
2022-10-25T09:16:57Z DBG discovered jwks endpoint jwks=https://auth.example.com/api/oidc/jwks service=proxy
2022-10-25T09:16:57Z DBG discovered jwks endpoint jwks=https://auth.example.com/api/oidc/jwks service=proxy
2022-10-25T09:16:57Z DBG parsed access token access token={} service=proxy
2022-10-25T09:16:57Z INF Failed to parse/verify the access token. error="token contains an invalid number of segments" service=proxy
2022-10-25T09:16:57Z ERR failed to authenticate the request error="failed to verify access token: token contains an invalid number of segments" authenticator=oidc path=/ocs/v1.php/cloud/user service=proxy
2022-10-25T09:16:57Z INF access-log bytes=0 duration=226.81491 method=GET path=/ocs/v1.php/cloud/user proto=HTTP/1.1 remote-addr=124.64.22.8 request=74ea8864-e233-4515-9d72-41de4eda3d8e service=proxy status=401
```
6. I'm redirected back to OAuth provider's consent page, rinse and repeat.

## Additional context

This is the response of `https://auth.example.com/api/oidc/jwks`:
```json
{
    "keys": [
        {
            "use": "sig",
            "kty": "RSA",
            "kid": "56b5d8",
            "alg": "RS256",
            "n": "xC1sgbJMiMmDN-V7J1p638mYRfQfcQvO2OcbKf_xpqGkUvXVr2ruGt_9HIVsNyTZaMAsR5oZ--Te23WiNxiEX4l56BvqNAnkDVjTSS06tV2c1VNaXSU-4aTjbHLvMZ4ITeZsnHNOLmU1Wwnxez6B_-tFJfy3o0qik7dZFdP4inwtvJxQKUD5_O04W5a2GgWuypnhpAl189qdpwY9eM6dB-1blgOtgQglk5BGiAybNVExSlUYzQnoNnztr2L7Fyu4t9EeIE9iFLf2c7Upb5c3vOchc8fDHHmt45zLQgS772PK7ViL9HpK2pgkJPzctDrLm0au0FmoyjeB42mxm-flRw",
            "e": "AQAB"
        }
    ]
}
```

Authelia client config for OCIS:
```yml
      - id: owncloud   
        description: Owncloud           
        # Public client don't need a secret
        # secret:     
        ## Sets the client to public. This should typically not be set, please see the documentation for usage.
        public: true
        authorization_policy: one_factor
        pre_configured_consent_duration: 1w
        # audience: []
        scopes:       
          - openid                                                 
          - groups
          - email
          - profile                    
        redirect_uris:     
          - https://owncloud.example.com/oidc-callback.html
        userinfo_signing_algorithm: RS256
```

Relevant Authelia logs:
```
authelia  | time="2022-10-25T17:16:52+08:00" level=debug msg="Authorization Request with id '476c802a-4900-406e-b67b-737fddafc330' on client wit
h id 'owncloud' was successfully processed, proceeding to build Authorization Response" method=GET path=/api/oidc/authorization remote_ip=124.64
.22.8                                                                                                                                          
authelia  | time="2022-10-25T17:16:52+08:00" level=trace msg="Authorization Request with id '476c802a-4900-406e-b67b-737fddafc330' on client wit
h id 'owncloud' creating session for Authorization Response for subject 'xxx' with username 'xxx' with claims: &{JTI: Issuer:https
://auth.example.com Subject:xxx Audience:[owncloud] Nonce: ExpiresAt:0001-01-01 00:00:00 +0000 UTC IssuedAt:2022-10-25 17:16:52.455468
93 +0800 CST m=+4316624.097382776 RequestedAt:2022-10-25 17:04:56 +0800 CST AuthTime:2022-09-29 17:18:54 +0800 CST AccessTokenHash: Authenticati
onContextClassReference: AuthenticationMethodsReferences:[] CodeHash: Extra:map[email:xxx@xxx.xxx email_verified:true name:
 Zhu preferred_username:xxx]}" method=GET path=/api/oidc/authorization remote_ip=xxx                                             
authelia  | time="2022-10-25T17:16:52+08:00" level=trace msg="Authorization Request with id '476c802a-4900-406e-b67b-737fddafc330' on client wit
h id 'owncloud' creating session for Authorization Response for subject 'xxx' with username 'xxx' with headers: &{Extra:map[kid:56
b5d8]}" method=GET path=/api/oidc/authorization remote_ip=124.64.22.8       
```
