### ISSUE TITLE
Process for auto-documenting OCIS_ (global scope) env vars

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#4916]
Similar to have a documention process for env vars for services, we need a process documenting ALL OCIS_env vars as they have by design a global scope. One of the challenging issues is, that there are OCIS_ env vars which are not mentioned in any service and therefore not visible in any documentation. This documentation is necessary as else the purpose of those global envs gets lost and no overview is present.

There was already an intense discussion with @dragonchaser @wkloucek including a solution proposal that not only would work for the ocis and the docs-ocis repo, but also being future proof.

This issue is necessary to have the requirement documented and as a reference of the upcoming solution.

@micbar fyi

**Comment by dragonchaser** [comment]
**Proposal workflow:**

Scan code => Generate a yaml with the variables and its type but leave the description empty => Descriptions are manually filled by the docs team => generate adoc template for consumption

With every subsequent run the generated yaml from the previous run is consumed beforehand, existing variables in that yaml are not updates, because they have already been edited by the docs team.

**Proposal yaml structure:**

```yaml
variables:
  - ocis_url:
      name: "OCIS_URL"
      type: "string"
      default: "some_default"
      description: "Base ocis URL"
      dependend_services:
        - service_a:
            path: "filepath"
        - service_b:
            path: "filepath"
  - ocis_idp_url:
      name: "OCIS_IDP_URL"
      type: "string"
      default: "some_default"
      description: ""
```
