### ISSUE TITLE
fatal could not initialize service handler | service=store error=no such device

### ISSUE THREAD

**Issue by C8opmBM** [owncloud/ocis#5035]
No matter the permissions, I always end up with this error

`fatal could not initialize service handler | service=store error=no such device`
I set the log to debug, everything is perfect, just this last line kills the container.
Any suggestions?

Thank you!

**Comment by C8opmBM** [comment]
Hello.
Yes, oCIS is running in a container. I use the latest tag.

This is my barebone ocis docker compose snippet:

```
[...]
  ocis:
    image: owncloud/ocis:latest
    container_name: ocis
    entrypoint:
      - /bin/sh
    command: ["-c", "ocis init || true; ocis server"]
    environment:      
      - PROXY_TLS=false
      - OCIS_INSECURE=true
      - OCIS_URL=https://localhost:9200
      - OCIS_LOG_LEVEL=debug
      - IDM_CREATE_DEMO_USERS=false
    networks:
      - ocis
    ports:
      - 9200:9200
    volumes:
      # mount the ocis config file inside the container
      - /srv/dev-disk-by-label-media/mediatools/ocis-config:/etc/ocis
      - /srv/mergerfs/pool/ocis-data:/var/lib/ocis
    logging:
      driver: local
[...]
```
