### ISSUE TITLE
OC-FileId missing in COPY operation response

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ocis#5039]
## Describe the bug

Android client expects the `OC-FileId` header in the response of the `COPY` operation. 

## Steps to reproduce

1. Using Android client, copy a single file to another location. Or using the `curl` command:

```
curl -k -u admin:admin -H 'User-Agent:Mozilla/5.0 (Android) ownCloud-android/3.0-beta.2' -H 'Destination:https://xx.xx.xx.xx:9200/remote.php/dav/files/admin/A/1.txt'  -X COPY https://xx.xx.xx.xx:9200/remote.php/dav/files/admin/1.txt
```

## Expected behavior

`OC-FileId` header returned in response with the file ID

## Actual behavior

File is correctly copied, but the lack of `OC-FileId` header in response makes the Android client to display an ugly error. oC10 returns such header.

## Setup

Please describe how you started the server and provide a list of relevant environment variables or configuration files.

Container created with the following docker-compose file:

```
version: "3.7"

services:
  ocis:
    image: owncloud/ocis:2.0.0-rc.1
    ports:
      - 9200:9200
      - 9215:9215
    environment:
      OCIS_INSECURE: "true"
      OCIS_URL: "https://xx.xx.xx.xx:9200"
      IDM_CREATE_DEMO_USERS: "true"
      IDM_ADMIN_PASSWORD: "admin"
      PROXY_ENABLE_BASIC_AUTH: "true"
    restart: "no"
    entrypoint:
      - /bin/sh
    # run ocis init to initialize a configuration file with random secrets
    # it will fail on subsequent runs, because the config file already exists
    # therefore we ignore the error and then start the ocis server
    command: ["-c", "ocis init || true; ocis server"]
```
