### ISSUE TITLE
[helm/k8s] Creating public link and doing any operation on it gives error message but the operation is successful - RC2

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/ocis#5147]
## Describe the bug

Creating public link and doing any operation on it gives error message but the operation is successful

## Steps to reproduce

1. As user `einstein` create a folder `New folder`
2. As user `einstein` create a public link to the folder

## Expected behavior
The public link should be created 

## Actual behavior
An error message along with a success message is shown and the link is created but is displayed only after reload. This happens with every operation involving public link like changing role, deleting the link

https://user-images.githubusercontent.com/41103328/204470635-50fe243b-0d81-41c3-bfdd-7bdd0ad44e33.mp4

## Setup

Set-up using the documentation https://doc.owncloud.com/ocis/next/deployment/container/orchestration/orchestration.html#kubernetes
ocis image used: `owncloud/ocis:2.0.0-rc.2` 
Basic auth: enabled

**Comment by saw-jan** [comment]
@SwikritiT  I couldn't reproduce this one on my K8s deployment.

**Comment by saw-jan** [comment]
Need to update the ocis-chart.

Try again with these changes:

```yml
# charts/ocis/templates/storage-users/deployment.yaml

env:
  - name: STORAGE_USERS_MOUNT_ID
    value: 1284d238-aa92-42ce-bdc4-0b0000009157

```
```yml
# charts/ocis/templates/gateway/deployment.yaml

env:
  - name: GATEWAY_STORAGE_USERS_MOUNT_ID
    value: 1284d238-aa92-42ce-bdc4-0b0000009157
```
