### ISSUE TITLE
Docker on Windows - Bind storage to host folder

### ISSUE THREAD

**Issue by cascaabreu** [owncloud/ocis#5247]
## Describe the bug

Binding **/var/lib/ocis** to any host folder results in missing files.
Files lacking any extension are translated to folders in Windows filesystem.

## Steps to reproduce

1. Running Docker on Windows through WSL2.

2. docker-compose

```
version: "3.7"
services:
  ocis:
    container_name: owncloud
    image: owncloud/ocis:latest
    restart: unless-stopped
    ports:
      - 9200:9200
    entrypoint:
      - /bin/sh
    command: ["-c", "ocis init || true; ocis server"]
    environment:
      OCIS_URL: "https://domain.com"
      PROXY_TLS: "false"
      OCIS_INSECURE: "false"
      OCIS_LOG_LEVEL: error
    volumes:
      - ./config:/etc/ocis
      - ./data:/var/lib/ocis
```

## Expected behavior
Running without issues even with **/var/lib/ocis** mounted inside Windows filesystem.

## Actual behavior
Binding **/var/lib/ocis** to any host folder leads ocis into a loop after login.
The same docker compose without mounting **/var/lib/ocis** to the host filesystem, enables ocis to run without issues.
