### ISSUE TITLE
Error setting up OCIS with Azure

### ISSUE THREAD

**Issue by J-Light** [owncloud/ocis#5324]
## Describe the bug

I am attempting to configure OCIS with Azure AD as the IDP. However, I am experiencing some issues which I have not yet been able to resolve. When OpenID is not configured with Azure, the setup works as expected using the build-in solution. When it is configured with Azure, I receive the following errors:

In the browser:
Network reports:
`GET https://[redacted]/ocs/v1.php/cloud/user  401 Unauthorized`

Console reports:
`Uncaught TypeError: Invalid character in header field name    vendor-b942fdc1.mjs:40:79848`

The server logging reports:
```JSON
{"level":"info","service":"proxy","error":"crypto/rsa: verification error","time":"2023-01-04T10:43:02.037524822Z","message":"Failed to parse/verify the access token."}
{"level":"error","service":"proxy","error":"failed to verify access token: crypto/rsa: verification error","authenticator":"oidc","path":"/ocs/v1.php/cloud/user","time":"2023-01-04T10:43:02.037747718Z","message":"failed to authenticate the request"}
{"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"cff4a139-e1d2-4222-a5d3-7111cd81f812","remote-addr":"[redacted]","method":"GET","status":401,"path":"/ocs/v1.php/cloud/user","duration":124.337058,"bytes":0,"time":"2023-01-04T10:43:02.037878812Z","message":"access-log"}
```
My Docker Compose is as follows:
```YAML
services:
  traefik:
    image: traefik:latest
    networks:
      ocis-net:
    command:
      - "--log.level=ERROR"
      - "--certificatesResolvers.http.acme.email=[redacted]"
      - "--certificatesResolvers.http.acme.storage=/certs/acme.json"
      - "--certificatesResolvers.http.acme.httpChallenge.entryPoint=http"
      - "--api.dashboard=true"
      - "--entryPoints.http.address=:80"
      - "--entryPoints.http.http.redirections.entryPoint.to=https"
      - "--entryPoints.http.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.https.address=:443"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--accessLog=true"
      - "--accessLog.fields.headers.names.X-Request-Id=keep"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certs:/certs:rw"
    labels:
      - "traefik.enable=false"
    logging:
      driver: local

  ocis:
    image: owncloud/ocis:latest
    depends_on:
      - traefik
    ports:
      - 9200:9200
    networks:
      ocis-net:
    environment:
      OCIS_URL: https://[redacted]
      OCIS_LOG_LEVEL: info
      PROXY_TLS: false
      OCIS_INSECURE: false
      STORAGE_USERS_DRIVER: s3ng
      STORAGE_SYSTEM_DRIVER: ocis
      STORAGE_USERS_S3NG_ENDPOINT: https://[redacted]
      STORAGE_USERS_S3NG_REGION: [redacted]
      STORAGE_USERS_S3NG_ACCESS_KEY: [redacted]
      STORAGE_USERS_S3NG_SECRET_KEY: [redacted]
      STORAGE_USERS_S3NG_BUCKET: [redacted]
      OCIS_OIDC_ISSUER: https://login.microsoftonline.com/[redacted]
      PROXY_OIDC_REWRITE_WELLKNOWN: false
      WEB_OIDC_CLIENT_ID: [redacted]
      IDM_ADMIN_PASSWORD: [redacted]
    volumes:
      - ./config:/etc/ocis
      - ./data:/var/lib/ocis
    labels:
      - "traefik.http.routers.ocis.entrypoints=https"
      - "traefik.http.routers.ocis.rule=Host(`[redacted]`)"
      - "traefik.http.routers.ocis.tls.certresolver=http"
      - "traefik.http.routers.ocis.service=ocis"
      - "traefik.http.services.ocis.loadbalancer.server.port=9200"
    logging:
      driver: local

networks:
  ocis-net:
```
## Steps to reproduce

1. Setup a container based deployment as per documentation
2. Register a new App in Azure for an SPA
3. Update docker-compose.yaml shown here with Client ID and Authority information in ocis service. 
4. Start the services

## Expected behavior
Application should allow authenticated users to login. 

## Actual behavior
Error in client and server.
