### ISSUE TITLE
CORS policy while getting token information from Keycloak 

### ISSUE THREAD

**Issue by PlayerBerny12** [owncloud/ocis#5466]
## Describe the bug

I am trying to create my internal owncloud ocis instance with keycloak and nginx revers proxy infront of it all. Owncloud is corectlly redirecting me to keycloak and after login, it tries to get token information but it fails on CORS policy as you can see from browser log.

![owncloud_cors](https://user-images.githubusercontent.com/34273914/215058494-b51ccc98-dfa5-4075-9a6a-bae586772e45.png)

I am not sure if this is a problem of owncloud or configuration of my nginx revers proxy. If I turn off cors policy in browser it is working as expected.

## Setup

Docker compose for owncloud:
```
version: "3"
services:
  owncloud:
    image: owncloud/ocis:latest
    restart: always
    hostname: owncloud
    container_name: owncloud
    entrypoint:
      - /bin/sh
    command: ["-c", "ocis init || true; ocis server"]
    environment:
      PROXY_AUTOPROVISION_ACCOUNTS: true
      OCIS_OIDC_ISSUER: https://keycloak.xxx.cz/realms/master
      PROXY_OIDC_REWRITE_WELLKNOWN: true
      WEB_OIDC_CLIENT_ID: owncloud
      OCIS_URL: https://owncloud.xxx.cz
      OCIS_LOG_LEVEL: INFO
      PROXY_TLS: false
      OCIS_INSECURE: true
    volumes:
      - /srv/owncloud/config:/etc/ocis
      - /srv/owncloud/data:/var/lib/ocis
    networks:
      - nginx-network
networks:
    nginx-network:
      name: nginx-network
      external: true
```

Nginx revers proxy configuration:
```
# Number of process
worker_processes 4;

# Number of connections for one process
events { worker_connections 1024; }

http {
    sendfile on;

    # Redirect http to https
    server {
        listen 80 default_server;
        server_name _;

        return 301 https://$host$request_uri;
    }
    # Keycloak
    server {
        listen 443 ssl;
        server_name keycloak.xxx.cz;

        ssl_certificate /srv/nginx/keycloak.crt;
        ssl_certificate_key /srv/nginx/keycloak.key;

        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
            proxy_pass http://keycloak:8080;

            proxy_buffer_size 8k;
        }
    }
    # Owncloud
    server {
        listen 443 ssl;
        server_name owncloud.xxx.cz;

        ssl_certificate /srv/nginx/owncloud.crt;
        ssl_certificate_key /srv/nginx/owncloud.key;

        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
            proxy_pass http://owncloud:9200;

           client_max_body_size 5000m;
        }
    }
}
```

## Additional context
Nginx and keycloak is each running in its own container and they are connected throught `nginx-network`.
