### ISSUE TITLE
Allow to configure GOMEMLIMIT / automatically set GOMEMLIMIT according cgroups

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#5713]
## Is your feature request related to a problem? Please describe.
In Kubernetes I want to set resource limits:

```yaml
resources:
  limits:
    memory: 10G
  requests:
    cpu: "3"
    memory: 10G
```

I could then set the GOMEMLIMIT like this with the downwards API:

```yaml
env:
  - name: GOMEMLIMIT
    valueFrom:
      resourceFieldRef:
        resource: limits.memory
        divisor: "1Mi"
```

But this is not recommended, because you should set GOMEMLIMIT to 90% of the available memory. This is currently not possible with the downwards API.

Therefore it would be nice, if oCIS would automatically configure it (whenever possible).

A POC is done in #4856
