### ISSUE TITLE
Cannot add group to Space

### ISSUE THREAD

**Issue by functioneer** [owncloud/ocis#5804]
## Describe the bug

The Help (i) pop-up says "Enter a name to add people or groups as members to this Space.".  But when we entered the Group name in the Add members search box, it didn't appear and so we could not add the group to the Space.  Could only add members and not groups.

## Steps to reproduce

1.   Create a Group and add members to it.
2.   Create a Space
3.   Click on Show Members of the Space and enter the Group name in the Add members search box.  

## Expected behavior
We expected to be able to add groups to a Space as stated in the Information/Help button pop-up.

## Actual behavior
The Add members search box could not find the group.

## Setup

Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```
systemctl edit --force --full ocis.service
[Unit]
Description=OCIS server

[Service]
Type=simple
User=ocis
Group=ocis
EnvironmentFile=/etc/ocis/ocis.env
ExecStart=/usr/local/bin/ocis server
Restart=always

[Install]
WantedBy=multi-user.target

ADMIN_PASSWORD=mypassword ocis init --config-path /etc/ocis

cat /etc/ocis/ocis.env
OCIS_INSECURE=true
OCIS_URL=https://ocis.mydomain.com:9200
PROXY_HTTP_ADDR=0.0.0.0:9200
IDM_CREATE_DEMO_USERS=true
OCIS_LOG_LEVEL=error
OCIS_CONFIG_DIR=/etc/ocis
OCIS_BASE_DATA_PATH=/var/ocis

cat /etc/ocis/ocis.yaml
token_manager:
  jwt_secret: xxxx
machine_auth_api_key: xxxx
system_user_api_key: xxxx
transfer_secret: =xxxx
system_user_id: xxxx
admin_user_id: xxxx
graph:
  events:
    tls_insecure: true
  spaces:
    insecure: true
  identity:
    ldap:
      bind_password: xxxx
idp:
  ldap:
    bind_password: xxxx
idm:
  service_user_passwords:
    admin_password: mypassword
    idm_password: xxxx
    reva_password: xxxx
    idp_password: xxxx
proxy:
  oidc:
    insecure: true
  insecure_backends: true
frontend:
  archiver:
    insecure: true
auth_basic:
  auth_providers:
    ldap:
      bind_password: xxxx
auth_bearer:
  auth_providers:
    oidc:
      insecure: true
users:
  drivers:
    ldap:
      bind_password: xxxx
groups:
  drivers:
    ldap:
      bind_password: xxxx
ocdav:
  insecure: true
thumbnails:
  thumbnail:
    transfer_secret: xxxx
    webdav_allow_insecure: true
    cs3_allow_insecure: true
search:
  events:
    tls_insecure: true
audit:
  events:
    tls_insecure: true
sharing:
  events:
    tls_insecure: true
storage_users:
  events:
    tls_insecure: true
  mount_id: xxxx
notifications:
  notifications:
    SMTP:
      smtp_host: smtp-relay.gmail.com
      smtp_port: 587
      smtp_sender: admin <it@mydomain.com>
      smtp_username: myusername@mydomain.com
      smtp_password: my_google_ws_app_password
      insecure: false
      smtp_authentication: login
      smtp_encryption: starttls
    events:
      endpoint: 127.0.0.1:9233
      cluster: ocis-cluster
      group: notifications
      tls_insecure: false
      enable_tls: false
    reva_gateway: 127.0.0.1:9142
    grpc_client_tls: null
nats:
  nats:
    tls_skip_verify_client_cert: true
gateway:
  storage_registry:
    storage_users_mount_id: xxxx


```

</p>
</details>

## Additional context
Note we added the smtp server settings to the ocis.yaml file.  But the add group to Space problem was already there before we added the smtp server settings to the ocis.yaml file.  

Thank you very much in anticipation
