### ISSUE TITLE
Install Blocked: "could not initialize oidcAuth provider" with default setup due to wrong server name in default certificate

### ISSUE THREAD

**Issue by MeachamusPrime** [owncloud/ocis#6192]
## Describe the bug
![image](https://user-images.githubusercontent.com/8473707/235327606-de59cf62-6101-4229-8230-e5b265e9e401.png)
First time login with default admin setup from ocis init leads to the above holding forever. I have attached the specific server side error message in [addition context](#additional-context) below. Note that the error message complains of the certificate being valid for localhost and not the configured OCI_URL.

## Steps to reproduce

1. export MICRO_REGISTRY=etcd
2.
```
PROXY_HTTP_ADDR=0.0.0.0:9200 \
OCIS_URL=https://rasberrypi:9200 \
KONNECTD_TLS=0 \
./ocis-2.0.0-linux-arm init
```
3. Record `admin` password
4. 
```
PROXY_HTTP_ADDR=0.0.0.0:9200 \
OCIS_URL=https://rasberrypi:9200 \
KONNECTD_TLS=0 \
./ocis-2.0.0-linux-arm server
```
5. Navigate to `https://rasberrypi:9200`
6. Login using `admin` and the recorded password

## Expected behavior
Successful login with an owncloud that is ready to setup

## Actual behavior
The above image forever with the below error message

## Setup
```
sudo cat ~/.ocis/idp/tmp/identifier-registration.yaml
clients:
- id: web
  name: ownCloud Web app
  trusted: true
  secret: ""
  redirect_uris:
  - https://rasberrypi:9200/
  - https://rasberrypi:9200/oidc-callback.html
  - https://rasberrypi:9200/oidc-silent-redirect.html
  origins:
  - https://rasberrypi:9200
  application_type: ""
- id: <id>
  name: ownCloud desktop app
  trusted: false
  secret: <secret>
  redirect_uris:
  - http://127.0.0.1
  - http://localhost
  origins: []
  application_type: native
- id: <id>
  name: ownCloud Android app
  trusted: false
  secret: <secret>
  redirect_uris:
  - oc://android.owncloud.com
  origins: []
  application_type: native
- id: <id>
  name: ownCloud iOS app
  trusted: false
  secret: <secret>
  redirect_uris:
  - oc://ios.owncloud.com
  - oc.ios://ios.owncloud.com
  origins: []
  application_type: native
```
All options in `~/.ocis/config/ocis.yaml` are set to false.

## Additional context
```
2023/04/30 00:04:10 http: TLS handshake error from 127.0.0.1:41124: remote error: tls: bad certificate
{"level":"error","service":"proxy","error":"Get \"https://rasberrypi:9200/.well-known/openid-configuration\": x509: certificate is valid for localhost, localhost, not rasberrypi","time":"2023-04-30T00:04:10.143725595+01:00","message":"could not initialize oidcAuth provider"}
```
