### ISSUE TITLE
How to run in HTTP mode?

### ISSUE THREAD

**Issue by doums** [owncloud/ocis#6302]
## Describe the bug

Hi, I'm trying to setup an ocis instance using docker. Once the container start, when I try to login to the web UI with the generated admin credentials, I get an `internal server error 500`.

Note that I'm inside a private network, where the server that runs the container has the following hostname `loup` (which is correctly resolved by private DNS). I try to connect to the web UI from another machine (a PC) also located on that private network. \
I don't use any reverse proxy (with TLS enabled) because it's intended to be only accessible inside my private network.

`http(s)://loup:9200` is the correct URL to access the web UI (inside my private network).

#### First issue

1. if I set  `PROXY_TLS` to `false`, when I open the webUI using `http://loup:9200` the page opens, blue background, spinner spinning and I get a CORS error. It seems the cors `OPTION` preflight request fails with `CORS Failed`.
2. with  `PROXY_TLS` to `true`, `https://loup:9200` the login page opens correctly, no CORS error but if I try to login with the fresh generated admin credential (taken from the logs), the `/signin/v1/identifier/_/logon` request fails with `internal server error 500`

logs
```
=========================================
 generated OCIS Config
=========================================
 configpath : /etc/ocis/ocis.yaml
 user       : admin
 password   : h*9tUcj1&hCPLP&.+eO^5&FyCEM&0gwJ

{"level":"warn","service":"storage-system","pkg":"rhttp","time":"2023-05-13T17:04:11.747797359Z","message":"missing or incomplete nats configuration. Events will not be published."}
{"level":"error","service":"idm","bind_dn":"uid=libregraph,ou=sysusers,o=libregraph-idm","op":"bind","remote_addr":"127.0.0.1:47394","time":"2023-05-13T17:04:12.43028311Z","message":"invalid credentials"}
{"level":"error","service":"graph","error":"LDAP Result Code 49 \"Invalid Credentials\": ","time":"2023-05-13T17:04:12.430385909Z","message":"Bind failed"}
{"level":"error","service":"graph","error":"LDAP Result Code 49 \"Invalid Credentials\": ","time":"2023-05-13T17:04:12.430468609Z","message":"autoconnect could not get ldap Connection"}
{"level":"warn","service":"proxy","time":"2023-05-13T17:04:12.748727332Z","message":"No tls certificate provided, using a generated one"}
{"level":"warn","service":"idp","kid":"private-key","path":"/var/lib/ocis/idp/private-key.pem","time":"2023-05-13T17:04:12.751351845Z","message":"skipped as signer with same kid already loaded"}
{"level":"error","service":"idm","bind_dn":"uid=idp,ou=sysusers,o=libregraph-idm","op":"bind","remote_addr":"127.0.0.1:34820","time":"2023-05-13T17:04:28.817175336Z","message":"invalid credentials"}
{"level":"error","service":"idp","error":"ldap identifier backend logon connect error: LDAP Result Code 49 \"Invalid Credentials\": ","time":"2023-05-13T17:04:28.817426667Z","message":"identifier failed to logo
n with backend"}
```

#### Second issue:

the HTTP**S** of the public URL seems required, as setting `OCIS_URL` to `http://loup..` make ocis instance crash
```
{"level":"fatal","service":"idp","error":"invalid iss value, URL must start with https://","time":"2023-05-13T16:52:49.129067655Z","message":"could not bootstrap idp"}
```
But in my case, I don't need TLS as I explained. There is way to force ocis to comply with HTTP only? 

####  `compose.yml` 

```
services:
  ocis:
    image: owncloud/ocis:latest
    container_name: ocis
    restart: unless-stopped
    user: 1000:1000 # the host user
    environment:
      OCIS_CONFIG_DIR: /etc/ocis/
      OCIS_BASE_DATA_PATH: /var/lib/ocis
      STORAGE_USERS_DRIVER: ocis # use POSIX FS driver
      OCIS_URL: https://loup:9200
      PROXY_HTTP_ADDR: 0.0.0.0:9200
      OCIS_INSECURE: true
      OCIS_LOG_LEVEL: warn
      OCIS_LOG_COLOR: false
      PROXY_TLS: true
    ports:
      - "9200:9200"
    volumes:
      - ./config:/etc/ocis
      - /box/files:/var/lib/ocis
    entrypoint:
      - /bin/sh
    command: ["-c", "ocis init || true; ocis server"]
```
