### ISSUE TITLE
Error when using the local/localhome storage driver

### ISSUE THREAD

**Issue by MrPixel1** [owncloud/ocis#6330]
## Describe the bug

When using the "local" or "localhome" storage driver, an error occurs and logged in users can't upload files.

The following error occurs a few times in the log:

`ERR failed to list storage spaces error="error: not supported: list storage spaces" filters=[{"Term":{"SpaceType":"project"},"type":4},{"Term":{"User":{"idp":"https://...","opaque_id":"26996839-94fc-4158-a7b6-fb00e1d20f92"}},"type":6}] line=github.com/cs3org/reva/v2@v2.13.2/internal/grpc/services/storageprovider/storageprovider.go:554 pkg=rgrpc service=storage-users status={"code":14,"message":"not implemented","trace":"00000000000000000000000000000000"} traceid=00000000000000000000000000000000`

## Steps to reproduce

1. Configure the environment variable `- "STORAGE_USERS_DRIVER=local"` or `- "STORAGE_USERS_DRIVER=localhome"` in the docker-compose.yml file.
2. Log in using the web UI.

## Expected behavior

After logging in, the user should be able to upload files. No error should appear in the log.

## Actual behavior

An error is repeated in the logs and the user can't upload files.

## Setup

Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```yml
services:
  app:
    image: owncloud/ocis:3.0.0-rc.3
    container_name: ocis
    environment:
      - "OCIS_URL=https://..."
      - "OCIS_LOG_FILE=/dev/stdout"
      - "OCIS_LOG_PRETTY=true"
      - "OCIS_LOG_LEVEL=info"
      - "OCIS_LOG_COLOR=true"
      - "PROXY_HTTP_ADDR=172.100.0.3:9200"
      - "PROXY_TLS=false"
      - "OCIS_INSECURE=true"
      - "PROXY_OIDC_INSECURE=true"
      - "PROXY_ENABLE_BASIC_AUTH=false"
      - "IDM_ADMIN_PASSWORD=..."
      - "IDM_CREATE_DEMO_USERS=false"
      - "PROXY_AUTOPROVISION_ACCOUNTS=true"
      - "OCIS_OIDC_ISSUER=https://..."
      - "PROXY_OIDC_REWRITE_WELLKNOWN=true"
      - "WEB_OIDC_CLIENT_ID=ocis-web"
      - "PROXY_OIDC_ACCESS_TOKEN_VERIFY_METHOD=none"
      - "STORAGE_USERS_DRIVER=local"
    ports:
      - "9200:9200"
    volumes:
      - "./persistent/config:/etc/ocis"
      - "./persistent/data:/var/lib/ocis"
    entrypoint: ["/bin/sh"]
    command: ["-c", "ocis init || true; ocis server"]
    user: "1000:1000"
    restart: unless-stopped
```

</p>
</details>

## Additional context

The use case behind using the local/localhome driver is to have the directories and files stored as-is on the filesystem instead of blobs (decomposed fs).
