### ISSUE TITLE
Unable to connect with the admin user

### ISSUE THREAD

**Issue by doums** [owncloud/ocis#6357]
## Describe the bug

Hi, I'm still trying to setup an ocis instance through docker (terrible and painful experience so far).
Once the container start, when I try to login to the web UI with the generated admin credentials, the following error is logged and I get redirected to "You were automatically logged out for security reasons."

```
{"level":"error","service":"proxy","error":"failed to verify access token: Get \"https://files.local.lan/.well-known/openid-configuration\": dial tcp: lookup files.local.lan on 127.0.0.11:53: no such host","authenticator":"oidc","path":"/api/v0/settings/values-list","time":"2023-05-21T22:25:36.416400738Z","message":"failed to authenticate the request"}
{"level":"warn","service":"frontend","pkg":"rhttp","traceid":"00000000000000000000000000000000","time":"2023-05-21T22:25:36.433181246Z","message":"core access token not set"}
{"level":"error","service":"proxy","error":"failed to verify access token: Get \"https://files.local.lan/.well-known/openid-configuration\": dial tcp: lookup files.local.lan on 127.0.0.11:53: no such host","authenticator":"oidc","path":"/ocs/v1.php/cloud/user","time":"2023-05-21T22:25:36.439403945Z","message":"failed to authenticate the request"}
```

**Note**: I use a reverse proxy which handle HTTPS (caddy) using a fake private local domain `files.local.lan` for my home network.

#### container startup logs

```
=========================================
 generated OCIS Config
=========================================
 configpath : /etc/ocis/ocis.yaml
 user       : admin
 password   : xxxxxx

{"level":"warn","service":"storage-system","pkg":"rhttp","time":"2023-05-21T21:11:23.3938579Z","message":"missing or incomplete nats configuration. Events will not be pu
blished."}
{"level":"info","time":"2023-05-21T21:11:23.397226782Z","caller":"github.com/cs3org/reva/v2@v2.13.3-0.20230510083816-98d8707dea33/pkg/storage/utils/decomposedfs/migrator
/0001_create_spaces_directory_structure.go:33","message":"Migrating spaces directory structure..."}
{"level":"info","time":"2023-05-21T21:11:23.397344248Z","caller":"github.com/cs3org/reva/v2@v2.13.3-0.20230510083816-98d8707dea33/pkg/storage/utils/decomposedfs/migrator
/0002_move_spacetypes_to_indexes.go:31","message":"Migrating space types indexes..."}
{"level":"info","root":"/var/lib/ocis/storage/metadata","time":"2023-05-21T21:11:23.397456103Z","caller":"github.com/cs3org/reva/v2@v2.13.3-0.20230510083816-98d8707dea33
/pkg/storage/utils/decomposedfs/migrator/0003_switch_to_messagepack_metadata.go:45","message":"Migrating to messagepack metadata backend..."}
{"level":"info","time":"2023-05-21T21:11:23.397527107Z","caller":"github.com/cs3org/reva/v2@v2.13.3-0.20230510083816-98d8707dea33/pkg/storage/utils/decomposedfs/migrator
/0003_switch_to_messagepack_metadata.go:106","message":"done."}
{"level":"info","time":"2023-05-21T21:11:24.249125296Z","caller":"github.com/cs3org/reva/v2@v2.13.3-0.20230510083816-98d8707dea33/pkg/storage/utils/decomposedfs/migrator
/0001_create_spaces_directory_structure.go:33","message":"Migrating spaces directory structure..."}
{"level":"info","time":"2023-05-21T21:11:24.249201339Z","caller":"github.com/cs3org/reva/v2@v2.13.3-0.20230510083816-98d8707dea33/pkg/storage/utils/decomposedfs/migrator
/0002_move_spacetypes_to_indexes.go:31","message":"Migrating space types indexes..."}
{"level":"warn","service":"users","LDAP CACert":"/var/lib/ocis/idm/ldap.crt","time":"2023-05-21T21:11:25.39079298Z","message":"CA cert file is not ready yet. Waiting 2 s
econds for it to appear."}
{"level":"warn","service":"groups","LDAP CACert":"/var/lib/ocis/idm/ldap.crt","time":"2023-05-21T21:11:25.390960882Z","message":"CA cert file is not ready yet. Waiting 2
 seconds for it to appear."}
{"level":"warn","service":"auth-basic","LDAP CACert":"/var/lib/ocis/idm/ldap.crt","time":"2023-05-21T21:11:25.392952866Z","message":"CA cert file is not ready yet. Waiti
ng 2 seconds for it to appear."}
{"level":"warn","service":"idp","kid":"private-key","path":"/var/lib/ocis/idp/private-key.pem","time":"2023-05-21T21:11:25.83158663Z","message":"skipped as signer with s
ame kid already loaded"}
```

####  `compose.yml` 

```
services:
  ocis:
    image: owncloud/ocis:latest
    container_name: ocis
    restart: unless-stopped
    user: 1000:1000 # the host user
    environment:
      OCIS_CONFIG_DIR: /etc/ocis/
      OCIS_BASE_DATA_PATH: /var/lib/ocis
      STORAGE_USERS_DRIVER: ocis # use POSIX FS driver
      OCIS_URL: https://files.local.lan
      PROXY_HTTP_ADDR: 0.0.0.0:9200
      OCIS_INSECURE: false
      PROXY_TLS: false
      OCIS_LOG_LEVEL: warn
      OCIS_LOG_COLOR: false
    ports:
      - "9200:9200"
    volumes:
      - ./config:/etc/ocis
      - /box/files:/var/lib/ocis
    entrypoint:
      - /bin/sh
    command: ["-c", "ocis init || true; ocis server"]
```
