### ISSUE TITLE
Authelia OIDC auth fails with "No roles in user claims" in 3.0.0

### ISSUE THREAD

**Issue by mwinters-stuff** [owncloud/ocis#6474]
## Describe the bug

Using Authelia for OIDC Authentication, Version 2.0.0 allows the users to authenticate, though as authelia's OIDC implementation is not complete, there are no roles in the claim.

Version 3.0.0, has a failure point when there are no roles for the user. This means that upgrading from 2.0.0 to 3.0.0
will break existing systems.

## Steps to reproduce

1. Setup with authelia & traefik (these are hosted in kubernetes with helm/flux)

OICS Ingress and middleware
``` yaml
 apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ocis-test
  namespace: default
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`owncloud.example.nz`) 
      kind: Rule
      middlewares:
        - name: authelia-ocis-remove-parameter
          namespace: default
      services:
        - name: ocis-test-external
          namespace: default
          port: 9200
  tls:
    secretName: winters-org-nz-production-tls

---
apiVersion: v1
kind: Service
metadata:
  name: ocis-test-external
  namespace: default
spec:
  type: ExternalName
  ports:
    - name: http
      port: 9200
      targetPort: 9200
  externalName: 192.168.10.15

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
    name: authelia-ocis-remove-parameter
    namespace: default
spec:
    plugin:
        traefik-plugin-query-modification:
            ParamName: prompt
            Type: delete

```

Authelia Configuration - middleware and OIDC configuration for web (abbreviated from values)

``` yaml
ingress:
  traefikCRD:
    middlewares:
         chains:
              auth:
                  before: []
                  after: []
              ingressRoute:
                  before:
                      - name: authelia-ocis-remove-parameter
                        namespace: default
                  after: []
configMap:
  identity_providers:
      oidc:
          enabled: true
          access_token_lifespan: 1h
          authorize_code_lifespan: 1m
          id_token_lifespan: 1h
          refresh_token_lifespan: 90m
          enforce_pkce: public_clients_only
          enable_pkce_plain_challenge: false
          minimum_parameter_entropy: 8
          enable_client_debug_messages: true
          cors:
              endpoints:
                  - authorization
                  - token
                  - revocation
                  - introspection
                  - userinfo
              allowed_origins: []
              allowed_origins_from_client_redirect_uris: true
          clients:
             - id: ocis-web
                description: ownCloud ocis web client
                public: true
                authorization_policy: two_factor
                userinfo_signing_algorithm: none
                grant_types:
                  - authorization_code
                scopes:
                  - openid
                  - groups
                  - email
                  - profile
                redirect_uris:
                  - https://owncloud.example.nz/
                  - https://owncloud.example.nz/oidc-callback.html
                  - https://owncloud.example.nz/oidc-silent-redirect.html
```

ocis.env (ocis is hosted on its own lxc container for testing purposes)

``` console
OCIS_URL=https://owncloud.example.nz
PROXY_HTTP_ADDR=0.0.0.0:9200
PROXY_TLS=false
OCIS_INSECURE=false

OCIS_LOG_LEVEL=info

OCIS_CONFIG_DIR=/etc/ocis
OCIS_BASE_DATA_PATH=/var/lib/ocis
OCIS_RUN_SERVICES=app-registry,app-provider,audit,auth-basic,auth-machine,frontend,gateway,graph,groups,idm,nats,notifications,ocdav,ocs,proxy,search,settings,sharing,storage-system,storage-publiclink,storage-shares,storage-users,store,thumbnails,users,web,webdav


OCIS_OIDC_ISSUER=https://auth.example.nz
WEB_OIDC_CLIENT_ID=ocis-web
PROXY_OIDC_REWRITE_WELLKNOWN=true
PROXY_OIDC_ACCESS_TOKEN_VERIFY_METHOD=none
PROXY_AUTOPROVISION_ACCOUNTS=true
PROXY_ROLE_ASSIGNMENT_DRIVER=oidc
```

2. Start OCIS and authelia/traefik
3. Attempt to log-in. you will get to verify through authelia then ocis automatically logs you out.
Log message "No roles in user claims".

## Expected behavior
To able to login and use OCIS

## Actual behavior
Unable to login, unable to use OCIS

## Setup

Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

See above:

</p>
</details>

## Additional context

Am able to login using version 2.0.0, the change to handing ocis roles in 3.0.0 "broke" this.

I am creating a pull request with a fix to allow authentication as before.
