### ISSUE TITLE
Too many roles assigned after upgrading to 3.0

### ISSUE THREAD

**Issue by sedadas** [owncloud/ocis#6530]
## Describe the bug

I am using keycloak as an IDP for my OCIS instance and have created the roles:
* ocisAdmin
* ocisUser
* ocisSpaceAdmin

that I'll use to assign permissions. I have added myself to ocisAdmin and attempted to login. OCIS gets the assigned roles, but then returns `"message":"The user has too many roles assigned"`. I checked the keycloak instance and saw that I only had one role assigned. I managed to narrow the issue down to this line here:
https://github.com/owncloud/ocis/blob/3ce2413c8026aa2469dae3399077c693a7f67ab8/services/proxy/pkg/userroles/oidcroles.go#LL91C1-L91C1

I then remembered that previously I have manually set my user id as an admin using `OCIS_ADMIN_USER_ID`, which obviously has saved my admin role in the database. 
Now I am attempting to obtain the admin role again, using the much more cleaner role mapping, but instead I cannot login.

## Steps to reproduce

These were the steps that made it happen on my side:

1. Deploy Keycloak
2. Deploy OCIS 2 and point it to the Keycloak IDP.
3. Set the admin using `OCIS_ADMIN_USER_ID`
4. Upgrade to OCIS 3
5. Attempt to login

## Expected behavior
I expected to login and see my files.

## Actual behavior
I got an access denied page and the log output from above.

## Setup

OCIS is running as a pod in Kubernetes and is using the following config

<details>
<p>

env:
```yaml
env:
    - name: OCIS_URL
      value: <ocisURL>
    - name: WEB_OIDC_CLIENT_ID
      value: oics_web
    - name: OCIS_OIDC_ISSUER
      value: <oidcURL>
    - name: PROXY_OIDC_REWRITE_WELLKNOWN
      value: 'true'
    - name: PROXY_USER_OIDC_CLAIM
      value: 'email'
```

ocis.yaml:

```yaml
    token_manager:
      jwt_secret: redacted
    machine_auth_api_key: redacted
    system_user_api_key: redacted
    transfer_secret: redacted
    system_user_id: redacted
    admin_user_id: redacted
    graph:
      application:
        id: redacted
      events:
        tls_insecure: false
      spaces:
        insecure: false
      identity:
        ldap:
          bind_password: redacted
    idp:
      iss: redacted
      ldap:
        bind_password: redacted
    clients:
      - id: redacted
        name: ownCloud Web app
        trusted: true
        secret: redacted
        redirect_uris:
          - 'ocisURL'
          - 'ocisURL/oidc-callback.html'
          - 'ocisURL/oidc-silent-redirect.html'
        origins:
          - 'ocisURL'
    idm:
      service_user_passwords:
        admin_password: redacted
        idm_password: redacted
        reva_password: redacted
        idp_password: redacted
    proxy:
      oidc:
        insecure: false
      role_assignment:
        driver: oidc
        oidc_role_mapper:
          role_claim: groups
          role_mapping:
            - role_name: admin
              claim_value: ocisAdmin
            - role_name: spaceadmin
              claim_value: ocisSpaceAdmin
            - role_name: user
              claim_value: ocisUser
            - role_name: guest
              claim_value: ocisGuest
      auto_provision_accounts: true
      insecure_backends: true
      http:
        addr: 0.0.0.0:9200
        root: /
        tls: false
    frontend:
      archiver:
        insecure: false
    auth_basic:
      auth_providers:
        ldap:
          bind_password: redacted
    auth_bearer:
      auth_providers:
        oidc:
          insecure: false
    users:
      drivers:
        ldap:
          bind_password: redacted
    groups:
      drivers:
        ldap:
          bind_password: redacted
    ocdav:
      insecure: false
    thumbnails:
      thumbnail:
        transfer_secret: redacted
        webdav_allow_insecure: false
        cs3_allow_insecure: false
    search:
      events:
        tls_insecure: false
    audit:
      events:
        tls_insecure: false
    sharing:
      events:
        tls_insecure: false
    storage_users:
      events:
        tls_insecure: false
      mount_id: 
    notifications:
      notifications:
        events:
          tls_insecure: false
    nats:
      nats:
        tls_skip_verify_client_cert: false
    gateway:
      storage_registry:
        storage_users_mount_id: redacted
```

</p>
</details>
