### ISSUE TITLE
Webfinger configuration templating

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#6546]
## Is your feature request related to a problem? Please describe.
When having a lot instances configured in your Webfinger config and running Webfinger in Kubernetes, you might quite easily reach the ConfigMap size limit of 1MiB (https://kubernetes.io/docs/concepts/configuration/configmap/#:~:text=A%20ConfigMap%20is%20not%20designed,separate%20database%20or%20file%20service.)

This is because the configuration needs to be quite verbose:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: webfinger-config
data:
  webfinger.yaml: |
    ---
    instances:
      - claim: "instancenumber"
        regex: "^0001$"
        href: "https://0001.this-is-my-ocis-domain.test"
      - claim: "instancenumber"
        regex: "^0002$"
        href: "https://0002.this-is-my-ocis-domain.test"
      ...
      ...
      ...
```

## Describe the solution you'd like
An option to use the value of regex capture groups in the href, which would funktion as template.

Therefore we would configure something like that:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: webfinger-config
data:
  webfinger.yaml: |
    ---
    instances:
      - claim: "instancenumber"
        regex: "^[0-9]+$"
        href: "https://{{ <regex-match> }}.this-is-my-ocis-domain.test"
```

## Describe alternatives you've considered
Use multiple ConfigMaps and glue config files together in a init container. But the proposed solution also has the advantage of not need to explicitly configuring all permutations.

## Additional context
none
