### ISSUE TITLE
Unable to connect OnlyOffice/WOPI 3.0.0/3.1.0-beta

### ISSUE THREAD

**Issue by gregflynn** [owncloud/ocis#6926]
## Describe the bug
I'm adapting [the docker-compose example from the docs for WOPI+OnlyOffice](https://github.com/owncloud/ocis/tree/master/deployments/examples/ocis_wopi) and attempted on both 3.0.0 and 3.1.0 after I saw [the docs have been updated already for 3.1.0](https://github.com/owncloud/ocis/commit/a86aba1c4144d54d80fd956ddcb9139518cbfc04) already but am running into two unique errors for each version. As it looks like y'all are on the cusp of 3.1.0, dealer's choice which one we try to fix here.

#### On 3.0.0
- The iframe for onlyoffice is HTTP instead of HTTPS and that causes firefox to block it. I've been scouring my config docs for an errant `http` instead of `https` but I couldn't find any

#### On 3.1.0
- The app-server is unable to communicate with the primary ocis server over the REVA gateway, with identical setting from 3.0.0
- `Jul 31 06:12:38 hexadebian docker[15582]: {"level":"error","pid":1,"error":"172.17.0.1:9142: service not found","time":"2023-07-31T11:12:38.887921466Z","caller":"github.com/cs3org/reva/v2@v2.15.0/internal/grpc/services/appprovider/appprovider.go:128","message":"error registering app provider: could not get gateway client"}`

#### On 3.0.0
- Starting all the containers and try to edit a document in the web ui

#### On 3.1.0
- Start all the containers, check journalctl and see the error in the log after startup of the app-server container

## Expected behavior
Onlyoffice is able to open and edit docs

#### On 3.0.0
iframe fails to load due to insecure content (http)

#### On 3.1.0
app-server fails to register itself with the owncloud server and 

## Setup
Instead of docker-compose, I'm running each container individually with systemd unit files to handle some of the entrypoint override retrying that was done in the docker-compose example. (Originally I was using the go binary instead of docker image but it looks like `server` and `app-server` like to bind to a lot of the same ports)

The service files are slightly abbreviated to just show commands since the rest is just systemd fluff

#### owncloud.service
```
ExecStart=/usr/bin/docker run --name ocis \
    --env-file /home/FOO/deploy/ocis/ocis.env \
    -v /ZFS/owncloud/conf:/etc/ocis \
    -v /ZFS/owncloud/data:/var/lib/ocis \
    -p 9142:9142 \
    -p 3006:3006 \
    owncloud/ocis:3.1.0-beta.1 \
    server
```

#### ocis.env
```env
OCIS_URL=https://cloud.foo.bar
PROXY_HTTP_ADDR=0.0.0.0:3006
PROXY_TLS=false
OCIS_INSECURE=false

OCIS_LOG_LEVEL=warning

GATEWAY_GRPC_ADDR=0.0.0.0:9142
```

#### owncloud-app-onlyoffice.service
```
ExecStart=/usr/bin/docker run --name ocisapp \
    --env-file /home/FOO/deploy/ocis/ocis-app.env \
    -v /ZFS/owncloud/conf:/etc/ocis \
    -p 9164:9164 \
    owncloud/ocis:3.1.0-beta.1 \
    app-provider server
```

#### ocis-app-env
```env
REVA_GATEWAY=172.17.0.1:9142
APP_PROVIDER_GRPC_ADDR=0.0.0.0:9164
APP_PROVIDER_SERVICE_NAME=app-provider-onlyoffice
APP_PROVIDER_EXTERNAL_ADDR=172.17.0.1:9164
APP_PROVIDER_DRIVER=wopi
APP_PROVIDER_WOPI_APP_NAME=OnlyOffice
APP_PROVIDER_WOPI_APP_ICON_URI=https://docs.foo.bar/web-apps/apps/documenteditor/main/resources/img/favicon.ico
APP_PROVIDER_WOPI_APP_URL=https://docs.foo.bar
APP_PROVIDER_WOPI_INSECURE="false"
APP_PROVIDER_WOPI_WOPI_SERVER_EXTERNAL_URL=https://wopi.foo.bar
APP_PROVIDER_WOPI_FOLDER_URL_BASE_URL=https://cloud.foo.bar

OCIS_LOG_LEVEL=warning
```

#### owncloud-wopi.service
```
ExecStart=/usr/bin/docker run --name wopi \
    -p 3008:8080 \
    -v /home/hexie/deploy/ocis/wopi.conf:/etc/wopi/wopiserver.conf:ro \
    -v /home/hexie/deploy/ocis/wopi_secret:/etc/wopi/wopisecret:ro \
    cs3org/wopiserver:v10.1.1
```

#### wopiserver.conf
_heavily abbreviated, can add more upon request_
```conf
# Port where to listen for WOPI requests
port = 8080

# ...

# URL of your WOPI server or your HA proxy in front of it
wopiurl = https://wopi.foo.bar

# URL for direct download of files. The complete URL that is sent
# to clients will include the access_token argument
downloadurl = https://wopi.foo.bar/wopi/iop/download

# ...

[cs3]
# Host and port of the Reva(-like) CS3-compliant GRPC gateway endpoint
revagateway = 172.17.0.1:9142

# Reva/gRPC authentication token expiration time [seconds]
# The default value matches Reva's default
authtokenvalidity = 3600

# SSL certificate check for Reva
sslverify = False
```

#### onlyoffice.service
```
ExecStart=/usr/bin/docker run --name onlyoffice \
    -p 3007:80 \
    -v /home/FOO/mounts/onlyoffice/logs:/var/log/onlyoffice \
    -v /home/FOO/mounts/onlyoffice/data:/var/www/onlyoffice/Data \
    -v /home/FOO/mounts/onlyoffice/filecache:/var/lib/onlyoffice \
    -v /home/FOO/mounts/onlyoffice/db:/var/lib/postgresql \
    -e "WOPI_ENABLED=true" \
    onlyoffice/documentserver:7.4.0.1
```

## Additional context
Host machine is Debian Buster 10.2 with upstream docker repo installed so docker isn't super out of date

Edit1: DNS has been obfuscated for a little privacy, but I hope it's clear in the above I have `cloud.*`, `docs.*`, and `wopi.*` subdomains setup.

Edit2: Oh and reverse proxy in use it NGINX hosted on another machine, I have copied the doc suggested settings for all 3 proxy entries for all 3 domains.

Thank you for reading this far! I really appreciate the help and can taste how close I am to getting this working!

**Comment by micbar** [comment]
NOTE: our examples have changed after 3.0.0

This is the crucial change. The DNS between our services no longer resolves the hostname, you now need to use the service names https://github.com/owncloud/ocis/commit/a86aba1c4144d54d80fd956ddcb9139518cbfc04

for the https issue: Do you have a valid ssl cert for the documentserver?

**Comment by gregflynn** [comment]
> NOTE: our examples have changed after 3.0.0
> 
> This is the crucial change. The DNS between our services no longer resolves the hostname, you now need to use the service names [a86aba1](https://github.com/owncloud/ocis/commit/a86aba1c4144d54d80fd956ddcb9139518cbfc04)

I noticed that, but I'm not using hostnames afaik in the above, all routes should be IP addresses, usually through the docker loopback IP since each container forwards its relevant ports to the host

> for the https issue: Do you have a valid ssl cert for the documentserver?

I have a wildcard cert for the domain that NGINX terminates similar to the Traifek example

**Comment by micbar** [comment]
>   all routes should be IP addresses

IP addresses will also not work

Please check my provided example. eg. `REVA_GATEWAY=com.owncloud.api.gateway`

**Comment by micbar** [comment]
I also suggest to use a better service registry in production. 

How did you set `MICRO_REGISTRY`?

**Comment by gregflynn** [comment]
> > all routes should be IP addresses
> 
> IP addresses will also not work
> 
> Please check my provided example. eg. `REVA_GATEWAY=com.owncloud.api.gateway`
```
Jul 31 07:18:28 hexadebian docker[17772]: {"level":"error","pid":1,"error":"com.owncloud.api.gateway: service not found","time":"2023-07-31T12:18:28.352510738Z","caller":"github.com/cs3org/reva/v2@v2.15.0/internal/grpc/services/appprovider/appprovider.go:128","message":"error registering app provider: could not get gateway client"}
```
I replaced that DNS with the IP address because it wasn't clear to me who or what was creating that DNS, and it looks like in this setup it's still not being mapped to anything

> I also suggest to use a better service registry in production.
> How did you set MICRO_REGISTRY?

It's not currently set since it 3.0.0 crashed on it but I can add it back, the documentation for that environment variable doesn't currently mention `mdns` as a valid value
![image](https://github.com/owncloud/ocis/assets/295898/46e0682f-659e-4303-8596-5e76de8c7472)

But adding `MICRO_REGISTRY="mdns"` to the two env files above causes:
```
Jul 31 07:23:49 hexadebian docker[25727]: ocis
Jul 31 07:23:49 hexadebian docker[25736]: Registry "mdns" not found
```

**Comment by gregflynn** [comment]
Doing a little bit of reading on what [mDNS](https://github.com/hashicorp/mdns) is (i don't have a ton of golang experience).

Is it correct to say 3.1.0beta leverages multicast DNS to not _need_ explicit IP/Port mappings, but that shouldn't preclude the use of explicit IP/Port mappings since the information mDNS is circulating maps back to an IP at the end of the day doesn't it? Because if IP addresses don't work, what are we using for networking here then?

**Comment by micbar** [comment]
@gregflynn Please don't get confused between internal (grpc between ocis services) and external communication.

We only changed the internal service registry. That means all communication behind the ocis proxy. We needed to make that change to enable scaling individual services on the fly. The internal grpc client needs a service name and not an IP address because you could have a service more than one time. The grpc client in combination with the internal service registry will lookup the service by name and do a loadbalancing to the multiple services.

## Your usecase

You are using ocis services in more than one docker container. The appprovider cannot find the gateway in the service registry because these two containers do not share a service registry. To make that possible, you need to set MICRO_REGISTRY for both containers. If you have `mdns` available (normally usable in docker compose) that everything is fine and the two containers will share the registry. If you have not, there are more options like `etcd` or `nats` which require to start an extra container which e.g. provides `etcd`. You could use the docker image from bitnami.

Please ask more questions if it is still unclear.

**Comment by gregflynn** [comment]
> @gregflynn Please don't get confused between internal (grpc between ocis services) and external communication.
> 
> We only changed the internal service registry. That means all communication behind the ocis proxy. We needed to make that change to enable scaling individual services on the fly. The internal grpc client needs a service name and not an IP address because you could have a service more than one time. The grpc client in combination with the internal service registry will lookup the service by name and do a loadbalancing to the multiple services.

Yea after reading mDNS, it suits the enterprise use-case well if you're looking to dynamically add/remove nodes in a high-availability environment. Ideally the code could regex on this setting to detect if it's an IP address or DNS and switch accordingly. I have more fingers than users in my setup so I wasn't planning any high-availability.


> ## Your usecase
> 
> You are using ocis services in more than one docker container. The appprovider cannot find the gateway in the service registry because these two containers do not share a service registry. To make that possible, you need to set MICRO_REGISTRY for both containers. If you have `mdns` available (normally usable in docker compose) that everything is fine and the two containers will share the registry. If you have not, there are more options like `etcd` or `nats` which require to start an extra container which e.g. provides `etcd`. You could use the docker image from bitnami.
> 
> Please ask more questions if it is still unclear.

Both the docker-compose example provided and my use case use more than one docker container. I think the key difference however is the example puts all containers in a network with unrestricted access between echother, whereas without docker-compose I'm forwarding individual ports. This was done based on this image of the interaction between services: 
![image](https://github.com/owncloud/ocis/assets/295898/26c7e7d3-87ca-4892-aa0c-ab9a5c0b3974)

If I'm understanding you correctly, what's missing from this diagram is a shared configuration server like etcd or an indication that the services need unrestricted network access between eachother

**Comment by gregflynn** [comment]
Tried creating a network, but still the same issue with mDNS, i'll try an etcd container next
`docker create network ocis`
add `--network ocis` to all the unit files
reboot all 4 containers
```
Jul 31 09:48:38 hexadebian docker[6602]: {"level":"error","pid":1,"error":"com.owncloud.api.gateway: service not found","time":"2023-07-31T14:48:38.204461124Z","caller":"github.com/cs3org/reva/v2@v2.15.0/internal/grpc/services/appprovider/appprovider.go:128","message":"error registering app provider: could not get gateway client"}
``` 

womp womp

**Comment by gregflynn** [comment]
So back to basics since I'm overcomplicating things, let's just pull down the example and make minimal edits for a working environment on 3.1.0.

```yaml
---
version: "3.7"

services:
  ocis:
    image: owncloud/ocis:3.1.0-beta.1
    networks:
      ocis-net:
    entrypoint:
      - /bin/sh
    command: ["-c", "ocis server"]
    environment:
      OCIS_URL: https://cloud.foo.bar
      OCIS_LOG_LEVEL: warning
      PROXY_HTTP_ADDR: 0.0.0.0:3006
      PROXY_TLS: "false"
      GATEWAY_GRPC_ADDR: 0.0.0.0:9142 # make the REVA gateway accessible to the app drivers
      # fulltext search
#      SEARCH_EXTRACTOR_TYPE: tika
#      SEARCH_EXTRACTOR_TIKA_TIKA_URL: http://tika:9998
      # make the registry available to the app provider containers
      MICRO_REGISTRY: "mdns"
    volumes:
      - ./config/ocis/app-registry.yaml:/etc/ocis/app-registry.yaml
      - /ZFS/owncloud/conf:/etc/ocis
      - /ZFS/owncloud/data:/var/lib/ocis
    logging:
      driver: "local"
    ports:
      - "3006:3006"
    restart: always

  ocis-appprovider-onlyoffice:
    image: owncloud/ocis:3.1.0-beta.1
    networks:
      ocis-net:
    user: "0" # needed for apk add in entrypoint script
    entrypoint:
      - /bin/sh
      - /entrypoint-override.sh
    #command: app-provider server
    environment:
      # use the internal service name of the gateway
      REVA_GATEWAY: ${REVA_GATEWAY:-com.owncloud.api.gateway}
      APP_PROVIDER_GRPC_ADDR: 0.0.0.0:9164
      # configure the service name to avoid collision with collabora
      APP_PROVIDER_SERVICE_NAME: app-provider-onlyoffice
      # use the internal service name
      APP_PROVIDER_EXTERNAL_ADDR: com.owncloud.api.app-provider-onlyoffice
      APP_PROVIDER_DRIVER: wopi
      APP_PROVIDER_WOPI_APP_NAME: OnlyOffice
      APP_PROVIDER_WOPI_APP_ICON_URI: https://docs.foo.bar/web-apps/apps/documenteditor/main/resources/img/favicon.ico
      APP_PROVIDER_WOPI_APP_URL: https://docs.foo.bar
      APP_PROVIDER_WOPI_WOPI_SERVER_EXTERNAL_URL: https://wopi.foo.bar
      APP_PROVIDER_WOPI_FOLDER_URL_BASE_URL: https://cloud.foo.bar
      # share the registry with the ocis container
      MICRO_REGISTRY: "mdns"
    volumes:
      - ./config/ocis-appprovider-onlyoffice/entrypoint-override.sh:/entrypoint-override.sh
      - /ZFS/owncloud/conf:/etc/ocis
    logging:
      driver: "local"
    restart: always

  wopiserver:
    image: cs3org/wopiserver:v10.1.1
    networks:
      ocis-net:
    entrypoint:
      - /bin/sh
      - /entrypoint-override.sh
    environment:
      WOPISECRET: LALALASECRETLALALA
      WOPISERVER_DOMAIN: wopi.foo.bar
    volumes:
      - ./config/wopiserver/entrypoint-override.sh:/entrypoint-override.sh
      - ./config/wopiserver/wopiserver.conf.dist:/etc/wopi/wopiserver.conf.dist
      - wopi-recovery:/var/spool/wopirecovery
    logging:
      driver: "local"
    ports:
      - "3008:8880"
    restart: always

  onlyoffice:
    image: onlyoffice/documentserver:7.4.0.1
    networks:
      ocis-net:
    entrypoint:
      - /bin/sh
      - /entrypoint-override.sh
    environment:
      WOPI_ENABLED: "true"
    volumes:
      - ./config/onlyoffice/entrypoint-override.sh:/entrypoint-override.sh
      - ./config/onlyoffice/local.json:/etc/onlyoffice/documentserver/local.dist.json
    logging:
      driver: "local"
    ports:
      - "3007:80"
    restart: always

#  tika:
#    image: apache/tika:2.8.0.0-full
#    networks:
#      ocis-net:
#    restart: always

volumes:
  wopi-recovery:

networks:
  ocis-net:
```

And I guess good news/bad news:
*GOOD*: we can resolve the above networking issues if we just go with docker-compose, no idea why my regular docker network didn't work but i can figure that out later
*BAD*: back to the same issue I ran into with 3.0.0 where the iframe content is HTTP
![image](https://github.com/owncloud/ocis/assets/295898/34f04a3c-ec20-47f6-902c-d49b7750b64e)

Double checked firefox and chrome just to be sure this isn't a firefox quirk or something

I can hit all 3 subdomains and get the standard landing pages over https

Not sure if it matters but my nginx is configured to redirect all http traffic to https
```
server {
        listen 8080 default_server;
        server_name foo.bar;
        return 301 https://$host$request_uri;
    }

**Comment by gregflynn** [comment]
![](https://media2.giphy.com/media/3o7abA4a0QCXtSxGN2/giphy.gif?cid=ecf05e47dwott9m989ngqapfac1z1hpdvu5jf1u02k3q6v0e&ep=v1_gifs_search&rid=giphy.gif&ct=g)

Turns out the issue was `7.4.0.1` of onlyoffice, `7.4.1` from last night works no problem, well less problems, some other kinks to work out but this one is solved!

Thank you!

**Comment by micbar** [comment]
> Turns out the issue was 7.4.0.1 of onlyoffice, 7.4.1

Good to know. We didn't use that version in our examples yet.

**Comment by micbar** [comment]
> we can resolve the above networking issues if we just go with docker-compose, no idea why my regular docker network didn't work but i can figure that out later

IMO the regular docker network doesn't provide mdns

In another deployment, i am using `etcd`

You need a container like


```yaml
  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      ocis-net:
```

and all ocis services should use

```
      MICRO_REGISTRY: "etcd"
      MICRO_REGISTRY_ADDRESS: "etcd:2379"
```
