### ISSUE TITLE
Nats discard policy "new"

### ISSUE THREAD

**Issue by case0sh** [owncloud/ocis#7231]
## Describe the bug
The oCIS nats store does create streams with discard policy "new"
```
~ # nats s info OBJ_eventhistory
Information for Stream OBJ_eventhistory created 2023-09-06 08:20:09

          Description: Object storage administered by go-micro store plugin
             Subjects: $O.eventhistory.C.>, $O.eventhistory.M.>
             Replicas: 1
              Storage: File

Options:

            Retention: Limits
     Acknowledgements: true
       Discard Policy: New
     Duplicate Window: 2m0s
           Direct Get: true
    Allows Msg Delete: true
         Allows Purge: true
       Allows Rollups: true

Limits:

     Maximum Messages: unlimited
  Maximum Per Subject: unlimited
        Maximum Bytes: unlimited
          Maximum Age: 14d0h0m0s
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited


Cluster Information:

                 Name: nats
               Leader: nats-2

State:

             Messages: 36
                Bytes: 24 KiB
             FirstSeq: 1 @ 2023-09-06T08:20:09 UTC
              LastSeq: 36 @ 2023-09-06T08:22:14 UTC
     Active Consumers: 0
   Number of Subjects: 36
```

This currently does not have any bad effect because oCIS is not setting limits on a stream, but if somebody enforces limits policy "new" might not be what we want

## Steps to reproduce

1. start oCIS with external Nats
2. Inspect the stream for the oCIS store 

## Expected behavior
Discard policy should be "old" 

## Actual behavior
Discard policy is "new"

## Setup

I was using the ocis-nats deployment example for k8s.

**Comment by wkloucek** [comment]
will be supersed if https://github.com/owncloud/ocis/issues/7272 is implemented

**Comment by wkloucek** [comment]
Caches should have Discard Policy "old"

eg storage-users don't have it yet:

```
~ # nats stream info KV_storage-users
Information for Stream KV_storage-users created 2024-01-23 11:39:16

           Description: KeyValue storage administered by go-micro store plugin
              Subjects: $KV.storage-users.>
              Replicas: 1
               Storage: Memory

Options:

             Retention: Limits
       Acknowledgments: true
        Discard Policy: New
```
