### ISSUE TITLE
hardcoded localhost?

### ISSUE THREAD

**Issue by mrpops2ko** [owncloud/ocis#7258]
## Describe the bug

I suspect its somewhere hardcoded localhost into the url, but this is what im getting
![bug](https://gyazo.com/0ee3c8a088a1da2ebe897b08741c4fd6.gif)
![bug2](https://gyazo.com/6e35e08ea477c324e7fe022cdece111d.gif)

we can see if i modify the url away from localhost it would actually work (obviously as the installation is not localhost)

i am trying to install ocis using docker-compose, i will attach my compose file (i had generated the init file already)

```
version: "3.7"
services:
  ocis:
    image: owncloud/ocis:latest
    networks:
      br0:
        ipv4_address: 192.168.1.186
    volumes:
      - /mnt/cache_nvme/appdata/owncloud/ocis.yaml:/etc/ocis/ocis.yaml
      - /mnt/cache_nvme/appdata/owncloud/ocis-data:/var/lib/ocis
networks:
  br0:
    external: true
```

my env file has
```
OCIS_INSECURE=true
OCIS_URL=https://192.168.1.186:9200
OCIS_LOG_LEVEL=debug
PROXY_HTTP_ADDR=0.0.0.0:9200
IDM_CREATE_DEMO_USERS=true
```

I am using docker ipvlan but that shouldn't matter in this
    

## Expected behavior
the page to load?

## Actual behavior
the page does not load

**Comment by micbar** [comment]
Seems like a caching issue. The config.json may be cached and localhost is the default. 

OCIS_URL=https://192.168.1.186:9200 should change the behavior but it needs a hard reload.

You can check the output of `config.json`.

**Comment by mrpops2ko** [comment]
ah thank you so much for this response

for some reason i had to declare the .env file in the docker-compose rather than it just being auto loaded

```
root@alexandria:~# docker exec -it owncloud_infinite_scale-ocis-1 sh
~ $ ls -al
total 8
drwxrwxrwx    1 99       users           90 Sep  9 03:21 .
drwxr-xr-x    1 root     root            34 Sep  9 00:43 ..
-rw-------    1 ocis-use ocis-gro       100 Sep  9 12:19 .ash_history
drwx------    1 ocis-use ocis-gro        54 Sep  9 03:19 idm
drwx------    1 ocis-use ocis-gro        64 Sep  9 03:19 idp
drwxr-x---    1 ocis-use ocis-gro        18 Sep  9 03:19 nats
drwx------    1 ocis-use ocis-gro        40 Sep  9 03:19 proxy
drwx------    1 ocis-use ocis-gro        10 Sep  9 03:19 search
drwx------    1 ocis-use ocis-gro        26 Sep  9 03:19 storage
drwx------    1 ocis-use ocis-gro        40 Sep  9 12:17 store
~ $ env
HOSTNAME=b71eeb41d93a
SHLVL=1
HOME=/var/lib/ocis
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/var/lib/ocis
```

^before

```
version: "3.7"
services:
  ocis:
    image: owncloud/ocis:latest
    env_file:
      - .env
    networks:
      br0:
        ipv4_address: 192.168.1.186
    volumes:
      - /mnt/cache_nvme/appdata/owncloud/ocis.yaml:/etc/ocis/ocis.yaml
      - /mnt/cache_nvme/appdata/owncloud/ocis-data:/var/lib/ocis
networks:
  br0:
    external: true
```
^ after

```
~ $ root@alexandria:~# docker exec -it owncloud_infinite_scale-ocis-1 sh
~ $ env
HOSTNAME=385bf73a1c48
OCIS_INSECURE=true
SHLVL=1
HOME=/var/lib/ocis
TERM=xterm
OCIS_LOG_LEVEL=debug
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
OCIS_URL=https://192.168.1.186:9200
IDM_CREATE_DEMO_USERS=true
PWD=/var/lib/ocis
PROXY_HTTP_ADDR=0.0.0.0:9200
```
