### ISSUE TITLE
POST request to create link with incorrect password returns 400 instead of 403

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ocis#8004]
## Describe the bug

If clients create a password for the link that does not match the policy, request returns `400 Bad Request`  instead of `403 Forbidden`

## Steps to reproduce

1. Create a new link using a mobile client with a password that does not match the given policy

that curl simulates the operation

```
curl -s -k -u <user:pwd> 'https://<url>/ocs/v2.php/apps/files_sharing/api/v1/shares' -X POST -H 'content-type: application/x-www-form-urlencoded' -H 'Origin: https://<url>' -H 'Connection: keep-alive' -H 'Referer: https://<url>/files/spaces/personal/<username>?fileId=dcfd1520-b2b7-4d5c-a557-947dc830bb3f%24f88aac90-8060-4b6b-9d7b-3ec40d77462d%21f88aac90-8060-4b6b-9d7b-3ec40d77462d&tiles-size=1&files-spaces-generic-view-mode=resource-table&items-per-page=100' -H 'Cookie: occelzrainqf=1f1olng1ce1ldouujsmk2k9ta6' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' --data-raw 'shareType=3&path=%2FDocuments&space_ref=dcfd1520-b2b7-4d5c-a557-947dc830bb3f%24f88aac90-8060-4b6b-9d7b-3ec40d77462d!781f56fa-e351-4d60-aaf3-8ed428db3c96&permissions=1&password=a'   | xmllint --format -
<?xml version="1.0" encoding="UTF-8"?>
```

## Expected behavior

Request is correct sintactically and semantically, so `400` is not proper error code. oC10 returns `403` under same context. Apart of that, returns `failure` instead of `error`

```
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>failure</status> <==== oC10 returns "failure" instead of error
    <statuscode>403</statuscode>  
    <message>At least 8 characters are required
at least 1 uppercase letters are required
at least 1 numbers are required
at least 1 special characters are required  !"#$%&amp;'()*+,-./:;&lt;=&gt;?@[\]^_`{|}~</message>
  </meta>
</ocs>
```

## Actual behavior

```
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>error</status>
    <statuscode>400</statuscode>
    <message>At least 8 characters are required
at least 1 uppercase letters are required
at least 1 numbers are required
at least 1 special characters are required  !"#$%&amp;'()*+,-./:;&lt;=&gt;?@[\]^_`{|}~</message>
  </meta>
</ocs>
```

## Setup

```
version: "3.7"

services:
  ocis:
    image: owncloud/ocis:5.0.0-beta.1
    ports:
      - 9200:9200
      - 9215:9215
    environment:
      OCIS_INSECURE: "true"
      OCIS_URL: "<url>"
      IDM_CREATE_DEMO_USERS: "true"
      IDM_ADMIN_PASSWORD: "admin"
      PROXY_ENABLE_BASIC_AUTH: "true"
    restart: "no"
    entrypoint:
      - /bin/sh
    # run ocis init to initialize a configuration file with random secrets
    # it will fail on subsequent runs, because the config file already exists
    # therefore we ignore the error and then start the ocis server
    command: ["-c", "ocis init || true; ocis server"]
```
