### ISSUE TITLE
Bare metal install using Caddy reverse-proxy always shows "Not Logged In" upon initial admin login.

### ISSUE THREAD

**Issue by thanateros** [owncloud/ocis#8042]
## Describe the bug
After [bare metal install](https://doc.owncloud.com/ocis/next/depl-examples/bare-metal.html), allowing 80/443/mDns through my firewall, and using a Caddy simple 'reverse_proxy localhost:9200' I can reach the login page at the public url just fine.
After I login with 'admin' and the initially generated password, I get "Not Logged In".  Cleared browser cache, tried different browsers on different computers, all do the same thing. Blew away and recreated from scrach 5 times with same result. I've been trying to get this to work for 3 months and nothing on google has helped.

## Steps to reproduce
1. Follow instruction for bare metal install (link is above).
2. Ensure ports are open for 80, 443, and mDns.
3. Go to public url and enter 'admin' and the auto-generated password from first step in the process.
4. Observe the "Not Logged In" message. Hitting 'Log In Again' button just instantly takes on back to "Not Logged In".

## Expected behavior
To be logged into OCIS with the initial admin login.

## Actual behavior
![image](https://github.com/owncloud/ocis/assets/54838/ceb6a7e1-5615-4f8b-aa8a-c094967581e8)

## Setup
Hosted on a Digital Ocean VPS running Rocky Linux 9.

Caddy is the reverse-proxy.

HTTP, HTTPS, and mDns ports are open in the firewall.

OCIS is a binary install and configured with Systemd according to [bare metal install](https://doc.owncloud.com/ocis/next/depl-examples/bare-metal.html).

<details>
/etc/ocis/ocis.env
<p>

```console
OCIS_URL=https://url-of-my-website.com
PROXY_HTTP_ADDR=0.0.0.0:9200
PROXY_TLS=false
OCIS_INSECURE=false

OCIS_LOG_LEVEL=warn

OCIS_CONFIG_DIR=/etc/ocis
OCIS_BASE_DATA_PATH=/var/lib/ocis
```

</p>

/etc/ocis/ocis.yaml
<p>

```yaml
token_manager:
  jwt_secret: 'xxxxxxxxxxxxxxxxxxxxxxxxx'
machine_auth_api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
system_user_api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
transfer_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
system_user_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
admin_user_id: xxxxxxxxxxxxxxxxxxxxxxxxx
graph:
  application:
    id: xxxxxxxxxxxxxxxx
  events:
    tls_insecure: true
  spaces:
    insecure: true
  identity:
    ldap:
      bind_password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
idp:
  ldap:
    bind_password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
idm:
  service_user_passwords:
    admin_password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    idm_password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    reva_password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    idp_password: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
proxy:
  oidc:
    insecure: true
  insecure_backends: true
frontend:
  archiver:
    insecure: true
auth_basic:
  auth_providers:
    ldap:
      bind_password: xxxxxxxxxxxxxxxxxxxxxxxxxx
auth_bearer:
  auth_providers:
    oidc:
      insecure: true
users:
  drivers:
    ldap:
      bind_password: xxxxxxxxxxxxxxxxxxx
groups:
  drivers:
    ldap:
      bind_password: xxxxxxxxxxxxxxxxxxxxxxxxxxx
ocdav:
  insecure: true
thumbnails:
  thumbnail:
    transfer_secret: xxxxxxxxxxxxxxxxxxxxxxxxxx
    webdav_allow_insecure: true
    cs3_allow_insecure: true
search:
  events:
    tls_insecure: true
audit:
  events:
    tls_insecure: true
sharing:
  events:
    tls_insecure: true
storage_users:
  events:
    tls_insecure: true
  mount_id: e04820c6-486b-4531-85f2-d8fd8816e996
notifications:
  notifications:
    events:
      tls_insecure: true
nats:
  nats:
    tls_skip_verify_client_cert: true
gateway:
  storage_registry:
    storage_users_mount_id: e04820c6-486b-4531-85f2-d8fd8816e996
```

</p>

/etc/caddy/Caddyfile

<p>

```console
my-website.org {
        reverse_proxy localhost:9200

        log {
                output file /var/log/caddy/ocis.log
        }

        tls {
                dns digitalocean {env.DO_AUTH_TOKEN}
        }
}
```

</p>
</details>

## Additional context

I noticed in the browser console I see this:

![browser_console](https://github.com/owncloud/ocis/assets/54838/98b73d9a-0720-42a6-88fe-a6a230ec3e9c)
