### ISSUE TITLE
Cannot upload files in a distributed setup

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/ocis#821]
```
ocis-reva-frontend_1 | 2020-11-06T14:15:43Z ERR error doing PATCH request to data service error="Patch \"http://localhost:9155/data/89324adf-82b2-4dde-8a80-d7cbb0256905\": dial tcp 127.0.0.1:9155: connect: connection refused" pkg=rhttp service=storage traceid=1d2cd81e65eb1a8b103903c94e1ff22e
```
Relevant containers from docker-compose:
```
  ocis-reva-frontend:
    env_file: .global.env
    image: owncloud/ocis:latest
    depends_on:
      - micro
    expose:
      - 9140
    environment:
      - STORAGE_FRONTEND_PUBLIC_URL=https://<server>
      - STORAGE_GATEWAY_ENDPOINT=ocis-reva-gateway:9142
    command: storage-frontend

  ocis-reva-gateway:
    env_file: .global.env
    image: owncloud/ocis:latest
    depends_on:
      - micro
    expose:
      - 9142
    environment:
      - STORAGE_GATEWAY_ENDPOINT=ocis-reva-gateway:9142
      - STORAGE_USERPROVIDER_ENDPOINT=ocis-reva-users:9144
      - STORAGE_AUTH_BASIC_ENDPOINT=ocis-reva-auth-basic:9146
      - STORAGE_AUTH_BEARER_ENDPOINT=ocis-reva-auth-bearer:9148
      - STORAGE_SHARING_ENDPOINT=ocis-reva-sharing:9150
      - STORAGE_STORAGE_HOME_ENDPOINT=ocis-reva-storage-home:9154
      - STORAGE_FRONTEND_PUBLIC_URL=https://<server>
      - STORAGE_DATAGATEWAY_PUBLIC_URL=https://<server>/data
    command: storage-gateway --storage-home-endpoint ocis-reva-storage-home:9154

 ocis-reva-storage-home:
    env_file: .global.env
    image: owncloud/ocis:latest
    depends_on:
      - micro
    expose:
      - 9154
      - 9155
    environment:
      - STORAGE_HOME_ENABLE_HOME=true
      - STORAGE_OWNCLOUD_REDIS_ADDR=redis:6379
      - STORAGE_HOME_DRIVER=ocis
      - STORAGE_STORAGE_OCIS_ENABLE_HOME=true
      #- STORAGE_STORAGE_OCIS_LAYOUT={{substr 0 1 .Username}}/{{.Username}}
      - STORAGE_STORAGE_OCIS_LAYOUT={{substr 0 1 .Mail}}/{{.Mail}}
    command: storage-home
    volumes:
    - files:/var/tmp/ocis

```
I don't see a way to point the storage-fronted to the right location of the storage.
