### ISSUE TITLE
CORS configuration too much

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/ocis#8393]
## Describe the bug
As of now some CORS parameters are configurable via env vars e.g. `OCIS_CORS_ALLOW_METHODS`, `OCIS_CORS_ALLOW_HEADERS` (and `OCIS_CORS_EXPOSE_HEADERS` - see upcoming PR by @butonic )

Besides the fact that different services require different methods and headers and need to be configured on service level - changing the working default to anything different will most probably break some services partially.

## Proposal
Do not configure allow methods, allow headers, expose headers and max ago but leave this to the individual services.

**Comment by butonic** [comment]
I agree, the only 'global' CORS config should be the allowed origin. the rest should IMO be hardcoded. At least we sohuld drop the `OCIS_CORS*` env vars (save `OCIS_CORS_ALLOW_ORIGINS`)

**Comment by micbar** [comment]
>  At least we should drop the OCIS_CORS* env vars (save OCIS_CORS_ALLOW_ORIGINS)
I agree generally, but on a higher level we need to **really** change our attitude towards config.

We are getting more and more feedback, that our todays practise leads to broken deployments on every release.

The reality is, nobody reads the docs.

The biggest problem is exactly what we have here: Removals of config which was working before.

**Comment by wkloucek** [comment]
The Helm Chart currently only exposes the CORS allow origins setting:

https://github.com/owncloud/ocis-charts/blob/d43e44276efffc37cc8e62621d99a255da7c4cb5/charts/ocis/values.yaml#L57-L61

**Comment by tailnet-h-usky-io** [comment]
For me, the ENV var which _is_ exposed is not fully working on a fresh install.

I am trying to integrate a new installation of OwnCloud Infinite Scale _(Community Edition)_ with the [Janssen Authorization Server][1], an open-source OIDC provider. The authentication workflow _almost_ succeeds:

1. OwnCloud redirects to the SSO sign-in page
2. Authentication Credentials are accepted and the requested OIDC scopes for OwnCloud (profile, mail, etc.) are presented to the user for acceptance
3. Browser redirects to the OIDC callback page on OwnCloud (`https://oc.[my domain].io/oidc-callback`) 

However, when the landing page on OwnCloud attempts to fetch the authorization token via Javascript (a request to `https://[my domain]/jans-auth/restv1/token`) , a CORS violation occurs and the browser blocks the request.
``` Request URL:
https://sso.[my domain].io/jans-auth/restv1/token
Request Method:
POST
Status Code:
401 Unauthorized
Referrer Policy:
strict-origin-when-cross-origin 
```

It seems that `https://sso.[my domain].io/` needs to be added to the CORS configuration for the OwnCloud frontend. I _believe_ I have done this correctly, but it's still not working. 

I'm deploying OCIS using the [Helm charts][2], and the CORS-related configuration values _do_ seem to be making it into the containers...

``` 
❯ kubectl get pod frontend-5d7bfd6fdf-mkc5m -o yaml |\
  grep -C 2 OCIS_CORS_ALLOW_ORIGINS

...
    - name: OCIS_CORS_ALLOW_ORIGINS
      value: '*,https://sso.[my domain].io,https://oc.[my domain].io,https://[my domain].io'
    image: owncloud/ocis:4.0.1

```
also...
```
❯ kubectl exec frontend-5d7bfd6fdf-mkc5m -- sh -c 'echo $OCIS_CORS_ALLOW_ORIGINS'

*,https://sso.[my domain].io,https://oc.[my domain].io,https://[my domain].io
```

So the config values have made it at least as far as ENV vars inside the containers. But it seems not all the way to the browser? Seems like I'm missing something obvious.

Any help or tips debugging this will be greatly appreciated.

Thanks in advance,
-b


--- 

**The OIDC server is hosted at:** `https://sso.[my domain].io`
**OCIS is hosted at:**  `https://oc.[my domain].io`

### Steps to reproduce
1. Establish OIDC provider at `https://sso.[some domain].io/`
1. Deploy OCIS from the Helm charts to   `https://oc.[some domain].io`, using the following overrides:
```
externalDomain: oc.[some domain].io

# HTTP settings for oCIS services.
http:
  #-- CORS settings for oCIS services.
  cors:
    #-- allow_origins is a list of origins a cross-domain request can be executed from.
    # If the special "*" value is present in the list, all origins will be allowed.
    allow_origins: ["*", "https://sso.[some domain].io", "https://oc.[some domain].io", "https://[some domain].io"]
...
features:
  basicAuthentication: false
  externalUserManagement:
    enabled: true
```
3. Attempt to login

### Expected behaviour
Browser Javascript requests to `https://sso.[some domain].io` should be allowed from OwnCloud

### Actual behaviour
Browser Javascript requests to `https://sso.[some domain].io` are blocked by CORS configuration. :( 

### Server configuration
**Operating system**: Ubuntu 22.04 LTS + microk8s

**Web server:** Whatever is packaged into OCIS Community edition `04.0.1` containers

**Database:** Whatever is packaged into OCIS Community edition `04.0.1` containers

**PHP version:** I think it's none? Isn't OCIS composed of golang microservices?

**ownCloud version:** 4.0.1

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:**  [Helm charts][1]

**The content of config/config.php:** _Hopefully all CORS-related config is posted above..._

**List of activated apps:** default set for OCIS 4.0.1

**Are you using external storage:** No

**Are you using encryption:** no

**Are you using an external user-backend:** [Janssen Authorization Server][2]

#### LDAP configuration (delete this part if not used)
```
    ldap:
      writeable: true
      readOnlyAttributes:
      uri: ldaps://ldap.[my domain].io:1636
      certTrusted: true
      insecure: false
      bindDN: cn=Directory Manager
      refintEnabled: false
      passwordModifyExOpEnabled: false
      useServerUUID: true
      user:
        schema:
          id: inum
          idIsOctetString: false
          mail: mail
          displayName: displayName
          userName: uid
          userType: ownCloudUserType
        baseDN: ou=people,o=jans
        scope: sub
        substringFilterType: any
        objectClass: jansPerson
      group:
        schema:
          id: inum
          idIsOctetString: false
          mail: mail
          displayName: displayName
          groupName: inum
          member: member
        baseDN: ou=groups,o=jans        
        createBaseDN: ""
        scope: sub
        filter:
        objectClass: jansGrp
      using an ldap attribute.
      disableUsers:
        disableMechanism: attribute
        userEnabledAttribute: ownCloudUserEnabled
        disabledUsersGroupDN: "cn=DisabledUsersGroup,ou=groups,o=libregraph-idm"
```

### Client configuration
**Browser:** Chrome, Firefox, Safari _(all tested - same results)_

**Operating system:** Windows, Mac, Linux _(all tested - same results)_


[1]:https://github.com/JanssenProject/jans
[2]:https://github.com/owncloud/ocis-charts
