### ISSUE TITLE
Oidc callback not redirecting

### ISSUE THREAD

**Issue by ggianfran** [owncloud/ocis#8498]
## Describe the bug
I have ocis deployed using docker compose running behind a traefik proxy and using Authentik as an Idp. When I configure OIDC, I get stuck on the Oidc callback page like this:

![image](https://github.com/owncloud/ocis/assets/20611201/847a1130-ff92-44ed-822d-3330aa01a441)

The url of the page i am stuck on: https://owncloud.mydomain.com/web-oidc-callback?code=7e34a2c48f404193b1477aeb8087f15f&state=db07c11712fe48ca96d4e67d81734cd1

When OIDC is not configured, logging in works fine with the admin account.

## Steps to reproduce
1. Deployed oidc using docker compose following these instructions: https://helgeklein.com/blog/owncloud-infinite-scale-with-openid-connect-authentication-for-home-networks/#sso-via-authentik-owncloud-openid-connect-authentication

## Expected behavior
Redirected to owncloud homepage

## Actual behavior
Stuck on:
"Logging you in"
"Please wait, you are being redirected"

## Setup
Please describe how you started the server and provide a list of relevant environment variables or configuration files.

### docker-compose.yaml
<details>
<p>

```yaml
version: "3.9"

services:
  owncloud:
    container_name: owncloud
    hostname: owncloud
    image: owncloud/ocis:latest
    restart: unless-stopped
    networks:
      - proxy_network
    entrypoint:
      - /bin/sh
    command: ["-c", "ocis init || true; ocis server"]
    expose:
      - 9200
    env_file:
      - .env
    volumes:
      - ocis-config:/etc/ocis
      - ocis-data:/var/lib/ocis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ocis.entrypoints=websecure"
      - "traefik.http.routers.ocis.rule=Host(`owncloud.mydomain.com`)"
      - "traefik.http.routers.ocis.tls.certresolver=letsencrypt"
      - "traefik.http.routers.ocis.service=ocis"
      - "traefik.http.services.ocis.loadbalancer.server.port=9200"
volumes:
  ocis-config:
    name: ocis-config
  ocis-data:
    name: ocis-data

networks:
  proxy_network:
    external: true
```

</p>
</details>

### .env

<details>
<p>

```env
DEMO_USERS=false
PROXY_TLS=false
OCIS_INSECURE=true
OCIS_URL=https://owncloud.mydomain.com
PROXY_HTTP_ADDR=0.0.0.0:9200

OCIS_LOG_LEVEL=info
OCIS_LOG_COLOR=true
OCIS_LOG_PRETTY=true

OCIS_OIDC_ISSUER=https://auth.mydomain.com/application/o/owncloud/
WEB_OIDC_CLIENT_ID=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
PROXY_OIDC_REWRITE_WELLKNOWN=true

PROXY_OIDC_ACCESS_TOKEN_VERIFY_METHOD=none
PROXY_USER_OIDC_CLAIM=preferred_username
```

</p>
</details>
