### ISSUE TITLE
OCIS fails to start after upgrade from 5.0.0-rc.5 to 5.0.0-rc.6

### ISSUE THREAD

**Issue by mcarbonne** [owncloud/ocis#8669]
## Describe the bug
After upgrading from `5.0.0-rc.5` to `5.0.0-rc.6`, ocis wasn't starting anymore :

```
ocis[2406802]: The service account id has not been configured for ocm. Make sure your /etc/ocis config contains the proper values (e.g. by running ocis init or setting it ma....
```

First, I tried first to generate a new `ocis.yaml` but I ran into errors (unable to login anymore, see below).

Then I managed to start `5.0.0-rc.6` by manually adding this (to my original config):
```
ocm:
  service_account:
    service_account_id: XXXXXXXX
    service_account_secret: XXXXX
```
(I copy-pasted this section from the newly generated `ocis.yaml`)

Note: rolling-back to `5.0.0-rc.5` was also working.
Also, my config file was generated a long time ago (most likely with 5.0.0-alpha1).

## Steps to reproduce
1. Run ocis `5.0.0-rc.5`
2. Update image to ocis `5.0.0-rc.6`
3. The container does not start anymore

## Expected behavior
I've tested almost all 5.0 alpha/beta/rc without any issues.
I was expecting two things :
1. First, when removing `ocis.yaml`, a newly generated `ocis.yaml ` shall be OK.
I'm running ocis with keycloak and all OCIS parameters are setup using environment variables.

But in my setup, I ran into a lot of troubles after regenerating ocis.yaml:
```
2024-03-16T21:43:16Z ERR failed to add user error="LDAP Result Code 49 \"Invalid Credentials\": " request-id=XXXXX-000099 service=graph
2024-03-16T21:43:16Z ERR could not create user: backend error error="generalException: failed to add user" request-id=XXXXX-000099 service=graph
2024-03-16T21:43:16Z ERR Error creating user error="500 Internal Server Error" service=proxy
2024-03-16T21:43:16Z ERR Autoprovisioning user failed error="500 Internal Server Error" service=proxy
2024-03-16T21:43:16Z ERR invalid credentials bind_dn=uid=libregraph,ou=sysusers,o=libregraph-idm op=bind remote_addr=127.0.0.1:41032 service=idm
2024-03-16T21:43:16Z ERR Bind failed error="LDAP Result Code 49 \"Invalid Credentials\": " service=graph
2024-03-16T21:43:16Z ERR failed to add user error="LDAP Result Code 49 \"Invalid Credentials\": " request-id=XXX-000100 service=graph
2024-03-16T21:43:16Z ERR could not create user: backend error error="generalException: failed to add user" request-id=XXX-000100 service=graph
2024-03-16T21:43:16Z ERR Error creating user error="500 Internal Server Error" service=proxy
2024-03-16T21:43:16Z ERR Autoprovisioning user failed error="500 Internal Server Error" service=proxy
```
The only solution was to rollback and re-use the previous one.
What is the underlying limitation ? Why re-generating a new `ocis.yaml` do not work ?

Note: to be sure this wasn't related to my setup, I tried to do this :
- use the official keycloak docker compose example https://github.com/owncloud/ocis/tree/master/deployments/examples/ocis_keycloak
- checkout on `v5.0.0-rc.6`
- run `docker compose up`
- login on https://ocis.owncloud.test/ => OK
- stop `docker compose`
- remove ocis.yaml
- start again `docker compose up`
- cannot login anymore

2. Secondly, when upgrading ocis, I was expecting automatic migration of configuration file.
Is automatic config file migration a feature ? How to trigger it ? (`ocis init` seems to do nothing if a configuration file already exists).

## Setup
I'm running latest ocis 5.0.0 rc6 (podman) with keycloak SSO.
My setup is very similar to https://owncloud.dev/ocis/deployment/ocis_keycloak/

**Comment by micbar** [comment]
> But in my setup, I ran into a lot of troubles after regenerating ocis.yaml:
Oh! This is not supported. We cannot destroy the existing ocis.yaml. There are randomized secrets in that. Regenerating them will break the system.

Please check your process by comparing to the upgrade docs. https://doc.owncloud.com/ocis/5.0/migration/upgrading-ocis.html

> Secondly, when upgrading ocis, I was expecting automatic migration of configuration file.

We have a not so clear situation here. It is a known DevOPS paradigm to not change config files "automagically" by the installed application.

In the future we can also have a maintenance command that can do an incremental upgrade "on demand".

**Comment by prohtex** [comment]
Same here using WOPI deployment. I am stuck on rc5.

**Comment by micbar** [comment]
Please Check the upgrade guide in the docs.

you need to add service account id and secret to your config.

**Comment by jacobgkau** [comment]
My instance won't start because the service account isn't defined after upgrading from 4.x to 5.x I tried adding a section like this to my `ocis.yaml` like @mcarbonne did:

```
ocm:
  service_account:
    service_account_id: XXXXXXXX
    service_account_secret: XXXXX
```

...but it didn't work. The documentation page [here](https://doc.owncloud.com/ocis/next/deployment/services/s-list/ocm.html) suggests simply putting it in a top-level section (although it seems to be for a `master.yaml` and not `ocis.yaml`):

```
service_account:
  service_account_id: ""
  service_account_secret: ""
```

...which also doesn't work. I'm running OCIS as a single Podman container using the official Docker image, and I don't want to have to specify secrets as environment variables in my systemd service that starts the continer. What is the proper format to configure this on-disk in `ocis.yaml`? If it's not going to be upgraded "automagically," then it ought to at least be documented how to configure it instead of just saying "configure it."

**Comment by kulmann** [comment]
@jacobgkau the (identical) service account configuration is required for all services that need a service account. `grep`ing a fresh `ocis.yaml` file I have the following occurrences (see code block below). That's generated from `ocis init`. I have no clue if a service account config on the root level is possible. If yes, I'd expect it starting with `service_account:`, not `ocis:` as the root level key in the `ocis.yaml` file. Again, no idea if that is supposed to work. The global env variables (starting with `OCIS_`) are just a shorthand for setting the env vars of all services at once.

I'm including the id and secret here, because this is only a local dev instance that get's killed on a regular basis anyway. Please don't use the two values in a production instance but generate your own values.

```yaml
graph:
  service_account:
    service_account_id: 19dff10e-6694-4a48-a698-5c7c8a4a5008
    service_account_secret: sKrUn-e@w6Mn9N0XL=gUHegt%nDQ9!C6
--
proxy:
  service_account:
    service_account_id: 19dff10e-6694-4a48-a698-5c7c8a4a5008
    service_account_secret: sKrUn-e@w6Mn9N0XL=gUHegt%nDQ9!C6
--
frontend:
  service_account:
    service_account_id: 19dff10e-6694-4a48-a698-5c7c8a4a5008
    service_account_secret: sKrUn-e@w6Mn9N0XL=gUHegt%nDQ9!C6
--
search:
  service_account:
    service_account_id: 19dff10e-6694-4a48-a698-5c7c8a4a5008
    service_account_secret: sKrUn-e@w6Mn9N0XL=gUHegt%nDQ9!C6
--
storage_users:
  service_account:
    service_account_id: 19dff10e-6694-4a48-a698-5c7c8a4a5008
    service_account_secret: sKrUn-e@w6Mn9N0XL=gUHegt%nDQ9!C6
--
notifications:
  service_account:
    service_account_id: 19dff10e-6694-4a48-a698-5c7c8a4a5008
    service_account_secret: sKrUn-e@w6Mn9N0XL=gUHegt%nDQ9!C6
--
userlog:
  service_account:
    service_account_id: 19dff10e-6694-4a48-a698-5c7c8a4a5008
    service_account_secret: sKrUn-e@w6Mn9N0XL=gUHegt%nDQ9!C6
--
auth_service:
  service_account:
    service_account_id: 19dff10e-6694-4a48-a698-5c7c8a4a5008
    service_account_secret: sKrUn-e@w6Mn9N0XL=gUHegt%nDQ9!C6
--
clientlog:
  service_account:
    service_account_id: 19dff10e-6694-4a48-a698-5c7c8a4a5008
    service_account_secret: sKrUn-e@w6Mn9N0XL=gUHegt%nDQ9!C6
```

And one more service account related config that I found in the `ocis.yaml` file:
```yaml
settings:
  service_account_ids:
  - 19dff10e-6694-4a48-a698-5c7c8a4a5008
```
