### ISSUE TITLE
oCIS crashes when setup with external idp (keycloak) and web-config.json

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#8703]
## Describe the bug
oCIS crashes when setup with keycloak as idp and using custom web config file (`WEB_UI_CONFIG_FILE=`)

## Steps to reproduce
Example: https://github.com/owncloud/ocis/blob/master/deployments/examples/ocis_keycloak/docker-compose.yml
1. Start ocis with keycloak config and  `WEB_UI_CONFIG_FILE=<config.json>` ([example config](https://github.com/owncloud/web/blob/master/tests/drone/config-ocis.json))
```yml
# config.json
{
  "server": "https://ocis.owncloud.test",
  "theme": "https://ocis.owncloud.test/themes/owncloud/theme.json",
  "openIdConnect": {
    "metadata_url": "https://ocis.owncloud.test/.well-known/openid-configuration",
    "authority": "https://ocis.owncloud.test",
    "client_id": "web",
    "response_type": "code",
    "scope": "openid profile email"
  },
...
```
2. Try to login to the ocis

The following urls need to be rewritten to have keycloak urls:
```yml
"metadata_url": "https://ocis.owncloud.test/.well-known/openid-configuration",
"authority": "https://ocis.owncloud.test",
```

Crash log: https://drone.owncloud.com/owncloud/web/43528/4/14
```go
2024/03/20 12:55:20 http: panic serving 192.168.48.5:49642: runtime error: invalid memory address or nil pointer dereference
goroutine 602 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1898 +0xbe
panic({0x2d47760?, 0x648d2c0?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
net/http.(*Client).deadline(0x627645?)
	/usr/local/go/src/net/http/client.go:193 +0xe
net/http.(*Client).do(0x0, 0xc002270c60)
	/usr/local/go/src/net/http/client.go:608 +0x1f6
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:590
net/http.(*Client).Get(0x0, {0xc00297e230?, 0x0?})
	/usr/local/go/src/net/http/client.go:487 +0x5f
github.com/owncloud/ocis/v2/services/proxy/pkg/staticroutes.(*StaticRouteHandler).oIDCWellKnownRewrite(0xc000373188, {0x7f1432ea7c90, 0xc001e4af80}, 0x1?)
	/go/src/github.com/owncloud/ocis/services/proxy/pkg/staticroutes/oidc_well-known.go:14 +0x73
net/http.HandlerFunc.ServeHTTP(0xc001bd0690?, {0x7f1432ea7c90?, 0xc001e4af80?}, 0xc0027ac420?)
	/usr/local/go/src/net/http/server.go:2166 +0x29
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc001275560, {0x7f1432ea7c90, 0xc001e4af80}, 0xc002270a20)
	/go/src/github.com/owncloud/ocis/vendor/github.com/go-chi/chi/v5/mux.go:459 +0x2e6
net/http.HandlerFunc.ServeHTTP(0xc002a02d20?, {0x7f1432ea7c90?, 0xc001e4af80?}, 0xc006b81c40?)
	/usr/local/go/src/net/http/server.go:2166 +0x29
```

### Findings
Could not start ocis-keycloak starting from commit: https://github.com/owncloud/ocis/commit/5cc286b8efc0f5d20d902e2fdd2ffe8a7091f509
