### ISSUE TITLE
Moved ocis setup to another server (docker > docker) users cannot see their files anymore

### ISSUE THREAD

**Issue by KawaKode** [owncloud/ocis#8820]
## Describe the bug
I just moved my OCIS docker setup to another server, I use S3NG as the storage driver and use the exact same bucket for the user's data. I also moved the data and config folders over to the new server. I can login but cannot see my data anymore, but I can still see my data usage as if the files were there. What can I do to tell OCIS to re-index the files that are on the bucket ?

![image](https://github.com/owncloud/ocis/assets/75862028/7384bb01-7a17-45c6-8b1c-b8278bbe1b1a)

## Steps to reproduce
1. Move the compose file to another docker server
2. Move the data and config folders
3. Start up the server

## Expected behavior
It should display files as the same bucket is used.

## Actual behavior
Users cannot see their files anymore, as if they were deleted, but they can still se the quota. EG : user can see that hes using 52/200GB.

## Setup
Please describe how you started the server and provide a list of relevant environment variables or configuration files.

Here's the compose file (exact same on both servers, data anonymized for this ticket) : 

```yaml
version: "3.7"

services:
  ocis:
    image: owncloud/ocis:latest
    networks:
      ocis-net:
    entrypoint:
      - /bin/sh
    command: ["-c", "ocis init || true; ocis server"]
    ports:
      - 9200:9200
    environment:
      OCIS_URL: https://cloud.domain.com
      PROXY_HTTP_ADDR: 0.0.0.0:9200
      OCIS_LOG_LEVEL: info
      OCIS_LOG_COLOR: "true"
      NATS_NATS_HOST: 0.0.0.0
      OCIS_SERVICE_ACCOUNT_ID: "<ACC_ID>"
      OCIS_SERVICE_ACCOUNT_SECRET: "<SECRET>"
      OCIS_ASYNC_UPLOADS: "true"
      OCIS_FRONTEND_UPLOAD_MAX_CHUNK_SIZE: "10000000"
      
      # activate s3ng storage driver
      STORAGE_USERS_DRIVER: s3ng
      STORAGE_SYSTEM_DRIVER: ocis # keep system data on ocis storage since this are only small files atm
      # s3ng specific settings
      STORAGE_USERS_S3NG_ENDPOINT: "<ENDPOINT>"
      STORAGE_USERS_S3NG_REGION: "<REGION>"
      STORAGE_USERS_S3NG_ACCESS_KEY: "<KEY>"
      STORAGE_USERS_S3NG_SECRET_KEY: "<SECRET>"
      STORAGE_USERS_S3NG_BUCKET: "<BUCKET>"
      OCIS_INSECURE: "false"
      # basic auth (not recommended, but needed for eg. WebDav clients that do not support OpenID Connect)
      #PROXY_ENABLE_BASIC_AUTH: "${PROXY_ENABLE_BASIC_AUTH:-false}"
      # admin user password
      IDM_ADMIN_PASSWORD: "<PASSWORD>" # this overrides the admin password from the configuration file
      # demo users
      IDM_CREATE_DEMO_USERS: "false"
      OCIS_SHARING_PUBLIC_SHARE_MUST_HAVE_PASSWORD: "false"
    volumes:
      - /docker/ocis/ocis-config/_data:/etc/ocis
      - /docker/ocis/ocis-data/_data:/var/lib/ocis
    logging:
      driver: "local"
    restart: always

volumes:
  certs:

networks:
  ocis-net:
```

## Additional context
The two servers are using Docker, I transfered the ocis_data and ocis_folders in their entirety.
