### ISSUE TITLE
Unable to change 'uidNumber' filter in users service (OCIS Helm/Kubernetes)

### ISSUE THREAD

**Issue by justSem** [owncloud/ocis#8919]
## Describe the bug
When setting up OCIS on Kubernetes with Authentik as OIDC/LDAP backend I observe some strange behaviour.
The helm charts setting `externalUserManagement.ldap.user.shchema.id` makes me think that is the 'uid' value the `user` service will use to perform it's LDAP search with. However, when going through the debug logging it becomes evident the behavior is different.

An example below:
`2024-04-22T15:25:31Z DBG GetUserByClaim error="error: not found: (&(objectClass=user)(objectclass=inetOrgPerson)(uidNumber=<OIDC hash>)(!(ak-active=FALSE)))"`

This error makes evident that the user service seems to be looking for an attribute called `uidNumber`. While this is a valid and existing attribute in my LDAP schema, it's automatically populated by Authentik and is not propagated to any OIDC claim, hence, I cannot match on this specific value. However, the OIDC claims do supply me with an uid hash, which is also present in the LDAP schema as the `uid` attribute.

I would assume that setting `externalUserManagement.ldap.user.shchema.id` to `uid` would alter `uidNumber` to `uid` in the LDAP search filter.

## Steps to reproduce
1. Deploy both OCIS and Authentik on K3S using helm.
2. Setup LDAP/OIDC using the default values in Authentik
3. Configure the OCIS helm chart as per the values below
4. Attempt l ogin.

## Expected behavior
I expected that when `externalUserManagement.ldap.user.shchema.id` is set to `uid` it would alter the LDAP search to use that specific attribute in the LDAP search filter.

## Actual behavior
The user service searches for a (seemingly hardcoded?) value of `uidNumber`.

## Setup
I'm running K3S on Ubuntu.
OCIS is deployed using the OCIS helm chart.
Authentik is deployed using the Authentik helm chart.
There is an Authentik outpost in the proper namespace which OCIS can authenticate to.k -

## Additional context

**User schema example**
```
dn: cn=<redacted>,ou=users,dc=ldap,dc=<redacted>,dc=<redacted>
app_password: <redacted>
app_username: <redacted>
uidNumber: 2005
sAMAccountName: <redacted>
name: <redacted>
mail: <redacted>
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: inetOrgPerson
objectClass: user
objectClass: posixAccount
objectClass: goauthentik.io/ldap/user
memberOf: cn=authentik Admins,ou=groups,dc=ldap,dc=<redacted>,dc=<redacted>
sn: <redacted>
ak-active: TRUE
ak-superuser: TRUE
uid: 2ed8e57fe0cf86d07488b6e5626e2ce0262cddaab98cde67459ad620de8dfe5a
homeDirectory: /home/username
cn: <redacted>
displayName: <redacted>
gidNumber: 2005

```

**Helm chart values**

```yaml
   features:
      externalUserManagement:
        enabled: true
        adminUUID: "<redacted>"
        oidc:
          issuerURI: "<redacted>"
          webClientID: "<redacted>"
          userIDClaim: "sub"
          userIDClaimAttributeMapping: "uid"
          sessionManagementLink: "<redacted>"
          editAccountLink: "<redacted>"
          roleAssignment:
            enabled: true
            claim: "groups"
            mapping:
              - role_name: "admin"
                claim_value: "authentik Admins"
              - role_name: "user"
                claim_value: "OCIS User"
        ldap:
          writeable: false
          uri: "ldaps://<redacted>"
          certTrusted: false
          bindDN: "cn=<redacted>,OU=users,dc=ldap,dc=<redacted>,dc=<redacted>"
          baseDN: "DC=ldap,DC=<redacted>,DC=<redacted>"
          useServerUUID: true
          user:
            schema:
              id: "uid"
              userName: "cn"
              displayName: "displayName"
            baseDN: "OU=users,DC=ldap,DC=<redacted>,DC=<redacted>"
            filter: "(objectClass=user)"
          group:
            schema:
              id: "uid"
            baseDN: "OU=groups,DC=ldap,DC=<redacted>,DC=<redacted>"
            filter: "(objectClass=group)"
          disableUsers:
            disableMechanism: "attribute"
            userEnabledAttribute: "ak-active"
    secretRefs:
      ldapCaRef: "ldap-ca"
      ldapSecretRef: "ldap-bind-secrets"

```
