### ISSUE TITLE
"missing or incomplete nats configuration. Events will not be published" warnings

### ISSUE THREAD

**Issue by Sad-Soul-Eater** [owncloud/ocis#8921]
## Describe the bug

There are next warnings in the log:

```log
WRN missing or incomplete nats configuration. Events will not be published. line=github.com/cs3org/reva/v2@v2.19.5/internal/http/services/dataprovider/dataprovider.go:83 pkg=rhttp service=ocm
WRN missing or incomplete nats configuration. Events will not be published. line=github.com/cs3org/reva/v2@v2.19.5/internal/http/services/dataprovider/dataprovider.go:83 pkg=rhttp service=storage-system
```

Full log: https://gist.github.com/Sad-Soul-Eater/f26942a8ab736221005f94074752d544

## Steps to reproduce
1. Run ocis in the container

## Expected behavior
No warnings

## Actual behavior
Warnings exist

## Setup
Minimal setup in k8s

<details>
<summary>deployment.yaml</summary>

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app owncloud
  labels:
    app: *app
spec:
  replicas: 1

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: *app

  template:
    metadata:
      labels:
        app: *app

    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false

      containers:
        - name: owncloud
          image: owncloud/ocis:5.0.2
          command: [ /bin/sh ]
          args: [ "-c", "ocis init || true; ocis server" ]

          env:
            - name: OCIS_INSECURE
              value: "false"

            - name: OCIS_URL
              value: "https://owncloud.example.com"

            - name: IDM_ADMIN_PASSWORD
              value: "admin"

            - name: OCIS_LOG_LEVEL
              value: "trace"
            - name: OCIS_LOG_PRETTY
              value: "true"

            - name: PROXY_TLS # do not use SSL between Traefik and oCIS
              value: "false"

          ports:
            - name: http
              containerPort: 9200

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: &user 1000
            runAsGroup: *user
            seccompProfile:
              type: RuntimeDefault

          volumeMounts:
            - name: data
              mountPath: /var/lib/ocis

            - name: tmp
              mountPath: /tmp

      securityContext:
        fsGroup: *user
        fsGroupChangePolicy: "OnRootMismatch"

      volumes:
        - name: data
          emptyDir: { }

        - name: tmp
          emptyDir: { }
```

</details>

## Additional context

There is discussion here: https://central.owncloud.org/t/ocis-seems-to-just-hang-after-some-time/45372/5

**Comment by micbar** [comment]
No clear picture in central. Please re open if the issue is still present. We cannot reproduce that in our public deployments using ocis 5.0.5.

**Comment by Sad-Soul-Eater** [comment]
@micbar Warnings is still here in the version `owncloud/ocis:5.0.5`

Here are logs with the `warn` level: https://gist.github.com/Sad-Soul-Eater/96c135b3e19b18b730bd8215b34f80b8#file-warn-log
And `trace` level: https://gist.github.com/Sad-Soul-Eater/96c135b3e19b18b730bd8215b34f80b8#file-trace-log

You can try to reproduce it with the next deployment:
The logs above taken from that deployment

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app owncloud
  labels:
    app: *app
spec:
  replicas: 1

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: *app

  template:
    metadata:
      labels:
        app: *app

    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false

      containers:
        - name: owncloud
          image: owncloud/ocis:5.0.5
          command: [ /bin/sh ]
          args: [ "-c", "ocis init || true; ocis server" ]

          env:
            - name: OCIS_INSECURE
              value: "false"

            - name: OCIS_URL
              value: "https://owncloud-test.example.com"

            - name: IDM_ADMIN_PASSWORD
              value: "admin"

            - name: OCIS_LOG_LEVEL
              value: "warn"
            - name: OCIS_LOG_PRETTY
              value: "true"

            - name: PROXY_TLS # do not use SSL between Traefik and oCIS
              value: "false"

          ports:
            - name: http
              containerPort: 9200

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: &user 1000
            runAsGroup: *user
            seccompProfile:
              type: RuntimeDefault

          volumeMounts:
            - name: data
              mountPath: /var/lib/ocis

            - name: tmp
              mountPath: /tmp

      securityContext:
        fsGroup: *user
        fsGroupChangePolicy: "OnRootMismatch"

      volumes:
        - name: data
          emptyDir: { }

        - name: tmp
          emptyDir: { }
```
