### ISSUE TITLE
Unable to collect prometheus metrics

### ISSUE THREAD

**Issue by rcrisanti** [owncloud/ocis#9168]
## Describe the bug

Unable to collect prometheus metrics.

## Steps to reproduce
1. Run ocis version 5.X.X
2. Update prometheus config as outlined in the [docs](https://doc.owncloud.com/ocis/5.0/monitoring/prometheus.html)
3. Restart prometheus with `--log.level=debug`

## Expected behavior

Metrics with name `ocis_...` are collected.

## Actual behavior

The metrics are not collected. I can see in the ocis logs a lot of these messages:

```
{"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"ocis/H6ynCsSHcg-000276","traceid":"5f7b3204e24fbe35019b78932110e1fc","remote-addr":"172.19.0.6:54172","method":"GET","status":200,"path":"/metrics","duration":2.292273,"bytes":7926,"time":"2024-05-14T15:49:37Z","line":"github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/accesslog.go:34","message":"access-log"}
```

and in the prometheus logs a lot of these messages:

```
ts=2024-05-14T15:51:07.732Z caller=scrape.go:1345 level=debug component="scrape manager" scrape_pool=ocis target=http://ocis:9200/metrics msg="Append failed" err="expected a valid start token, got \"<\" (\"INVALID\") while parsing: \"<\""
```

I'm not an expert in prometheus but it makes me thing the ocis /metrics endpoint isn't publishing in the correct format? Or maybe there are some additional steps to get set up beyond what is covered in the documentation.

## Setup

Running via docker compose behind caddy reverse proxy.

<details>
<p>

### Docker compose
```yml
services:
  ocis:
    container_name: ocis
    hostname: ocis
    image: owncloud/ocis:5.0.3
    mem_limit: "1G"
    env_file:
      - .env
    environment:
      # INSECURE: needed if oCIS / proxy is using self generated certificates
      OCIS_INSECURE: true
      OCIS_LOG_LEVEL: info
      PROXY_HTTP_ADDR: 0.0.0.0:9200
      PROXY_TLS: false

      WEB_OIDC_CLIENT_ID: owncloud-web
      PROXY_OIDC_REWRITE_WELLKNOWN: true
      PROXY_OIDC_ACCESS_TOKEN_VERIFY_METHOD: none
      PROXY_USER_OIDC_CLAIM: preferred_username
      PROXY_USER_CS3_CLAIM: username
      PROXY_AUTOPROVISION_ACCOUNTS: true
    volumes:
      - ./config/ocis.yaml:/etc/ocis/ocis.yaml
      - ./data:/var/lib/ocis
    ports:
      - '9200:9200'
    restart: unless-stopped

networks:
  default:
    name: caddy_net
    external: true
```

### .env file
```console
OCIS_URL=https://cloud.<domain>
OCIS_OIDC_ISSUER=https://auth.<domain>
OCIS_SERVICE_ACCOUNT_ID=...
OCIS_SERVICE_ACCOUNT_SECRET=...
```

### prometheus config
```yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: ocis
    static_configs:
      - targets: ['ocis:9200']
```

</p>
</details>

## Additional context

Like I said I'm not an expert but I think the metrics endpoint should expose a format like [this](https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-example) where currently it seems to be responding with an HTML document.
