### ISSUE TITLE
[PROPFIND][QA] add test coverage new props

### ISSUE THREAD

**Issue by grgprarup** [owncloud/ocis#9180]
There are new props added in PRs https://github.com/cs3org/reva/pull/4389 and https://github.com/cs3org/reva/pull/4684 , we can add test coverage for them.
Start with listing test scenarios and confirm with the team if we need those scenarios, then

add tests for:
- [x] PROPFIND:
    ```xml
    <oc:audio>
      <oc:album>ALBUM1234567890123456789012345</oc:album>
      <oc:artist>ARTIST123456789012345678901234</oc:artist>
      <oc:genre>Pop</oc:genre>
      <oc:title>TITLE1234567890123456789012345</oc:title>
      <oc:track>1</oc:track>
      <oc:year>2001</oc:year>
    </oc:audio>
    <oc:location>
      <oc:latitude>28.209538</oc:latitude>
      <oc:longitude>83.991402</oc:longitude>
    </oc:location>
    <oc:image>
      <oc:width>1240</oc:width>
      <oc:height>648</oc:height>
    </oc:image>
    <oc:photo>
      <oc:camera-make>Canon</oc:camera-make>
      <oc:camera-model>Canon EOS 1D Mark II</oc:camera-model>
      <oc:f-number>1.8</oc:f-number>
      <oc:focal-length>55</oc:focal-length>
    </oc:photo>
    ```
  - `audio` prop 
  - `location` prop
  - `image` prop
  - `photo` prop
  
   Scenarios: check above properties
  - [x] Project Space @Salipa-Gurung - https://github.com/owncloud/ocis/pull/9367
  - [x] Personal Space https://github.com/owncloud/ocis/pull/9606
  - [x] Shares Space by sharee https://github.com/owncloud/ocis/pull/9606

- [x] GET drive item: `graph/v1.0/drives/{drive-id}/items/{item-id}` (https://github.com/owncloud/ocis/pull/7886) @nirajacharya2 
  ```yml
  {
    "audio": {
      "album": "ALBUM1234567890123456789012345",
      "artist": "ARTIST123456789012345678901234",
      "genre": "Pop",
      "title": "TITLE1234567890123456789012345",
      "track": 1,
      "year": 2001
    },
  ...
  }
  ```
  - `audio` prop 
  - `location` prop
  - `image` prop
  - `photo` prop

   Scenarios: check above properties
  - [x] Project Space https://github.com/owncloud/ocis/pull/9614
  - [x] Personal Space https://github.com/owncloud/ocis/pull/9612
  - [x] Shares Space by sharee https://github.com/owncloud/ocis/pull/9616

- :exclamation: `graph/v1beta1/drives/{drive-id}/items/{item-id}` https://github.com/owncloud/ocis/issues/9521
