### ISSUE TITLE
Ldap certificate not found

### ISSUE THREAD

**Issue by aikooo7** [owncloud/ocis#9443]
## Describe the bug
Ocis can't find ldap certificate.

## Steps to reproduce

[Follow the official guide](https://owncloud.dev/ocis/guides/ocis-local-docker/)

## Expected behavior
Ocis starting.

## Actual behavior
Ocis complaining about ldap certificate not existing.

## Setup
I started ocis with the following docker compose file:

<details>
<p>

```
services:
  ocis:
    image: owncloud/ocis:latest
    container_name: owncloud
    entrypoint:
      - /bin/sh
    # run ocis init to initialize a configuration file with random secrets
    # it will fail on subsequent runs, because the config file already exist
    # therefore we ignore the error and then start the ocis server
    command: ["-c", "ocis init || true; ocis server"]
    environment:
      PROXY_TLS: "false"
      OCIS_INSECURE: "true"
      OCIS_URL: "https://subdomain.domain.com"
      OCIS_LOG_LEVEL: info
      OCIS_CONFIG_DIR: /etc/ocis
      OCIS_BASE_DATA_PATH: /var/lib/ocis
    networks:
      - proxy-network
    volumes:
      - /path/to/something:/etc/ocis
      - /path/to/something/else:/var/lib/ocis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.owncloud.rule=Host(`https://subdomain.domain.com`)"
      - "traefik.http.routers.owncloud.entrypoints=websecure"
      - "traefik.http.services.owncloud.loadbalancer.server.port=9200"

networks:
  proxy-network:
    external: true
```

</p>
</details>

## Additional context
Not needed.
