### ISSUE TITLE
OCIS (docker version at least)  does not allow to log in when firewall is active

### ISSUE THREAD

**Issue by carcuevas** [owncloud/ocis#9658]
## Describe the bug
Cannot login to OCIS when not allowing in firewall the IP `3.130.156.83`

## Steps to reproduce
1. Install ocis-rolling:6.1.0 docker version (also happening with the version 5) and just turn on the firewall and be sure that port 80 and 443 are closed to the World just open to some IPs 

## Expected behavior
I should be able to login even when the firewall is active

## Actual behavior
Well the the login page 

## Setup
I am using Ubuntu 24.04 in a EC2 machine with docker in which I am running  the following config: 

`docker-compose.yml` 

```yaml
services:
  nginx:
    image: nginx:1.21
    container_name: nginx
    restart: always
    environment:
      TZ: Etc/UTC
    volumes:
      - /opt/docker/owncloud/nginx:/etc/nginx/conf.d:ro
      - /var/log/nginx:/var/log/nginx
    ports:
      - 80:80
    networks:
      - owncloud
  owncloud:
    image: owncloud/ocis-rolling:6.1.0
    restart: always
    entrypoint:
      - /bin/sh
    command: ["-c",  "ocis init || true; ocis server"]
    container_name: owncloud
    volumes:
      - "/owncloud/data:/var/lib/ocis"
      - "/owncloud/config/ocis/ocis-config:/etc/ocis"
      - "/owncloud/config/web-config/:/config"
      - "/owncloud/config/web/dist:/dist"
      - "/var/log/owncloud:/logs"
    environment:
      OCIS_URL: https://my_ocis_domain.com
      OCIS_LOG_FILE: "/logs/output.log"
      PROXY_HTTP_ADDR: "0.0.0.0:9200"
      STORAGE_USERS_DRIVER: "s3ng"
      STORAGE_USERS_S3NG_ROOT: "/var/lib/ocis/metadata"
      STORAGE_SYSTEM_DRIVER: "ocis"
      STORAGE_USERS_S3NG_ENDPOINT: "https://s3-accesspoint.us-east-2.amazonaws.com"
      STORAGE_USERS_S3NG_REGION: "us-east-2"
      STORAGE_USERS_S3NG_ACCESS_KEY:  [REDACTED]
      STORAGE_USERS_S3NG_SECRET_KEY: [REDACTED]
      STORAGE_USERS_S3NG_BUCKET: "my-oci-bucket-name"
      DEMO_USERS: "false"
      PROXY_TLS: "false"
      OCIS_INSECURE: "true"
      OCIS_LOG_PRETTY: "true"
      OCIS_LOG_LEVEL: "info"
      expose: 9200
    networks:
      - owncloud

networks:
  owncloud:
```

`nginx-owncloud.conf`  

```nginx
# Upstreams
upstream owncloud {
    server owncloud:9200;
}

# HTTP Server
server {
    listen 80;
    server_name cloud.medojed.info;

    location /health-check {
      return 200;
    }

    location / {
        proxy_pass http://owncloud;
        proxy_buffers 4 256k;
        proxy_buffer_size 128k;
        proxy_busy_buffers_size 256k;

        # Disable checking of client request body size
        client_max_body_size 0;
        proxy_set_header Host $host;
    }
}

```

Also I am running the AWS ELB for HTTPS (certificate managed by AWS)

## Additional context
I have realized by chance, when trying to login allowing just my Public IP address and a few others, once OCIS is asking for the username and password it won't login and instead it will show: 

```
Logging you in
Please wait, you are being redirected.

ownCloud – A safe home for all your data

```

After some time it will timeout... and it wont login.... 

So I open to the World the Security Group, and I could login without any troubles, I checked the logs from the nginx and I saw this activity: 

```
"GET /.well-known/openid-configuration HTTP/1.1" 200 1802 "-" "Go-http-client/1.1" "3.130.156.83"
"GET /konnect/v1/jwks.json HTTP/1.1" 200 1609 "-" "Go-http-client/1.1" "3.130.156.83"
"GET /konnect/v1/userinfo HTTP/1.1" 200 265 "-" "Go-http-client/1.1" "3.130.156.83"
"GET /konnect/v1/userinfo HTTP/1.1" 200 265 "-" "Go-http-client/1.1" "3.130.156.83"
"PATCH /data/[REDACTED!!!] HTTP/1.1" 204 0 "-" "Go-http-client/2.0" "3.130.156.83"


```

why this is happening?

Thanks
