### ISSUE TITLE
Unexpected error sharing with users from mobile clients

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ocis#9681]
## Describe the bug

Using mobile clients Android and iOS, sharing with other users returns an error (reproduced in `ocis.ocis.master.owncloud.works`, in stable 5.0.6 works). But, it works in web client. Something different somewhere

## Steps to reproduce

1. Log in with any user
2. Try to share any file or folder with other user

Let's curlizy it (Android request):

```
curl 'https://ocis.ocis.master.owncloud.works/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json' \
  -X 'POST' \
  -H 'accept-encoding: identity' \
  -H 'accept-language: en' \
  -H 'authorization: Bearer ... \
  -H 'connection: Keep-Alive' \
  -H 'content-length: 63' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -H 'host: ocis.ocis.master.owncloud.works' \
  -H 'ocs-apirequest: true' \
  -H 'user-agent: Mozilla/5.0 (Android) ownCloud-android/4.3.1' \
  -H 'x-request-id: c3573187-cdef-4073-9e2a-8d1103ced807' \
  --data-raw 'path=%2FtestShare%2F&shareType=0&shareWith=katherine&permissions=31' \
  --compressed
```

## Expected behavior

Content shared

## Actual behavior

Error:

```
{"ocs":{"meta":{"status":"error","statuscode":400,"message":"resharing not supported"}}} 
```

action was not a resharing, just a direct share of an item. 

## Setup

reproducible in `ocis.ocis.master.owncloud.works`

ownCloud Web UI 9.2.0-alpha.1 
Infinite Scale 6.1.0+baa0c23c3 Community 

not reproducible in stable 5.0.6.... something is missing in the middle. I created the 5.0.6 instance with the following `docker-compose-yml` file:

```
version: "3.7"

services:
  ocis:
    image: owncloud/ocis:5.0.6
    ports:
      - 9200:9200
      - 9215:9215
    environment:
      OCIS_INSECURE: "true"
      OCIS_URL: "..."
      IDM_CREATE_DEMO_USERS: "true"
      IDM_ADMIN_PASSWORD: "admin"
      PROXY_ENABLE_BASIC_AUTH: "true"
      OCIS_PASSWORD_POLICY_MIN_CHARACTERS: "8"
      OCIS_PASSWORD_POLICY_MIN_LOWERCASE_CHARACTERS: "1"
      OCIS_PASSWORD_POLICY_MIN_UPPERCASE_CHARACTERS: "1"
      OCIS_PASSWORD_POLICY_MIN_DIGITS: "1"
      OCIS_PASSWORD_POLICY_MIN_SPECIAL_CHARACTERS: "1"
      OCIS_SERVICE_ACCOUNT_ID: "b0fbfad7-3dd6-49cb-b468-3f588f2f82be"
      OCIS_SERVICE_ACCOUNT_SECRET: "asaGE4DF"
    restart: "no"
    entrypoint:
      - /bin/sh
    # run ocis init to initialize a configuration file with random secrets
    # it will fail on subsequent runs, because the config file already exists
    # therefore we ignore the error and then start the ocis server
    command: ["-c", "ocis init || true; ocis server"]
```
