### ISSUE TITLE
posix storage driver: cannot open files

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#9909]
DISCLAIMER: this is a ticket I opened as a private person and not as an employee of ownCloud

## Describe the bug
When using the posix storage driver with oCIS 6.3.0, I can't open files

## Steps to reproduce
1. start the docker-compose
2. create a text file
3. try to open it

## Expected behavior
Being able to open and edit the file

## Actual behavior
See a HTTP 404 status code

## Setup
Following docker-compose:

```yaml
---
services:
  ocis:
    image: owncloud/ocis-rolling:6.3.0
    entrypoint:
      - /bin/sh
    command: ["-c", "ocis init || true; ocis server"]
    environment:
      OCIS_URL: https://localhost:9200
      OCIS_LOG_LEVEL: info
      PROXY_TLS: "true"
      OCIS_INSECURE: "true"
      STORAGE_USERS_DRIVER: posix
    ports:
      - 9200:9200
    volumes:
      - ./data/ocis-config:/etc/ocis
      - ./data/ocis-data:/var/lib/ocis
    networks:
      - ocis
    logging:
      driver: "local"
    restart: always
```
