### ISSUE TITLE
posix storage driver: storage path seems wrong

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#9910]
DISCLAIMER: this is a ticket I opened as a private person and not as an employee of ownCloud

## Describe the bug
When using the posix storage driver with oCIS 6.3.0, I see the data stored on a different path than the documentations suggests

## Steps to reproduce
1. start the docker-compose
2. create a text file as admin user
3. look at the storage location

## Expected behavior
the file is available on disk on this path (relative to the ocis data director `/var/lib/ocis`): `storage/owncloud/users/admin/test.txt`

This behaviour can be enforced by setting `STORAGE_USERS_POSIX_ROOT: /var/lib/ocis/storage/owncloud`

The documentation suggests this is already the default:

![image](https://github.com/user-attachments/assets/d1426b2d-d349-4ab7-b841-19e02c417107)

## Actual behavior
the file is available on disk on this path (relative to the ocis data director `/var/lib/ocis`): `users/admin/test.txt`

## Setup
Following docker-compose:

```yaml
---
services:
  ocis:
    image: owncloud/ocis-rolling:6.3.0
    entrypoint:
      - /bin/sh
    command: ["-c", "ocis init || true; ocis server"]
    environment:
      OCIS_URL: https://localhost:9200
      OCIS_LOG_LEVEL: info
      PROXY_TLS: "true"
      OCIS_INSECURE: "true"
      STORAGE_USERS_DRIVER: posix
    ports:
      - 9200:9200
    volumes:
      - ./data/ocis-config:/etc/ocis
      - ./data/ocis-data:/var/lib/ocis
    networks:
      - ocis
    logging:
      driver: "local"
    restart: always
```
